### ISSUE TITLE
关于重置密钥密码 reset-key-password

### ISSUE THREAD

**Issue by boy-good** [Bytom/bytom#1000]
#### 使用cli执行重置密码方法时，无论我的旧密码是否正确，都返回提示重置成功，但实际上是没有重置成功的。reset-key-password貌似有问题。

./bytomcli reset-key-password d6b4b0f1ab95132c69615f54d25f3ec0eb25e1bb178e7cda27e2c0304d0d03bead1d6c3009f38d1eeac0c2cdf2f16b32527f78f79ca8faab31592770760d7bc7 654 123
 
返回 Successfully reset key password

实际上密码还是原始的123456，并没有被改变

**Comment by oysheng** [comment]
这个是因为后端的结果处理形式修改了之后，bytomcli没有同步更新导致的，返回结果为
type ResetPasswordResp struct {
	Changed bool `json:"changed"`
}
Changed为true表示修改成功，否则表示密码修改失败。这个bug已经在dev上修复了，谢谢你提的issue

**Comment by guess00712** [comment]
How does the BTM wallet reset its password? What steps must be taken to reset the password?
![bsm 1](https://user-images.githubusercontent.com/40441569/41683083-36c3dd08-750c-11e8-85e9-070b9ede1790.jpg)

**Comment by Paladz** [comment]
click keys ---- more --- reset-passowrd
