### ISSUE TITLE
build-transaction 参数描述不清

### ISSUE THREAD

**Issue by LamentWy** [Bytom/bytom#1001]
####  build-transaction 参数中 actions的每个元素代表什么含义？

```
{
  "base_transaction": null,
  "actions": [
    {
      "account_id": "0BF63M2U00A04",
      "amount": 20000000,
      "asset_id": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
      "type": "spend_account"
    },
    {
      "account_id": "0BF63M2U00A04",
      "amount": 99,
      "asset_id": "3152a15da72be51b330e1c0f8e1c0db669269809da4f16443ff266e07cc43680",
      "type": "spend_account"
    },
    {
      "amount": 99,
      "asset_id": "3152a15da72be51b330e1c0f8e1c0db669269809da4f16443ff266e07cc43680",
      "receiver": {
        "control_program": "0014a3f9111f3b0ee96cbd119a3ea5c60058f506fb19"
      },
      "type": "control_receiver"
    }
  ],
  "ttl": 0,
  "time_range": 1521625823
}
```
比如api文档里这个sample， 谁能详细解释一下 actions[0]~actions[2]是什么含义？

难道说第一个是定义手续费，第二个是定义转账资产类型和数量，第三个是定义接收方地址？

还有我build不同含义的 transaction，actions.type 如何组合 以及每种type的含义 有没有一个文档？

看得很迷啊。

**Comment by prettyCoders** [comment]
对，描述有点不清楚，虽然大概知道前面两个是Input，后面control_program是账户生成的所谓的控制程序或者说是账户的另一种表示方式。还有就是本地浏览器钱包有创建新地址的按钮，为什么不提供API呢？还有就是transaction type is address的意思就是接收方可以是BTM地址对吗？

**Comment by prettyCoders** [comment]
还有就是不支持备注嘛？

**Comment by LamentWy** [comment]
@prettyCoders   经过我的测试，actions数组的那仨元素跟我猜的意思基本一致。

至于control_program ,你用命令行生成一次地址就知道了，他跟address是 一一对应的。

但是问题又来了，使用GUI钱包时，根本看不到这个control_program ，只能看到address.

没有这个control_program，光靠address又没办法build_transaction,会报required field is missing。

根据address查control_program的接口也没找到。

等开发人员回复吧。  发起交易相关的三个接口设计的太不友好了。

**Comment by prettyCoders** [comment]
@LamentWy 确实，为什么GUI钱包能一键发送交易，而API需要创建、签名、广播三个步骤？还有请教一下actions数组的那仨元素，您的测试结果是？

**Comment by prettyCoders** [comment]
@LamentWy 好的，知道了，谢谢。等同步好了我也去测试一下
