### ISSUE TITLE
No payments recieved

### ISSUE THREAD

**Issue by Bling2018** [Bytom/bytom#1005]
#### Environment

- OS: Windows 10

#### Problem Description

no payments recieved to wallet.

bm1qgdx9rt9dsup94tnx57h443nlte5atjaehrvg8u
--
Please assist in issues of payments not showing in wallet

**Comment by Blockmeta** [comment]
send again. Maybe it hadn't included in a certain block.

**Comment by Bling2018** [comment]
I still haven't received a few payments, the one most worried about is 5/21/2018. at bottom you need to resend please.



________________________________

**Comment by Paladz** [comment]
You can check your balance here:
http://blockmeta.com/address/bm1qgdx9rt9dsup94tnx57h443nlte5atjaehrvg8u

Plz double check that you are sync to the highest block
