### ISSUE TITLE
不同方式获取的difficulty不一样。

### ISSUE THREAD

**Issue by jacky007wang** [Bytom/bytom#1009]
curl  -X POST http://localhost:9888/get-block -d '{"block_height":0}'
得到：2967955637

curl  -X POST http://localhost:9888/get-difficulty -d '{"block_height":0}'
得到：15154807

./bytomcli get-difficulty --height 0
得到：2967955637

./bytomcli get-block 0
得到：15154807

应该以哪种为准？

OS: Mac
Bytomd: 1.0.2

**Comment by Paladz** [comment]
dup issue, close
https://github.com/Bytom/bytom/issues/1010
