### ISSUE TITLE
不同时刻获取到的block信息不同

### ISSUE THREAD

**Issue by jacky007wang** [Bytom/bytom#1011]
OS: Ubuntu
Bytomd: 1.0.2

现象：
同一个block height（29160），两次获取的block数据不同，都是通过curl 调用 http api获取。
curl  -X POST http://localhost:9888/get-block -d '{"block_height":29160}'

第一次得到的结果：
{"data": {"bits": 2089670227100004982, "difficulty": "2967955637", "hash": "070ee0935acc51467aa4b3915ed97f1b630e4111faaf735190a5b61789ff26f9", "height": 29160, "nonce": 88310970060861, "previous_block_hash": "2e6c3747fa20eca462828d28dfd99dba646c56c0e85ec6524f9139ee3987d7ef", "size": 404, "timestamp": 1527811742, "transaction_merkle_root": "cb7156d0639355043eaa712cb0f4acf7fb670569dca31879310990f8fa46b7c2", "transaction_status_hash": "c9c377e5192668bc0a367e4a4764f11e7c725ecced1d7b6a492974fab1b6d5bc", "transactions": [{"id": "77d6727a6d53e600b05dd9698286e29e9ea8a201169bceb90bd5b4014d93ba45", "inputs": [{"amount": 0, "arbitrary": "e787a8", "asset_definition": {}, "asset_id": "0000000000000000000000000000000000000000000000000000000000000000", "type": "coinbase"}], "outputs": [{"address": "bm1qsk6dj6pym7yng0ev7wne7tm3d54ea2sjz5tyxk", "amount": 41250000000, "asset_definition": {}, "asset_id": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "control_program": "001485b4d96824df89343f2cf3a79f2f716d2b9eaa12", "id": "8414bbfb45cd0dfe16a2e341aeec760f41e316249bc7bd562b521418c3eae13b", "position": 0, "type": "control"}], "size": 78, "status_fail": false, "time_range": 0, "version": 1}], "version": 1}, "status": "success"}

过一段时间后，再获取一次，得到结果：
{"data": {"bits": 2089670227100004982, "difficulty": "2967955637", "hash": "6433e1f43e6e4a387a2c12b6be8e21d7dfc94e38671bf119ecef782d2b2e554d", "height": 29160, "nonce": 121981078411027689, "previous_block_hash": "2e6c3747fa20eca462828d28dfd99dba646c56c0e85ec6524f9139ee3987d7ef", "size": 408, "timestamp": 1527811681, "transaction_merkle_root": "61aa002e1f3799ff1dec085c4cbfae1a223da90c3412ebe51c0831f472d2618b", "transaction_status_hash": "c9c377e5192668bc0a367e4a4764f11e7c725ecced1d7b6a492974fab1b6d5bc", "transactions": [{"id": "1f802a9c61a2f6e25f3d1a49361a00de9259c0961e273d3aedde0b98c88bdbce", "inputs": [{"amount": 0, "arbitrary": "e787a8", "asset_definition": {}, "asset_id": "0000000000000000000000000000000000000000000000000000000000000000", "type": "coinbase"}], "outputs": [{"address": "bm1qcxg0w7c70tdd46t7dxn204mkyeyudcz063s49e", "amount": 41250000000, "asset_definition": {}, "asset_id": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "control_program": "0014c190f77b1e7adadae97e69a6a7d7762649c6e04f", "id": "df7b2ef75a2752efac870f056ef66764dcb3d4934bd3b62a273bea72f5eaf448", "position": 0, "type": "control"}], "size": 78, "status_fail": false, "time_range": 0, "version": 1}], "version": 1}, "status": "success"}

**Comment by oysheng** [comment]
这个有可能是因为这个区块被算力大的矿工替代出块了，由于现在查的是第二个结果，请问现在还可以复现这个问题吗？

**Comment by jacky007wang** [comment]
应该是你说的原因，分叉然后块被丢弃
