### ISSUE TITLE
B3在蚂蚁矿池支付到Bytom Wallet未收到

### ISSUE THREAD

**Issue by vvviper** [Bytom/bytom#1012]
#### Environment

- OS: ???

#### Problem Description

同样的Bytom Wallet地址，2018/5/21和5/22两笔从antpool转出的都可以在bytom wallet的交易查询里查到，数量也对
但是2018/5/23---2018/6/1期间的转账，一共10笔，有3笔状态是支付中，剩余的7笔都显示已支付，Bytom Wallet交易里却没有任何记录
附：
Transaction链接:
87e133278e49ce8595a09c1cc87e6f51b2c4bbd64107e63283dcb7a46c4e975a--显示已支付却未收到

--

请问是什么问题？

**Comment by MartinBTM** [comment]
收到了吗？ 区块浏览器显示有5158.4208 BTM  如果没有问题就关闭问题了
