### ISSUE TITLE
DOES ANYONE WORK FOR BYTOMWALLET.IO? IS THE PROJECT DEAD? IS ANYONE GOING TO ANSWER THESE PAST INQUIRIES REGARDING SENDING A TRANSACTION?

### ISSUE THREAD

**Issue by drew92flip** [Bytom/bytom#1013]
Please see below. Is anyone going to sufficiently address these issues? I am having the same issues as the below referenced users. When attempting to send from my desktop wallet it is rejecting any address that I input. Is the receiving party required to have a wallet address starting in ‘bm’? Any address that I attempt to send to which begins with ‘0X’ is being denied.... Why is this happening? It is an important function for a wallet to be able to send your funds... please advise.

https://github.com/Bytom/bytom/issues/989

https://github.com/Bytom/bytom/issues/990

**Comment by HAOYUatHZ** [comment]
0x... is an erc20 addr
bm... is a mainnet addr

plz use mainnet addr for our wallet

**Comment by yayayahnoo** [comment]
hi, so how can we exchange bytom?

**Comment by HAOYUatHZ** [comment]
gate.io has already support bm.. address
