### ISSUE TITLE
[外部测试]增加接口以导入观察地址

### ISSUE THREAD

**Issue by Clarenous** [Bytom/bytom#1015]
#### 简单描述

某些情况下，可能需要对钱包做冷存储，此时将不便从本地节点获得冷钱包信息。所以，建议增加接口，允许导入一些观察地址，同时应允许手动开启链的重新扫描，以获得导入观察地址的交易信息。(类似Bitcoin-Cli 中的API)

#### 接口示例

可实现类似的效果：

用户首先设置观察地址：`./bytomcli importAddress "Bytom Address" "Nickname"`

随后手动重新扫描区块链：`./bytomcli rescan startHeight endHeight`

过程中可手动停止扫描：`./bytomcli stopRescan`

**Comment by Paladz** [comment]
1. 通过区块链浏览器查看，比如 https://blockmeta.com/address/bm1q3yt265592czgh96r0uz63ta8fq40uzu5a8c2h0

2. 备份钱包，然后恢复到观察节点上即可（可以删除私钥信息）
