### ISSUE TITLE
[外部测试]钱包变动时应提醒用户备份

### ISSUE THREAD

**Issue by Clarenous** [Bytom/bytom#1016]
#### 原因

使用DashBoard 或DesktopWallet 时，用户可能在某个时间点A备份过钱包。但在时间点B时，若用户创建了新的密钥或账户，则钱包文件已经发生变化，而用户很可能忘记再次备份、或不了解需要再次备份，进而部分丢失数字资产。

#### 改善建议

在DashBoard 或DesktopWallet 中，每当用户进行了导致钱包文件变化的操作(创建新密钥、账户等)时，应在醒目位置对用户进行醒目的提示，例如“钱包文件已发生变化，请立即重新备份”。

**Comment by MartinBTM** [comment]
好建议

**Comment by Paladz** [comment]
1.0.7已经加入了动态地址扩张，同一个账户只要备份一次就够了
