### ISSUE TITLE
difficulty.CompactToBig与BigToCompact的疑问

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#1019]
在`difficulty`包下有一个`CompactToBig`与`BigToCompact`方法，用于计算难度值：

<https://github.com/Bytom/bytom/blob/678de9e03736c33c8e8752e2b27507a1f1bcafed/consensus/difficulty/difficulty.go#L59-L117>

我写了一个测试，连续调用这两个方法互转：

```
package main

import (
	"fmt"
	"github.com/bytom/consensus/difficulty"
)

func main() {
	compact := uint64(2342343323542345)
	big := difficulty.CompactToBig(compact)
	compactAgain := difficulty.BigToCompact(big)
	bigAgain := difficulty.CompactToBig(compactAgain)

	fmt.Println("      compact:", compact)
	fmt.Println("          big:", big)
	fmt.Println("compact again:", compactAgain)
	fmt.Println("    big again:", bigAgain)
}

```

结果如下：

```
      compact: 2342343323542345
          big: 139614541
compact again: 288230376152257113
    big again: 139614464
```

可以看到两次compact与big的值并不相等，两次compact的值相差100倍以上，两次big的值相差77。这样的不精确性是设计出来的吗？由于在计算新的难度值时，需要用到它们进行转换及乘除，所以对此有疑问

**Comment by freewind** [comment]
这个问题的原因是从big到compact的转换本身是有可能有精度损失的（太小的数位可能会被忽略），所以对于某些数来说，来回转就会有损失。同时由于比原的设计，CompactToBig也是有可能有精度损失的，所以就出现了本题所示的情况

**Comment by freewind** [comment]
又找了一些例子，将某些数先BigToCompact，再CompactToBig，得到的数与原数可能有很大的误差：

```
--------------  6480200000000000000  -------------
6480199377204805632
diff: -622795194368
--------------  6480300000000000000  -------------
6480299432762933248
diff: -567237066752
--------------  6480400000000000000  -------------
6480399488321060864
diff: -511678939136
```

以上数据的格式为：
```
--------------- 原数 -------------------
两次转换后的数字
diff: 相差
```

可见相差可能出现上千亿，或者说是原来的1亿分之1，这样的误差会给难度的计算带来意外的不确定性吗？

**Comment by freewind** [comment]
经过我的计算，这个误差并不会给难度值的计算带来可觉察的影响。我使用的代码大概如下：

```
package main

import (
	"fmt"
	"math/big"
	"github.com/bytom/consensus/difficulty"
)

// 302400 = 150秒 * 2016

var (
	genesisCompact   = uint64(2161727821137910632)
	genesisBigInt, _ = new(big.Int).SetString("7640617385137161009307348744505657205600476961500639119722770042191872", 10)
)

func main() {
	fmt.Println(genesisBigInt)
	fmt.Println(genesisCompact)
	fmt.Println(difficulty.CompactToBig(genesisCompact))

	calcWithoutCompact()
	fmt.Println("-----------------")
	calcWithCompact()
}

func calcWithCompact() {
	oldCompact := genesisCompact
	i := 0
	for i < 200000 {
		i += 1
		actualSpan := 302400 - 100

		oldBigInt := difficulty.CompactToBig(oldCompact)
		newTarget := big.NewInt(0)
		newTarget.Mul(oldBigInt, big.NewInt(int64(actualSpan)))
		newTarget.Div(newTarget, big.NewInt(302400))
		fmt.Println(i, " oldTarget:", newTarget)
		fmt.Println(i, " newTarget:", newTarget)

		oldCompact = difficulty.BigToCompact(newTarget)
	}
}

func calcWithoutCompact() {
	oldTarget := genesisBigInt
	i := 0
	for i < 200000 {
		i += 1
		actualSpan := 302400 - 100
		newTarget := big.NewInt(0)
		newTarget.Mul(oldTarget, big.NewInt(int64(actualSpan)))
		newTarget.Div(newTarget, big.NewInt(302400))
		fmt.Println(i, " oldTarget:", oldTarget)
		fmt.Println(i, " newTarget:", newTarget)

		oldTarget = newTarget
	}
}
```

两边计算出来的难度值误差在万分之几，我觉得可以忽略不计。

**Comment by Leekailklk** [comment]
package main
    
    import (
    	"fmt"
    	"math/big"
    
    	"github.com/bytom/consensus/difficulty"
    )
    
    var (
    	genesisCompact   = uint64(2161727821137910632)
    	genesisBigInt, _ = new(big.Int).SetString("7640617385137161009307348744505657205600476961500639119722770042191872", 10)
    )
    ``
    func main() {
    	fmt.Println(genesisBigInt)
    	fmt.Println(genesisCompact)
    	fmt.Println(difficulty.CompactToBig(genesisCompact))
    	lastResultWithCompact := calcWithCompact()
    	fmt.Println("lastResultWithCompact   :", lastResultWithCompact)
    }
    func calTarget(oldTargetOne *big.Int) *big.Int {
    	newTarget := big.NewInt(0)
    	newTarget.Mul(oldTargetOne, big.NewInt(100))
    	return newTarget.Div(newTarget, big.NewInt(1000))
    }
    
    func calcWithCompact() *big.Int {
    	oldCompact := genesisCompact
    	oldTarget := difficulty.CompactToBig(oldCompact)
    	for i := 1; i <= 30; i++ {
    		oldTarget = difficulty.CompactToBig(oldCompact)
    		fmt.Println(i, " oldTarget:", oldTarget)
    		newTarget := calTarget(oldTarget)
    		fmt.Println(i, " newTarget:", newTarget)
    		oldCompact = difficulty.BigToCompact(newTarget)
    	}
    	return oldTarget
    }
先上代码，根据freewind兄代码改了一下，（比较懒没重新写一个）。
对于使用CompactToBig（）和BigToCompact（）进行转换精度损失问题，我认为只要保证根据当前难度计算下一难度时的精度损失不要过大即可，因为当前难度是已经事实存在的可用难度，计算难度的目的是为了根据当前的2016区块出块情况对系统进行调整，保证系统根据当前算力维持2.5分钟出块的节奏。实测每次使用这两个函数进行难度调整时的精度误差小于百万分之一以上，这对系统调整没有任何实际影响。

另外，测试了假设系统难度调整10倍，连续调整30次，即难度最终增加10的30次方倍，这应该是很大的难度了。可以看到输出结果如下：
    7640617385137161009307348744505657205600476961500639119722770042191872
    2161727821137910632
    7640617385137161009307348744505657205600476961500639119722770042191872
    1  oldTarget: 7640617385137161009307348744505657205600476961500639119722770042191872
    1  newTarget: 764061738513716100930734874450565720560047696150063911972277004219187
    2  oldTarget: 764061656238488234870432766702106592692522447013270630293283836788736
    2  newTarget: 76406165623848823487043276670210659269252244701327063029328383678873
    3  oldTarget: 76406124486234890456892222795981095335489620132930422189831799963648
    3  newTarget: 7640612448623489045689222279598109533548962013293042218983179996364
    4  oldTarget: 7640611163073053638497001846028435660618879995530647192748911755264
    4  newTarget: 764061116307305363849700184602843566061887999553064719274891175526
    5  oldTarget: 764060473532087660253589967818006629596846990671867206157757054976
    5  newTarget: 76406047353208766025358996781800662959684699067186720615775705497
    6  oldTarget: 76406043586947724793350538480327009035084849405773453937354997760
    6  newTarget: 7640604358694772479335053848032700903508484940577345393735499776
    7  oldTarget: 7640601220143904785994671930137989299675276889399623161718243328
    7  newTarget: 764060122014390478599467193013798929967527688939962316171824332
    8  oldTarget: 764055100333002169254856124382260363834394807055606744944214016
    8  newTarget: 76405510033300216925485612438226036383439480705560674494421401
    9  oldTarget: 76405495321343024612952572198094575740471317965665101531840512
    9  newTarget: 7640549532134302461295257219809457574047131796566510153184051
    10  oldTarget: 7640532368184244763340043606322753490584275266688341696839680
    10  newTarget: 764053236818424476334004360632275349058427526668834169683968
    11  oldTarget: 764053236818424476334004360632275349058427526668834169683968
    11  newTarget: 76405323681842447633400436063227534905842752666883416968396
    12  oldTarget: 76405247057065404338957518145876177390383571729927307788288
    12  newTarget: 7640524705706540433895751814587617739038357172992730778828
    13  oldTarget: 7640448080929497139452833897236260223579176236036621598720
    13  newTarget: 764044808092949713945283389723626022357917623603662159872
    14  oldTarget: 764044808092949713945283389723626022357917623603662159872
    14  newTarget: 76404480809294971394528338972362602235791762360366215987
    15  oldTarget: 76404405980411140052298926943699167162101155976620015616
    15  newTarget: 7640440598041114005229892694369916716210115597662001561
    16  oldTarget: 7640439721140131606688141772159017086440303804102475776
    16  newTarget: 764043972114013160668814177215901708644030380410247577
    17  oldTarget: 764043825963849427578522356847418437015728414816993280
    17  newTarget: 76404382596384942757852235684741843701572841481699328
    18  oldTarget: 76404382596384942757852235684741843701572841481699328
    18  newTarget: 7640438259638494275785223568474184370157284148169932
    19  oldTarget: 7640433692445877616713604181959082131772847723380736
    19  newTarget: 764043369244587761671360418195908213177284772338073
    20  oldTarget: 764039943850125267367645878309581534388957453746176
    20  newTarget: 76403994385012526736764587830958153438895745374617
    21  oldTarget: 76403981004565407618390702909527189849878841786368
    21  newTarget: 7640398100456540761839070290952718984987884178636
    22  oldTarget: 7640391410232981202652127830237237190479432384512
    22  newTarget: 764039141023298120265212783023723719047943238451
    23  oldTarget: 764039123600840933913163453698943818541410811904
    23  newTarget: 76403912360084093391316345369894381854141081190
    24  oldTarget: 76403833959026754807094363408384829574745161728
    24  newTarget: 7640383395902675480709436340838482957474516172
    25  oldTarget: 7640357262216895952635442353668632197675876352
    25  newTarget: 764035726221689595263544235366863219767587635
    26  oldTarget: 764035658165216211075851542691941733413945344
    26  newTarget: 76403565816521621107585154269194173341394534
    27  oldTarget: 76403259562391392262968037232047484750004224
    27  newTarget: 7640325956239139226296803723204748475000422
    28  oldTarget: 7640325424547940912330454561681924362862592
    28  newTarget: 764032542454794091233045456168192436286259
    29  oldTarget: 764032276609194934249870875406780380217344
    29  newTarget: 76403227660919493424987087540678038021734
    30  oldTarget: 76403225584000750011056036128479506333696
    30  newTarget: 7640322558400075001105603612847950633369
    lastResultWithCompact   : 76403225584000750011056036128479506333696    
即难度调整机制还在正常运行，    最后测算假设每年难度增加10倍，（实际随着难度越来越大，增加的倍数会越来越低，连续70次增加10倍几乎是不可能）。按照当前代码设定，最终系统难度调整可以运行70年。可见比原的代码设计还是健壮的。

**Comment by freewind** [comment]
这个问题差不多清楚了，我觉得可以关闭啦
