### ISSUE TITLE
Setup Mining Pool znomp or yiimp

### ISSUE THREAD

**Issue by goodthebest** [Bytom/bytom#1027]
Hi BYTOM Dev, Is there any implementation of bytom to setup pool either in znomp or yiimp software? Or you have any in-house pool software we can use to setup a bytom pool?

**Comment by HAOYUatHZ** [comment]
hi we focus on building a chain instead of a pool

you will need to integrate bytom into ur existing pool by urself

**Comment by HAOYUatHZ** [comment]
hi we focus on building a chain instead of a pool

you will need to integrate bytom into ur existing pool by urself
