### ISSUE TITLE
比原链dashboard交易异常提示

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#1043]
#### Environment

- OS: Win 7  64位

#### Problem Description
**过程描述：**
       当前账户BTM资产96个，计划转入到比特儿地址充值（主网地址），采用简单交易发起，输入账户、资产和转至地址、数量（95），选择gas（系统提示消耗不到1个）时，界面抛出异常“errors occurred in one or more actions -<action index 0:reserving utxos:reservation found outputs already reserved>”。同时提交交易按钮无法选择。
        经过多次尝试，调整转账资产数量为50个，仍然遇到如上异常。最后再次尝试交易90个，提示交易成功，但界面仍然提示“errors occurred in one or more actions -<action index 0:reserving utxos:reservation found outputs already reserved>”异常。具体见下图：
![_20180612111736](https://user-images.githubusercontent.com/34227886/41268696-fc6b2050-6e33-11e8-9b08-4d9edd67ea97.png)

**Comment by ZhitingLin** [comment]
“errors occurred in one or more actions -<action index 0:reserving utxos:reservation found outputs already reserved>”这个是说你build 太频繁了。上面的错误提示应该是之前交易失败的错误提示。错误提示5秒中会消失。交易成功的话就已经提交了。
