### ISSUE TITLE
命令行发出交易，交易失败！

### ISSUE THREAD

**Issue by yahtoo** [Bytom/bytom#105]
#### Environment

- OS: ???

#### Problem Description

命令行发出交易 bytomcli sub-spend-account-tx 06GRV0E800A02 06GRV31S00A04 10d3fae90d5ed23c3a1129de400dd96729f22642fe0f832492cb4a2ff5476a9c 1824467f271795d84c2c6495b953958ef8defeb34bd76778c454114ed802be6b298df65403821ee93e4f86ce6e39b8ff99867bb3ab9f119222968b73a515dfc1 10
错误返回
submit transaction:[map[code:CH000 message:Chain API Error temporary:true]]

**Comment by Paladz** [comment]
已修好
