### ISSUE TITLE
挖矿过程报“非法内存或空指针异常”自动断开

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#1059]
Environment

OS: Win 7 64位
Problem Description
运行的程序包是：bytom-1.0.2-windows_amd64.zip
报错截图如下：
![default](https://user-images.githubusercontent.com/34227886/41400353-7ccc39d4-6fef-11e8-9bcb-7b78ccc8a301.PNG)

**Comment by HAOYUatHZ** [comment]
plz try out our new version, thx
