### ISSUE TITLE
 problem with logging in

### ISSUE THREAD

**Issue by Roman9467** [Bytom/bytom#1068]
- OS: ??? Windows

The problem with entering the wallet, I can not restore my account, everything was fine and in one day the wallet simply asked me to create a new account, as if I was going into it for the first time, he just forgot my old wallet, what should I do? the backup did not save! Help!

**Comment by ZhitingLin** [comment]
Are you using the Bytom desktop? What version is that? Your files and everything should be in your local file, under %APPDATA%\Bytom. Just don't delete that file.

**Comment by Paladz** [comment]
Close this issue due to didn't get the new response in 30 days
