### ISSUE TITLE
构建事务的接口build-transaction太复杂了

### ISSUE THREAD

**Issue by lanmp** [Bytom/bytom#1078]
#### Environment

- OS: ???

#### Problem Description

build-transaction 这个接口可以给个详细的说明文档吗，太复杂了，或者有更简单的方法？像sendtoaddress sendfrom这样的

build-transaction
Arrary of Object - actions:
Object:
String - account_id | account_alias, alias or ID of account.
String - asset_id | asset_alias, alias or ID of asset.
Integer - amount, the specified asset of the amount sent with this transaction.
String- type, type of transaction, valid types: 'spend_account', 'issue', 'spend_account_unspent_output', 'control_address', 'control_program', 'retire'.
String - address, (type is control_address) address of receiver, the style of address is P2PKH or P2SH.
String - control_program, (type is control_program) control program of receiver.

**Comment by Paladz** [comment]
https://github.com/Bytom/bytom/wiki/API-Reference
