### ISSUE TITLE
区块浏览器的地址打不开，麻烦改一下 http://blockmeta.com

### ISSUE THREAD

**Issue by luxiaoxiaomo** [Bytom/bytom#1096]
![image](https://user-images.githubusercontent.com/30423156/41902367-d743c254-7965-11e8-99dd-601c2df2f45b.png)

区块浏览器的地址打不开，麻烦改一下 http://blockmeta.com
#### Environment

- OS: ???

**Comment by HAOYUatHZ** [comment]
fixed
