### ISSUE TITLE
1999 端口是用来干嘛的? 在 Dockerfile 中看到

### ISSUE THREAD

**Issue by DinoStray** [Bytom/bytom#1097]
在官方的 Dockerfile 中看到 
EXPOSE 1999 46656 46657 9888
其他端口我都知道干嘛的. 这个 1999 没弄清楚, 是做什么的端口?

**Comment by HAOYUatHZ** [comment]
Hi 1999 has been deprecated,
we will update our dockerfile asap

**Comment by HAOYUatHZ** [comment]
it has been deprecated, sorry for causing the confusion.
we will update the dockerfile asap
