### ISSUE TITLE
win64 钱包转账问题

### ISSUE THREAD

**Issue by pphaolu** [Bytom/bytom#1122]
#### Environment

- OS: windows 10
钱包版本 1.0.3

#### Problem Description

 转账的时候，第一次交易密码输错，再重新输入正确密码提示
![image](https://user-images.githubusercontent.com/35622701/42298357-0f638718-8038-11e8-8003-4519dfb8bdf6.png)
这样就不能转账了，即使是新建新的交易也不可以。

需要关闭钱包客户端，重新新建交易，才可以转账。

**Comment by Paladz** [comment]
因为钱包为了防止双花会锁定主utxo
