### ISSUE TITLE
交易

### ISSUE THREAD

**Issue by James-liou** [Bytom/bytom#1123]
#### Environment

- OS: Win 10 64

#### Problem Description

Wallet顯示餘額與收益顯示不符
![2018-07-05_130930](https://user-images.githubusercontent.com/40848130/42303600-c4c19e76-8054-11e8-970b-6773b9440dfe.jpg)
![2018-07-05_120706](https://user-images.githubusercontent.com/40848130/42303608-cbff8f0e-8054-11e8-8cb8-9c7d2b59cb0f.jpg)

**Comment by Blockmeta** [comment]
No fully synced.  Please watch out the "peer count". Keep it more than zero.

**Comment by Paladz** [comment]
Close du to didn't get response in 10 days
