### ISSUE TITLE
at what exchange can i deposit btm

### ISSUE THREAD

**Issue by elifederman** [Bytom/bytom#1138]
#### Environment

- OS: ???

**Comment by qty236** [comment]
I did it with success on gate.io

**Comment by joshmoore1234** [comment]
gate.io doesn't allow users from Japan, Canada or US. I'm having the same issue, wallet starts with bm and all exchanges are erc20 token.

**Comment by HAOYUatHZ** [comment]
huobi will support btm mainnet addr soon

**Comment by MartinBTM** [comment]
try  Bibox exchange ?

**Comment by Paladz** [comment]
https://coinmarketcap.com/currencies/bytom/#markets
