### ISSUE TITLE
Cannot send from wallet

### ISSUE THREAD

**Issue by limatsao** [Bytom/bytom#1227]
#### Environment

- OS: Windows 10

#### Problem Description

Error submitting form
Available UTXOs of account have been reserved: action index 0: reserving utxos: reservation found outputs already reserved
Error Code: BTM702

**Comment by Paladz** [comment]
wait for 5 minutes for UTXO get unlocked. Or you can download the v1.0.6

**Comment by mobsikx** [comment]
I got this with version v1.0.9, and it's not for the fist time:
Error submitting form
Available UTXOs of account have been reserved
Error Code: BTM702

No wonder that the coin went down...
