### ISSUE TITLE
submit transaction

### ISSUE THREAD

**Issue by liu-lewis** [Bytom/bytom#1242]
- OS: Linux leosubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

When I try to send multiple transactions from an account in short time by submit-transaction,always the first transaction will be successful(confirm), and the others will be fail.

**Comment by Paladz** [comment]
what's the error message?

**Comment by Paladz** [comment]
close due to didn't get response
