### ISSUE TITLE
support defer unlock

### ISSUE THREAD

**Issue by IBYoung** [Bytom/bytom#1256]
#### Environment

- OS: ???

#### Problem Description
在代码中较常用如下的习惯
        m.cacheMu.Lock()
	...
	m.cacheMu.Unlock()

个人建议可以采纳，如下的方式：
     lock.Lock()
    defer lock.Unlock()

**Comment by HAOYUatHZ** [comment]
大部分 情况 还是用   defer 方式的
有的情况下   并不是整个函数原子性  才分步lock、unlock
