### ISSUE TITLE
Crashes on Mojave Beta

### ISSUE THREAD

**Issue by patmccormick** [Bytom/bytom#1328]
#### Environment

- OS: Mac OS 10.14 Beta (18A377a)

#### Problem Description

Wallet does not launch

errors in log:

Sep  8 13:21:14 iMac-7 Bytom Wallet[76865]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep  8 13:21:21 iMac-7 Bytom Wallet[76869]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep  8 13:21:30 iMac-7 Bytom Wallet[76874]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**Comment by ZhitingLin** [comment]
The error looks like the apple system error. Could you please provided the bytomd error msg? ~/Library/Application\ Support/Bytom Wallet\logs\all.log

**Comment by Paladz** [comment]
Close due to didn't get the response

**Comment by patmccormick** [comment]
[2018-10-08T10:38:22.605] [INFO] main - Bytomd Network has been inited
[2018-10-08T10:38:23.932] [INFO] bytomd - bytomd mining: panic: Panicked on a Sanity Check: Error initializing DB: file missing [file=MANIFEST-000000]

goroutine 1 [running]:
github.com/bytom/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0x17b1820, 0xc42004aff0)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0xf3
github.com/bytom/vendor/github.com/tendermint/tmlibs/db.NewDB(0x18cd44d, 0x7, 0xc420506710, 
[2018-10-08T10:38:23.933] [INFO] bytomd - bytomd mining: 0x7, 0xc424945200, 0x2a, 0x0, 0x0)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/db/db.go:61 +0x188
github.com/bytom/node.NewNode(0xc420091200, 0x0)
	/Users/jnet/Documents/go/src/github.com/bytom/node/node.go:86 +0x3b6
github.com/bytom/cmd/bytomd/commands.runNode(0x2456e20, 0xc4201e00b0, 0x0, 0x1, 0x0, 0x0)
	/Users/jnet/Documents/go/src/github.com/bytom/cmd/bytomd/commands/run_node.go:73 +0x5a
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).execute(0x2456e20, 0xc4201e0090, 0x1, 0x1, 0x2456e20, 0xc4201e0090)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2456c00, 0xc42051bea8, 0x141f201, 0x1816780)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).Execute(0x2456c00, 0x141eab5, 0xc4201e0040)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/bytom/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x2456c00, 0x202aed8, 0x2, 0xc420014240)
	/Users/jnet/Documents/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/Users/jnet/Documents/go/src/github.com/bytom/cmd/bytomd/main.go:55 +0x78

[2018-10-08T10:38:23.941] [INFO] bytomd - bytom Mining exited with code 2
[2018-10-08T10:38:23.942] [INFO] main - Kill bytomd Mining command...
