### ISSUE TITLE
balance not updating on Mac wallet

### ISSUE THREAD

**Issue by raviproperty** [Bytom/bytom#1344]
#### Environment

- OS: mac 10.13 high sierra

#### Problem Description

i mined few bytom coins using a mining pool there were 11 bytom coins i was suppose to get 3 days back.
the coins are showing up in the https://blockmeta.com/address/bm1qqrzymekaxevaq8ddpyag9k3l2un5x6vnl0k4l4
but this has yet not credited to by bytom desktop wallet
my wallet public address: bm1qqrzymekaxevaq8ddpyag9k3l2un5x6vnl0k4l4

strange thing is that bytomscan.io is not able to identify this address but blockmeta.com is working fine.
i want my coins in my desktop wallet. please help

**Comment by MartinBTM** [comment]
hi，is your wallet syc all blocks? or you can rescan you balance

**Comment by raviproperty** [comment]
Yes. I tried multiple times to resync my wallet n scan my balance

**Comment by raviproperty** [comment]
any updates?

**Comment by raviproperty** [comment]
Ok thanks will try it

**Comment by MartinBTM** [comment]
hi are your problem solved?

**Comment by raviproperty** [comment]
No

**Comment by Paladz** [comment]
1. Did you have this address "bm1qqrzymekaxevaq8ddpyag9k3l2un5x6vnl0k4l4" on your wallet?
2. what's your local node's block height?
