### ISSUE TITLE
bytomcli cannot be used for other network.

### ISSUE THREAD

**Issue by rlaace423** [Bytom/bytom#1349]
Hello, I'm new to bytom.

I installed bytom and launched both testnet and solonet each (testnet with desktop wallet and solonet with bytomd binary).

Also, their root path is seperated (testnet : ~/Library/Bytom, solonet : ~/bytom/solonet)

but when I execute **bytomcli net-info**, it only shows testnet result. And I can't find in help to make bytomcli see other chain. (And also it is mistery how bytomcli found testnet root path without any configuration)

Is there any options?

**Comment by Paladz** [comment]
Bytomcli is a command line curl tool. It will call API to "http://localhost:9888"
I guess the reason why you get the testnet result is that your node is running the testnet.

**Comment by rlaace423** [comment]
Thank you for your answer. So, is there any options to change that url in bytomcli?
