### ISSUE TITLE
tansaction not recieved

### ISSUE THREAD

**Issue by antpoolfan** [Bytom/bytom#1356]
I am mining with antpool with the payment address: bm1qpp0fcqq2cnzg0wtn2tj34w4rphh8aa9932zfh5
I created this address with my Btyom official wallet downloaded. 

I can check the transaction on http://www.btmscan.com/address/bm1qpp0fcqq2cnzg0wtn2tj34w4rphh8aa9932zfh5/

But it is not shown on my Bytom wallet.
my wallet is 100% synced. 

Can anyone help?
have I done anything wrong?

**Comment by antpoolfan** [comment]
Sorry. Question answered. Not truly 100% synced. 
I transplanted the account to another "faster" computer, with updated Bytom Wallet.

The transaction was shown properly.

But it never shows up on my older computer with older version of Bytom. (it told me that it is synced, but it is not.)

**Comment by MartinBTM** [comment]
we have update our syc program, so the old version maybe not connect the new version node
