### ISSUE TITLE
Payment not Recieve

### ISSUE THREAD

**Issue by Japanpeach** [Bytom/bytom#1357]
I am mining with antpool with the payment address:bm1qkq2hv7n5eshmqdrxchqwrsr0ahp82ytm5d8rh4
I created this address with my Btyom official wallet downloaded.
I can check the transaction on http://www.btmscan.com/address/bm1qkq2hv7n5eshmqdrxchqwrsr0ahp82ytm5d8rh4/
But it is not shown on my Bytom wallet.
my wallet is 100% synced.

Problem Description: payments are sending but not being received since 8-30-18

**Comment by MartinBTM** [comment]
you can use the way below to fast syc:
https://bytom.io/wallet/

1.Make sure that you have last version of Bytom Wallet (v1.0.5 ) and have enough free space in destination disk.
2.Download object file and make sure you close Bytom Wallet software,
- For Windows users, replace object file in shortcut '%APPDATA%/Roaming/Bytom/data/core.db'

- For Mac users, replace object file in shortcut '~/Library/Bytom/data/core.db'

- For Linux users, replace object file in shortcut '~/.bytom/data/core.db'

3.Make sure that you set correct destination for datadir and replace object file to your downloaded bytom wallet folder.

**Comment by Paladz** [comment]
Please download the newest version and re-try
