### ISSUE TITLE
Asset Symbols should be unique across the entire bytom blockchain

### ISSUE THREAD

**Issue by yanilkr** [Bytom/bytom#1359]
It looks like Asset Alias is a name you can give to an asset id in your wallet. 

If I create an asset with Alias "ABC" and send it to my friend and they create an asset alias with same name "ABC" but different asset id, now it gets confusing. A wallet will have two assets with same name but different asset ids. This is a kind of security risk. Scammers can scam innocent people with this name confusion, not many people will verify Ids.

Please implement a global naming system to make sure asset symbols are unique across the blockchain.

Happy to provide more details if the description is not clear

**Comment by MartinBTM** [comment]
yeah, but the alias is only in your wallet not in blockchain, so it now you can use unique ID to distinguish the different assets, It is just not convenient for user , but maybe not security problem.

we have a solution calling ODIN (Open Data Index Name) ,  if you are interested ,you can join our tech group: https://t.me/BytomTech  or whatsapp group : https://chat.whatsapp.com/LtVvGeDjExdFVBQG3wksLi

**Comment by MartinBTM** [comment]
https://github.com/ppkpub/docs/tree/master/English
