### ISSUE TITLE
New asset declaration has field "symobol" instead of "symbol".

### ISSUE THREAD

**Issue by Agouri** [Bytom/bytom#1366]
I was wondering if this was a spelling mistake that made it through to the code.

Custom assets declaration accept `symobol = ""` in their description. Note the extra "o".
This is also reflected in the code in the Wiki and Documentation.

I checked that the BTM description has `symbol="BTM"`, which is correct, and different from `symobol`.

Was this done intentionally to differentiate between BTM (governing token) and custom assets? Or is this a mistake?

**Comment by Paladz** [comment]
Thanks for find the bug, we will fix it in the next release
