### ISSUE TITLE
[PROPOSAL] Partial unlocking of amounts of values in Smart Contracts, not just static full Amounts

### ISSUE THREAD

**Issue by Agouri** [Bytom/bytom#1367]
As a continuation of today's chat with Martin in the Telegram Bytom Dev group, I'm submitting this proposal as a request for **Partial / Step-by-step unlocking of value in Equity Smart Contracts.**

To describe it, I will be using the Example contract `LoanWithCollateral` that is provided in the Wiki:
```
contract LoanCollateral(assetLoaned: Asset,
                        amountLoaned: Amount,
                        repaymentHeight: Integer,
                        lender: Program,
                            borrower: Program) locks collateral {
  clause repay() requires payment: amountLoaned of assetLoaned {
    lock payment with lender
    lock collateral with borrower
  }
  clause default() {
    verify above(repaymentHeight)
    lock collateral with lender
  }
}
```

In this example, an **implementation of partial value unlocking would allow for a partial repayment of amountLoaned by the borrower** (for example, monthly).
So we could get a `requires payment` expression that doesn't re-use `amountLoaned` from the contract declaration, but instead holds the amount of assets the borrower (or user generally) gave in this transaction, to be compared to minimums and maximums according to your contract's logic at a later time.

----

Martin noted that UTXO objects are Boolean, and therefore can either Lock or Unlock value, not part of value. 
However, I'm hoping this gets worked on in the future as it unlocks a very useful feature in Bytom Smart contracts: Token-for-token, dynamic exchange of assets.

**Comment by MartinBTM** [comment]
hi Agouri，you can see the contract demo below(just test demo):

`contract PartLoanCollateral(assetLoaned: Asset,
                        amountLoaned: Integer,
                        blockHeight: Integer,
                        lender: Program,
                        borrower: Program) locks valueAmount of valueAsset {
  clause repay(amountPartLoaned: Integer) {
    if amountPartLoaned > 0 && amountPartLoaned < amountLoaned {
      lock amountPartLoaned of assetLoaned with lender
      lock valueAmount*amountPartLoaned/amountLoaned of valueAsset with borrower
      lock valueAmount-(valueAmount*amountPartLoaned/amountLoaned) of valueAsset with PartLoanCollateral(assetLoaned, amountLoaned-amountPartLoaned, blockHeight, lender, borrower)
    } else {
      lock amountLoaned of assetLoaned with lender
      lock valueAmount of valueAsset with borrower
    }
  }
  clause default() {
    verify above(blockHeight)
    lock valueAmount of valueAsset with lender
  }
}`

**Comment by Agouri** [comment]
This is exactly what I had in mind.

Will a contract like this compile/deploy through the API?

**Comment by Agouri** [comment]
As an update, and for you to better understand my request, I'll be expanding Martin's test example to what functionality I'd like to see:
```
contract PartLoanCollateral(assetLoaned: Asset,
                        amountLoaned: Integer,
                        blockHeight: Integer,
                        lender: Program,
                        borrower: Program) locks valueAmount of valueAsset {
  clause repay() requires payment: this_amount of assetLoaned {
    if( this_amount > 0 && this_amount < amountLoaned ){
        lock this_amount of assetLoaned with lender
        lock ( valueAmount * (this_amount / amountLoaned) ) of valueAsset with borrower
        lock ( valueAmount - ( valueAmount * (this_amount / amountLoaned) ) ) of valueAsset with PartLoanCollateral(assetLoaned, (amountLoaned - this_amount), blockHeight, lender, borrower)
    } else {
      lock amountLoaned of assetLoaned with lender
      lock valueAmount of valueAsset with borrower
    }
  }
  clause default() {
    verify above(blockHeight)
    lock valueAmount of valueAsset with lender
  }
}
```

**Comment by oysheng** [comment]
the expression "valueAmount*amountPartLoaned/amountLoaned" couldn't modify to  "( valueAmount * (this_amount / amountLoaned) ) ", because the type of "amount" is integer,  the result of "this_amount / amountLoaned" is zero, i think that it is not you hoped.

**Comment by Agouri** [comment]
Thank you Martin for the correction, we can bypass that by doing `all_amounts *= 10^8` and working with values multiplied to integers with 8 trailing zeroes.

What I would like to focus on though is not the code implementation itself, **but the placement of variables around the contract for partial unlocking**, and if these are planned/going to be supported in the future, and whether or not a contract like this can compile on the VM or not

**Comment by oysheng** [comment]
the contract for partial unlocking can be supported in the future, and the compiled program can be run on bytom VM.
