### ISSUE TITLE
btm如何获得私钥？

### ISSUE THREAD

**Issue by woyinzf** [Bytom/bytom#1398]
btm如何或者keystore的私钥，因为在create_key的时候，只返回了xpub，没有看到私钥。

是否有工具，或则cli命令，或者rpc方法，可以获得keystore的私钥？

私钥用于离线签名使用。

**Comment by Blockmeta** [comment]
keystore就是加密后的私钥

**Comment by HAOYUatHZ** [comment]
既然是 离线签名
密钥是不放在 bytomd 的，为什么要在 bytomd 取呢
而且rpc 明文传输 密钥不安全  (cli 其实也是走了 rpc)
如果真的需要的话  blockchain/pseudohsm/pseudohsm.go L141 把xprv打印出来
