### ISSUE TITLE
Java sdk 中 validate-address 有问题

### ISSUE THREAD

**Issue by boy-good** [Bytom/bytom#1422]
Address validate = new Account.AddressBuilder().validate(client, address);
其实返回的Address中并没有把vaild赋值进去，只赋值了isLocal
![image](https://user-images.githubusercontent.com/39320533/47428906-44f26480-d7c7-11e8-9b7d-c6c2c2efe887.png)
是不是 @SerializedName("is_local")没有加呢？

**Comment by successli** [comment]
sorry, 我的锅，应该是valid而非vaild，所以没有赋值进去，现在已经改过来了，地址https://github.com/Bytom/bytom-java-sdk

**Comment by boy-good** [comment]
@successli 感谢感谢
