### ISSUE TITLE
java sdk 的UnconfirmedTransaction中的list-unconfirmed-transactions有问题

### ISSUE THREAD

**Issue by boy-good** [Bytom/bytom#1447]
可以获取到区块的数据，但是方法返回时是永远为null的。没有赋值到
![image](https://user-images.githubusercontent.com/39320533/47948437-457bbf80-df6c-11e8-9e03-453ae441f201.png)

![image](https://user-images.githubusercontent.com/39320533/47948443-6512e800-df6c-11e8-9849-d9902b487fb0.png)

**Comment by wyjDoraemon** [comment]
请问一下你这个sdk是哪个版本的？ @ boy-good

**Comment by wyjDoraemon** [comment]
现在的版本已经没这个问题了  @boy-good
