### ISSUE TITLE
[bug]当钱包中存在自定义资产时，查询余额失败，node节点显示内存访问错误（非法指针）。

### ISSUE THREAD

**Issue by 421986908** [Bytom/bytom#1457]
系统环境：阿里云 centos7
btm版本：release v1.0.6rc1

复现步骤如下：

1. 准备一个新的钱包并创建一个新的账户。

2. 向账户转入BTM与自定义资产。

3.扫描钱包。

完成以上操作后去查询账户余额就会出现bug。尝试了3次，必现。

**Comment by Paladz** [comment]
已在1.0.7中修复，请尝试
