### ISSUE TITLE
txfeed panic

### ISSUE THREAD

**Issue by gguoss** [Bytom/bytom#146]
![txfeed](https://user-images.githubusercontent.com/9285062/33364090-df9dbaa0-d51d-11e7-857d-24762a1ffe2c.png)

**Comment by yahtoo** [comment]
commit 95433fd683a67e88f8c9aad459f34516d9862f24
Author: Yahtoo Ma <yahtoo.ma@gmail.com>
Date:   Thu Nov 30 10:13:05 2017 +0800

    Fix txfeed panic when wallet disabled
