### ISSUE TITLE
BTM在3签2时广播报错，求解决方案

### ISSUE THREAD

**Issue by woyinzf** [Bytom/bytom#1480]
btm在进行3签2的时候广播报错：“Gas credit has been spent”
单签的时候没有报错，领导十分想用多签，安全。

因为decode的里的input数量相当多，所以无论单签还是多签都调用了：build-chain-transactions。
单签时候一个raw里大概有10个input，多签的时候一个raw里有7个左右的input。（但是在正确签名后，广播报错：“Gas credit has been spent”）

**Comment by Paladz** [comment]
你们手续费是给多少的？这个错误是指手续费少了

**Comment by woyinzf** [comment]
0.1 个btm

**Comment by woyinzf** [comment]
0.05个btm

**Comment by Paladz** [comment]
1.0.7已经已经解决了之前的一个多钱手续费计算误差bug，下载最新的试用
