### ISSUE TITLE
compile contract failed

### ISSUE THREAD

**Issue by zhengll0514** [Bytom/bytom#1502]
parse error: line 1, col 61: expected keyword of: compile contract failed

**Comment by zhengll0514** [comment]
{
  "contract": "contract LockWithPublicKey(publicKey: PublicKey) locks locked { clause unlockWithSig(sig: Signature) { verify checkTxSig(publicKey, sig) unlock locked }}",
  "args": [
    {
      "string": "58e3b6ecf8414f4960b82e6b64231ec54131900cfc1596cd861a850f671325ac"
    }
  ]
}

**Comment by oysheng** [comment]
新版合约格式已经改了，具体可以参考API接口：https://github.com/Bytom/bytom/wiki/API-Reference#compile
