### ISSUE TITLE
Failed to Compile bytom source code on windows platform

### ISSUE THREAD

**Issue by icodezjb** [Bytom/bytom#153]
#### Environment

- OS: windows

#### Problem Description
cd cmd/bytomd && go build -a 

error info:
 github.com\tendermint\tmlibs\common\os.go:56: undefined: syscall.Kill 

tmlibs\common\os.go  info:
53:  // Kill the running process by sending itself SIGTERM
54:  func Kill() error {
55:	  pid := os.Getpid()
56:	  return syscall.Kill(pid, syscall.SIGTERM)
57:  }

conclusion：
tmlibs has no the functional implementation which  used to killing a process on windows platform

**Comment by icodezjb** [comment]
modify unsafely just for test:

53: // Kill the running process by sending itself SIGTERM
54: func Kill() error {
55:   return nil
56:	//pid := os.Getpid()
57:	//return syscall.Kill(pid, syscall.SIGTERM)
58: }

**Comment by Blockmeta** [comment]
windows i386 or x64？

**Comment by icodezjb** [comment]
amd_64

**Comment by icodezjb** [comment]
done , see
https://github.com/Bytom/bytom/pull/174
