### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by cost82el** [Bytom/bytom#1542]
![unknown 1](https://user-images.githubusercontent.com/31382065/50547578-e7561a80-0c44-11e9-8ee0-bf27d4dd7e4a.png)
![unknown](https://user-images.githubusercontent.com/31382065/50547579-e7561a80-0c44-11e9-861b-9b4e1ff2f661.png)

**Comment by GregoryGHarding** [comment]
please explain the issue so others can understand what is happening.

**Comment by HAOYUatHZ** [comment]
r u using the correct key

**Comment by cost82el** [comment]
yes, i use correct key... i have 129 btm received from mining and i try to move to exchange... password is correct ... i can changed without no problem but i receive this error when submit transaction.

**Comment by GregoryGHarding** [comment]
have you tried sending a different amount? maybe the error text is wrong..

**Comment by cost82el** [comment]
yes... same error

**Comment by GregoryGHarding** [comment]
@HAOYUatHZ

**Comment by ZhitingLin** [comment]
From your account page, you could get the account xpub for the account papy.  that's the actual key for your account, you should try the password for the matched account key xpub.
