### ISSUE TITLE
关于sm2和ed25519

### ISSUE THREAD

**Issue by zhengll0514** [Bytom/bytom#1560]
请问为什么实现2套加解密代码，不抽象出一套加解密接口，像Action那样。

**Comment by knull-cn** [comment]
我看了一下源代码，好像没用到国密相关的功能，可能还在开发中，还没实现

**Comment by MartinBTM** [comment]
有个国密库，https://github.com/Bytom/bytom-gm

**Comment by zcc0721** [comment]
分成两个库是因为账户、交易体系都要统一使用同一个加密标准。sm2 和 ed25519 算法不同，在生成密钥的时候无法通用。
