### ISSUE TITLE
如何联系你们？

### ISSUE THREAD

**Issue by jiazhaoyang** [Bytom/bytom#160]
测试网自动链接（想测试的，联系官方送测试币）

**Comment by Blockmeta** [comment]
if you are chinese， pls contact us with 8btc.com bytom section

**Comment by zcc0721** [comment]
想了解更多比原链官方信息，请关注：
比原链官网：
http://bytom.io/
比原链官方博客：
https://bytom.io/blog
比原链官方论坛：
http://8btc.com/forum-143-1.html
比原链Twitter：
https://twitter.com/Bytom_Official
比原链Slack：
https://bytom-official.slack.com/messages
比原链Reddit：
https://www.reddit.com/r/BytomBlockchain/
比原链Facebook：
https://www.facebook.com/bytomofficial/

注：比原链微信群现已关闭所有的入群渠道，微信群将不再接受新的入群申请。

**Comment by honhosing** [comment]
@jiazhaoyang 欢迎加入Slack的开发者社区：https://join.slack.com/t/bytom-official/shared_invite/enQtMjQxNzY2MzI5OTc0LWY1MWMxZjlkYjViNjNiNjhkYzBlN2U5MGY0NGUwMGJhNjdkNzg3NjQwODY3OTdhMDhmMTNiNGJkY2EwZmJkODA

**Comment by zcc0721** [comment]
If you use wechat, you can join the group:
![](https://camo.githubusercontent.com/86782a99eeb65dd7324067ca70834c4cb1fdac4e/68747470733a2f2f696d616765732d63646e2e7368696d6f2e696d2f693451436e48506948487367305441332f576563686174494d47313036362e6a706567217468756d626e61696c)
