### ISSUE TITLE
Issue compiling bytomd on Ubuntu

### ISSUE THREAD

**Issue by 2tg67eHE4xWE** [Bytom/bytom#161]
#### Environment

- OS: Ubuntu 16.04.3 LTS

#### Problem Description

Fails to compile bytomd due to path errors. I have verified that the files are in the proper paths specified by the program. Furthermore the dependency 'tmlibs' is not automatically obtained and also is not set in the correct path structure based on commands given. It should just be stored in ~./github.com/tmlibs not ~./github.com/tendermint/tmlibs. 

Follow compilation instructions found on the main github page for ubuntu linux.

Additional information:

BASIC INFO

root@b4865a6472a4:~/.go/src/github.com/bytom# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

root@b4865a6472a4:~/.go/src/github.com/bytom# go version
go version go1.9.2 linux/amd64

root@b4865a6472a4:~/.go/src/github.com/bytom# go env GOROOT GOPATH
/usr/local/go
/root/go

Issue 1a:
root@b4865a6472a4:~/.go/src/github.com/bytom# make bytomd
Building bytomd to cmd/bytomd/bytomd
cmd/bytomd/main.go:8:2: cannot find package "github.com/bytom/cmd/bytomd/commands" in any of:
        /usr/local/go/src/github.com/bytom/cmd/bytomd/commands (from $GOROOT)
        /root/go/src/github.com/bytom/cmd/bytomd/commands (from $GOPATH)

root@b4865a6472a4:~/.go/src/github.com/bytom# ls $GOPATH/src/github.com/bytom/cmd/bytomd/commands/
init.go  root.go  run_node.go  version.go

Issue 1b:
This is wrong import in general, I believe it should just be github.com/tmlibs in the actual folder structure: 
cmd/bytomd/main.go:6:2: cannot find package "github.com/tendermint/tmlibs/cli" in any of:
        /usr/local/go/src/github.com/tendermint/tmlibs/cli (from $GOROOT)
        /root/go/src/github.com/tendermint/tmlibs/cli (from $GOPATH)

b4865a6472a4:~/.go/src/github.com/bytom# ls $GOPATH/src/github.com/tendermint/tmlibs/cli
flags  helper.go  setup.go  setup_test.go

As seen even after it's placed into the proper path it still says that it cannot be found

**Comment by 2tg67eHE4xWE** [comment]
Was able to compile after changing the import string in main.go, I can make a pull to do the change if requested.

**Comment by gguoss** [comment]
Can not reproduce.

**Comment by honhosing** [comment]
@2tg67eHE4xWE 
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address.

Bytom Core

**Comment by honhosing** [comment]
@2tg67eHE4xWE 
Dear developer 2tg67eHE4xWE：

你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
