### ISSUE TITLE
国内站点被封锁，寻求新的站点同步数据

### ISSUE THREAD

**Issue by MartinDong** [Bytom/bytom#1610]
昨天下面的站点都不返回最新高度了，请问有别的节点可以使用么？
45.79.213.28:46657,198.74.61.131:46657,212.111.41.245:46657,47.100.214.154:46657,47.100.109.199:46657,47.100.105.165:46657

**Comment by MartinDong** [comment]
![image](https://user-images.githubusercontent.com/7735699/53675223-6a403380-3ccf-11e9-9bd1-7c606d13b285.png)

**Comment by Paladz** [comment]
解决方案：
1. 下载最新的1.0.8版本
2. 删除Bytom目录下的  .bytom/data/core.db文件夹
3. 重启节点
