### ISSUE TITLE
How to Build Transaction and Sign Offline

### ISSUE THREAD

**Issue by Robwpy** [Bytom/bytom#1630]
I read the source code and found that the construction transaction is done by api. So how do I construct a transaction offline?

**Comment by Robwpy** [comment]
I create a new BTMsolo address offline,and set it as miner-address

So, How could I get list-unspent-outputs by api?

no account_id,no account_alias, always rpc 504 timeout

any help?

**Comment by Robwpy** [comment]
我离线创建一个新的BTMsolo地址，并将其设置为miner-address

那么，我怎么能通过api得到list-unspent-outputs？

没有account_id，没有account_alias，总是rpc 504超时

任何帮助？

**Comment by vae520283995** [comment]
你是用什么语言写的

**Comment by Robwpy** [comment]
https://github.com/Bytom/bytom/blob/56443ac4cd0f7da9e8ca1cf7117a809bc0f6cf87/blockchain/txbuilder/txbuilder_test.go#L295

我看到这里测试了一笔通过utxo构造交易的，里面的recvProg应该是什么值？公钥还是其他的？

**Comment by vae520283995** [comment]
这个相当于地址,就是你转到哪个地址上面去

**Comment by Robwpy** [comment]
> 这个相当于地址,就是你转到哪个地址上面去

那它是什么来的？

**Comment by vae520283995** [comment]
program, err := vmutil.P2WPKHProgram([]byte(pubHash))
就是通过公钥hash算出这个东西来的,具体要看代码,我还没研究到这里

**Comment by Robwpy** [comment]
> ```
> program, err := vmutil.P2WPKHProgram([]byte(pubHash))
> ```
> 就是通过公钥hash算出这个东西来的,具体要看代码,我还没研究到这里

好的，谢谢你提供的帮助

**Comment by Robwpy** [comment]
I create a new BTMsolo address offline and set it as miner-address

So, How could I get list-unspent-outputs by api?

no account_id, no account_alias, always rpc 504 timeout

any help?

我离线创建一个新的BTMsolo地址，并将其设置为miner-address

那么，我怎么能通过api得到list-unspent-outputs？

没有account_id，没有account_alias，总是rpc 504超时
