### ISSUE TITLE
How do I generate addresses through mnemonics by bip44 please

### ISSUE THREAD

**Issue by vae520283995** [Bytom/bytom#1631]
How do I generate addresses through mnemonics by bip44
now I generate xpub 28e410368cb69b3a668dd9285dc1779102b003bed7f8286c972f672fe3358e1bef1f31696b44c812000e4a109f1ee6caea093f6add27328a038883fff67efd8b
and address bm1qy44d7u22xazxwf7ltygpwafk68d9e3nkz4jd74
But there's no way to verify him.
please

**Comment by zcc0721** [comment]
I think your address is incorrect. I cann't generate address bm1qy44d7u22xazxwf7ltygpwafk68d9e3nkz4jd74 from 28e410368cb69b3a668dd9285dc1779102b003bed7f8286c972f672fe3358e1bef1f31696b44c812000e4a109f1ee6caea093f6add27328a038883fff67efd8b.

**Comment by zcc0721** [comment]
![image](https://user-images.githubusercontent.com/17916496/54184377-8159ff00-44e1-11e9-920c-6759b0fb4764.png)

**Comment by vae520283995** [comment]
> You can use bytom kit to verify the result.
> 
> https://kit.blockmeta.com/#

@zcc0721 thank you very much ,can you give me you qq number?

**Comment by zcc0721** [comment]
email：zcc0721@foxmail.com

**Comment by vae520283995** [comment]
> email：[zcc0721@foxmail.com](mailto:zcc0721@foxmail.com)

ok
