### ISSUE TITLE
get transaction failed

### ISSUE THREAD

**Issue by Robwpy** [Bytom/bytom#1634]
我发送一笔交易后，发现我离线生成的地址的outputID查询时没有任何返回，但是找零的outputID却可以查询。

1、那我怎么获取这个离线地址的utxo，或者怎么获取source_id?

2、我如何将不是local address的地址变为local，我没看到API有任何相关的操作

**Comment by Robwpy** [comment]
1、我使用account给离线的生成的地址转账，成功后找到了对应的outputID，但是我用list-unspent-outputs接口却查不到对应output，使用这个outputID构造交易提示费用不足BTM770。

是因为我的地址不属于节点钱包就不记录我的output吗？就算不记录，那我也是一个合法的output为什么不能构造交易

2、我通过create-account-receiver接口创建的地址，怎么导出私钥？？？

bitcoin起码可以导出keystore，那bytom呢？

**Comment by Robwpy** [comment]
另外，有没有开发人员，问个问题简直了

**Comment by zcc0721** [comment]
source id 就是 mux id，可以使用 blockmeta 的 api 接口查询到。

**Comment by JFJun** [comment]
我也遇到相同的问题，但不知到是什么原因，调用get-transaction总是返回不了数据。

**Comment by zcc0721** [comment]
> 我也遇到相同的问题，但不知到是什么原因，调用get-transaction总是返回不了数据。

请把错误信息发上来。

**Comment by JFJun** [comment]
{"status":"fail","code":"BTM000","msg":"Bytom API Error","error_detail":"No transaction(tx_id=f3af7c50b127e2e92f30aa307ea1c899853a404c07e9ffd448c3c15db98f7b8b) from txpool"}

这是我返回的错误信息！！！

**Comment by JFJun** [comment]
{"status":"fail","code":"BTM000","msg":"Bytom API Error","error_detail":"No transaction(tx_id=e15b98532cb1adf56ec843818970f2d9308e44e05bd9d6086e1857f1e0ce5d27) from txpool"}

上面的日志txid是错的，这个日志的交易id链上可以查到

**Comment by JFJun** [comment]
我目前不太理解这个get-transaction是只能查找本地节点的交易记录还是整个区块链中的所有交易记录，如果只能查找本地节点所发生的交易记录的话，因为我的节点是刚搭建的，所以没有发生任何交易记录。那如果是这样的话，那么我怎么获取整个区块链中所有的交易记录了。我使用list-transactions查找交易返回status=“success”,但是data=“[]"。

**Comment by zcc0721** [comment]
list-transactions 肯定返回自己钱包的交易，返回全网交易没有意义。

**Comment by JFJun** [comment]
那如果我需要自己写一个接口去查询我的txid是否已经在链上了，而不是手动去打开区块游览器查询，这个怎么处理了

**Comment by zcc0721** [comment]
首先需要启动bytomd，使用 [get-transaction api](https://github.com/Bytom/bytom/wiki/API-Reference#get-transaction)

**Comment by JFJun** [comment]
> 
> 
> 首先需要启动bytomd，使用 [get-transaction api](https://github.com/Bytom/bytom/wiki/API-Reference#get-transaction)

我目前就是使用这个方法，我现在的需要是根据任何一个链上可查的txid能够获取链上的任何一笔的交易数据，而不只是我的钱包里面发生的交易数据。

**Comment by zcc0721** [comment]
你在启动 bytom 节点的时候需要添加两个字段，例如：

```
bytomd node --home $HOME/bytom/testnet --wallet.rescan --wallet.txindex
```

这样就可以 get-transaction 获取全网交易

**Comment by JFJun** [comment]
> 
> 
> 你在启动 bytom 节点的时候需要添加两个字段，例如：
> 
> ```
> bytomd node --home $HOME/bytom/testnet --wallet.rescan --wallet.txindex
> ```
> 
> 这样就可以 get-transaction 获取全网交易

好的，我试一下，太感谢了
