### ISSUE TITLE
Bytom transection error "Available UTXO's of account have been reserved"

### ISSUE THREAD

**Issue by Deemondude** [Bytom/bytom#1637]
![image](https://user-images.githubusercontent.com/48659176/54498414-67ebf500-48dd-11e9-88f1-db30ab63a6e3.png)

**Comment by Deemondude** [comment]
I keep getting this error when I try to send my funds to an external wallet. Any help will be greatly appreciated. Thank you :)

**Comment by zcc0721** [comment]
Your UTXO has been spend twice.

**Comment by zcc0721** [comment]
Please wait, and this UTXO will be unlock if your last tx has been affirmed.

**Comment by HAOYUatHZ** [comment]
or maybe just wait for 24 hrs
