### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RockerFlower** [Bytom/bytom#167]
#### Environment

- OS: macOS 10.13.1

#### Problem Description

I downloaded [Bytom 0.2.0 for Mac](https://github.com/Bytom/bytom/releases/download/v0.2.0/bytom-0.2.0.mac.zip), extracted to `Workspace/Bytom/cmd`, and run `./bytomd init --chain_id testnet`, `./bytomd node --wallet.enable`.

<img width="682" alt="screen shot 2017-12-04 at 4 55 48 pm" src="https://user-images.githubusercontent.com/5019152/33544037-29fc094a-d914-11e7-9415-9bee401445a5.png">

Here is the step with `bytomcli`:

<img width="682" alt="screen shot 2017-12-04 at 4 59 56 pm" src="https://user-images.githubusercontent.com/5019152/33544219-e899dbde-d914-11e7-9148-7c4cca616e97.png">
<img width="682" alt="screen shot 2017-12-04 at 5 00 33 pm" src="https://user-images.githubusercontent.com/5019152/33544235-fa4d4ec4-d914-11e7-8693-2b3874c2c472.png">

Error occurs when I run `sub-create-issue-tx`:

> To build transaction:
> -----------tpl:{<nil> [] false false}
> ----------tpl transaction:<nil>
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x44ee60e]

> goroutine 1 [running]:
> main.submitCreateIssueTransaction(0xc420010310, 0xc420010090, 0x5, 0x5)
	/Users/zcc/GoWorkspace/src/github.com/bytom/cmd/bytomcli/main.go:555 +0x57e
> main.main()
	/Users/zcc/GoWorkspace/src/github.com/bytom/cmd/bytomcli/main.go:129 +0x271

**Comment by icodezjb** [comment]
update bytom v0.3.0
