### ISSUE TITLE
新版本更新问题

### ISSUE THREAD

**Issue by KuoRave** [Bytom/bytom#1676]
昨天为止我用的还是1.0.7版本的,区块没法同步到最新区块,所以备份了数据之后新开了目录运行新版本,但是如何把备份的数据迁移过来?用相同的key创建的地址余额不共享的,实在是好麻烦

**Comment by HAOYUatHZ** [comment]
助记词？可以共享

**Comment by HAOYUatHZ** [comment]
或者你 导出  钱包备份，再导入，然后  rescan
