### ISSUE TITLE
win10系统下乱码

### ISSUE THREAD

**Issue by coodream** [Bytom/bytom#168]
#### Environment

- OS: win10

#### Problem Description

![image](https://user-images.githubusercontent.com/1920448/33546310-a7f89c30-d91b-11e7-90a5-6d2b94df53c5.png)

**Comment by coodream** [comment]
![image](https://user-images.githubusercontent.com/1920448/33546693-a544521c-d91c-11e7-8fd8-11ed6952a9bd.png)

**Comment by gguoss** [comment]
是windows cmd 里面编码问题， 可以用power shell 运行是没问题的

**Comment by coodream** [comment]
ok
