### ISSUE TITLE
Getting PublicKey and Program of an Address through the API (or programmatically)

### ISSUE THREAD

**Issue by Agouri** [Bytom/bytom#1690]
Good morning,

For a Smart Contract that has `Program` and `PublicKey` parameters that are **associated**, for example `saver_program` and `saver_key`, is there a way to get the associated Program+PublicKey together, programmatically?

Right now I have to go to the Web Interface and find the address I want to use, find the Bech32 address, get the Program through the interface, then decode the Bech32 address, call the API's `list-pubkeys` and try to find the relevant PublicKey form of the address.

Any way for this to be faster? :)

EDIT: **If that's impossible**, could you write down the process of obtaining Program from Public Key, so I can do it myself, outside of the API?

**Comment by oysheng** [comment]
you can get the program and publickey by changing source code, please refer to: https://github.com/Bytom/bytom/blob/master/account/accounts.go#L652

**Comment by zcc0721** [comment]
Hi, did you solve it?

**Comment by Agouri** [comment]
Not completely, but we can close this issue, I'll make a new issue when If
I run into more problems. Thank you.
