### ISSUE TITLE
list-keys 和 create-control-program 命令 没有帮助参数  就一直报错 说参数不正确

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#170]
#### Environment

- OS: all

#### Problem Description
list-keys 和 create-control-program 命令 没有帮助参数  就一直报错 说参数不正确

list-keys 就一直说 参数不合法
[error: listKeys args not vaild]

create-control-program
说是不让跟参数 但是没参数又报错
[error:createControlProgram not use args]

responses:[map[code:CH003 message:Invalid request body detail:unknown control pr
ogram type "" temporary:false]]

**Comment by liuchengxu** [comment]
Please update to the latest version, it should be solved.
