### ISSUE TITLE
挖矿的问题 不知道是不是bug!

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#171]
#### Environment

- OS: win7

#### Problem Description
挖矿官方给的说法是 必须要完成同步数据！目前大概8000区块！我测试了一下在同步的过程中直接关闭bytomd.exe 下次再打开 他就不继续同步了……直接开始挖矿了 ！
这就有两个问题
第一个是否存在其他隐患的问题
第二个 友好问题 目前同步数据量不大 删除文件从新同步没什么 当以后同步数据大的话 不能断点同步 必须一次性同步完成 貌似就太不友好了 

关于这个问题 我一会测试完其他的 再去验证一次 同步一次很累 暂时不想删除

**Comment by gguoss** [comment]
挖矿模块有更新
