### ISSUE TITLE
多账户转账的问题-是操作不当还是bug?

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#172]
#### Environment

- OS: win7

#### Problem Description
建立账户1，建立账户2，建立账户3，挖矿会自动进入账户1，账户1可以往2.3中转账，而2.3却无法转账！
转账命令 密钥 账户id 资产id 数量 地址都对 就是无法转
报错信息：
To build transaction:
tpl:[{<nil> [] false false}]
sign-transaction error. err:missing raw tx

**Comment by icodezjb** [comment]
有没有更bytomd报错信息

**Comment by icodezjb** [comment]
已更新到bytom v0.3.0
