### ISSUE TITLE
账户在转出一笔钱后短暂的时间内无法持续转出第二笔？

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#173]
#### Environment

- OS: win7

#### Problem Description
转出第一笔之后 马上转第二笔 就会报错？是不是必须区块确认后才能转第二笔？

**Comment by zcc0721** [comment]
错误提示什么？

**Comment by btmtest** [comment]
错误提示！

To build transaction:

tpl:[{<nil> [] false false}]

sign-transaction error. err:missing raw tx

这个错误提示就跟填错了是一样 实际并没有填错

我详细给你描述一下问题 肯定是有点问题的

我的操作是这样的

我有三个账户，按顺序第一个账户是最早建立的，依次类推，第一个账户就是挖矿自动进入的账户，第一个账户转出没有任何问题，假设现在从第一个账户转给第二个账户1000000000 ，等待出块后确认成功，list-balances也查到了第二个账户有转过来的余额了

然而第二个账户往第三个账户转 或者第一个账户转就会出现问题，第一个问题是，转交大额就转不出去一直报错，在没有修改任何其他信息，我逐步减少转账金额后，远小于余额，就可以转账成功了，然而这根本不是手续费问题，因为扣的手续费远小于我的余额，例如我可能吧转出10000000改成1000后才可以成功第一笔，

而第二个问题就出现了，在以后转账就没有说必须很小额，足够手续费，足够余额都可以了，但是就会出现，必须到账后才能转下一笔！

1.在所有信息我确保填对的情况下，而且余额充足，而且保证余额远大于手续费 

具体详细 我们可以微信或者 slack沟通都可以 微信我在内测群里  名称 “：” 就最活跃那个 今天在群里问过这个问题

slack 号是 luxiyi

**Comment by icodezjb** [comment]
测试网的手续费是20000000btm

**Comment by icodezjb** [comment]
第三次转账失败是因为没有足够的utxo构建交易，所以会失败

**Comment by btmtest** [comment]
我对go不熟悉 没有足够能力代码审计 但是通过客户端 转账测试 比价 眼花缭乱 但是 我说的那个 明明 大于转账+手续费的余额 确转不出去必须改成很小很小的数值才可以 确实存在 复现了两次了 我有空 再详细试一下啊 再给你们更准确的说法

**Comment by icodezjb** [comment]
如果复现问题，bytomd应该也会报错，bytomd的报错信息有助于排查

**Comment by btmtest** [comment]
To build transaction:

tpl:[{ [] false false}]

sign-transaction error. err:missing raw tx 
报错就是这个啊 ……比如 ID填错了 什么 都是这个报错

**Comment by icodezjb** [comment]
是的，bytomd报错信息只有btm开发人员能看到

**Comment by btmtest** [comment]
嗯 我研究下go 以前玩c++ 应该go好上手

**Comment by zcc0721** [comment]
可以开启debug模式

**Comment by icodezjb** [comment]
已更新到bytom v0.3.0
