### ISSUE TITLE
BTM测试币领取问题

### ISSUE THREAD

**Issue by A-HUAN** [Bytom/bytom#1742]
前往http://btmdemo.ppkpub.org/joy/faucet.php领取了测试币 说2-3分钟左右会进行出块确认 但是钱包账户一直没有

**Comment by zcc0721** [comment]
你好，领取比原链测试币建议还是前往比原链官方水龙头： https://blockmeta.com/tools/faucet ，只需输入自己的测试地址就能领取 10 BTM测试币。
