### ISSUE TITLE
你好，领取比原链测试币建议还是前往比原链官方水龙头： https://blockmeta.com/tools/faucet ，只需输入自己的测试地址就能领取 10 BTM测试币。

### ISSUE THREAD

**Issue by A-HUAN** [Bytom/bytom#1744]
你好，领取比原链测试币建议还是前往比原链官方水龙头： https://blockmeta.com/tools/faucet ，只需输入自己的测试地址就能领取 10 BTM测试币。

_Originally posted by @zcc0721 in https://github.com/Bytom/bytom/issues/1742#issuecomment-487399434_

您好  在您提供的地址输入了钱包测试网地址 也反馈了交易ID 但是钱包里依然没有 区块已全部同步

**Comment by zcc0721** [comment]
刚才我试了一下，可以正常使用，你要确保生成了正确的 tm 开头的测试地址，如 tm1qq5nzpwr2d40qwvga2qval73cvnxv3f4aczd8h6， 填入地址就行了，然后到比原链测试网浏览器查看交易是否存在，http://52.83.95.44:8082/ 。还有，你的钱包版本最好更新到最新版本，最新版本是 1.0.9。

**Comment by zcc0721** [comment]
![image](https://user-images.githubusercontent.com/17916496/56894426-686cd380-6ab8-11e9-8651-cecc7b200b70.png)

**Comment by zcc0721** [comment]
我刚才试验多次，均能正常获取。
