### ISSUE TITLE
区块同步太慢

### ISSUE THREAD

**Issue by A-HUAN** [Bytom/bytom#1746]
您好 钱包testnet区块同步太慢是也可以去https://bytom.io/wallet/下载区块数据文件替换吗？还是仅针对主网的 之前替换过一次 打开钱包左下角的确显示区块同步完成 但余额依然无法正常显示（钱包地址已经前往水龙头领取过测试BTM币）所以测试网只能自己慢慢等龟速同步吗

**Comment by A-HUAN** [comment]
而且为什么左下角区块同步最大数一会是40000多 一会是20000多？

**Comment by zcc0721** [comment]
你是开发者吗？是否运行go源代码版本？还是直接运行编译好的版本？

**Comment by zcc0721** [comment]
同步区块显示变化其中一个可能的原因是网络不稳定，节点同步区块信息有变化。

**Comment by HAOYUatHZ** [comment]
db on https://bytom.io/wallet/ is only for mainnet

**Comment by HAOYUatHZ** [comment]
when there'z not peer connect, the best height will be the best height on your local chain, which is 2k+ in ur case

when u r connected to another peer, the best height will be the best height among the network formed, which is 4k+ in ur case
