### ISSUE TITLE
能否同步更新Dockerfile

### ISSUE THREAD

**Issue by Z-Beatles** [Bytom/bytom#175]
#### Environment

- OS: Win10

#### Problem Description

$ docker build -t bytom .                                                                                                                                    
Sending build context to Docker daemon    138MB                                                                                                              
Step 1/10 : FROM golang:1.9-alpine as builder                                                                                                                
1.9-alpine: Pulling from library/golang                                                                                                                      
1160f4abea84: Pull complete                                                                                                                                  
4d49542c61a4: Pull complete                                                                                                                                  
3ee103c86f60: Pull complete                                                                                                                                  
9a56d2eb1eed: Pull complete                                                                                                                                  
67e0ebed9a3b: Pull complete                                                                                                                                  
194910951a14: Pull complete                                                                                                                                  
Digest: sha256:354be5853ea170e6f8bf3e258154e10ba0ed03f909d8be8625faf61592c515c8                                                                              
Status: Downloaded newer image for golang:1.9-alpine                                                                                                         
 ---> f421e93ece9c                                                                                                                                           
Step 2/10 : RUN apk add --no-cache make git                                                                                                                  
 ---> Running in aaa8885f3dc1                                                                                                                                
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz                                                                                  
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz                                                                             
(1/6) Installing libssh2 (1.8.0-r1)                                                                                                                          
(2/6) Installing libcurl (7.56.1-r0)                                                                                                                         
(3/6) Installing expat (2.2.0-r1)                                                                                                                            
(4/6) Installing pcre (8.41-r0)                                                                                                                              
(5/6) Installing git (2.13.5-r0)                                                                                                                             
(6/6) Installing make (4.2.1-r0)                                                                                                                             
Executing busybox-1.26.2-r9.trigger                                                                                                                          
OK: 25 MiB in 18 packages                                                                                                                                    
 ---> 04caa95453c9                                                                                                                                           
Removing intermediate container aaa8885f3dc1                                                                                                                 
Step 3/10 : ADD . /go/src/github.com/bytom                                                                                                                   
 ---> 645376f57e41                                                                                                                                           
Step 4/10 : RUN cd /go/src/github.com/bytom && make install && cd ./cmd/bytomd && go build && cd ../bytomcli && go build                                     
 ---> Running in 7219d4bb6059                                                                                                                                
**make: *** No rule to make target 'install'.  Stop.**                                                                                                           
The command '/bin/sh -c cd /go/src/github.com/bytom && make install && cd ./cmd/bytomd && go build && cd ../bytomcli && go build' returned a non-zero code: 2

**Comment by gguoss** [comment]
https://github.com/Bytom/bytom/pull/198
