### ISSUE TITLE
充币地址怎么不在我帐户了

### ISSUE THREAD

**Issue by dengdawei588** [Bytom/bytom#1750]
充币地址怎么不在我帐户了

**Comment by zcc0721** [comment]
请详细描述你的问题

**Comment by dengdawei588** [comment]
我的电脑重装系统以后，资金地址就不在我账户了，怎么才能找回我的BTM呢？
![BTM充值](https://user-images.githubusercontent.com/41830671/57995480-e3903b00-7af4-11e9-8a7b-f20c581f3fd6.PNG)

**Comment by zcc0721** [comment]
钱包是否已经备份？如果没有备份，那么就是找不到了，如果有备份是可以找到的。

**Comment by dengdawei588** [comment]
通过助记词能恢复吗

**Comment by zcc0721** [comment]
是的，如果备份了钱包的话，也可以导入钱包文件

**Comment by dengdawei588** [comment]
助记词是什么？我好像没有设置过呢！其它我都有记录下来，除了没备份

**Comment by zcc0721** [comment]
助记词指的是创建钱包时生成的 12 个单词，钱包没备份？你现在保存的到底是什么？有没有通过钱包点击备份过？
