### ISSUE TITLE
备份的keystore文件恢复报错

### ISSUE THREAD

**Issue by davidlaw99** [Bytom/bytom#1752]
备份的keystore文件恢复报错
Could not parse JASON response
怎么样解决？
![btm报错](https://user-images.githubusercontent.com/26465493/58882105-20bc1600-870e-11e9-9ff9-f82d30860de4.JPG)

**Comment by zcc0721** [comment]
你之前有没有在钱包选项中点击备份钱包？如果只是在数据目录里复制 keystore 文件是无法正确恢复的。

**Comment by zcc0721** [comment]
从你的文件名来看，你备份的只是 keystore，采用的是复制粘贴的方式备份的，这种备份方法是错误的。正确的方法应该是在钱包设置里选择备份，之后就产生一个新的备份文件，这样才能正确导入钱包。

只有 keystore 的话想要恢复你的钱包步骤比较繁琐：

1. 下载最新版本 1.0.9 并安装但是不启动
2. 将你的 keystore 复制到比原的数据目录下，就是原来 keystore 从哪里得到的还原样复制到该目录下，不同的系统数据目录不同
3. 启动钱包并等待区块同步完成
4. 在钱包里你或许能看到你的 key 列表，但是在账户下你看不到任何账户，这个时候需要新建账户，新建账户的数量取决于你之前新建了几个账户
5. 在每个账号下点击右上角的新建地址选项，多点击几次，尽可能多的新建地址，如果你确信自己之前用的地址很少的话可以少新建几个
6. 之后在余额页面的右上角点击重新扫描开始扫描自己的交易
7. 扫描完成后可以在余额中查看自己的余额
