### ISSUE TITLE
新版本下载不下来，给个网盘地址吧

### ISSUE THREAD

**Issue by sundayxcn** [Bytom/bytom#1755]
我1.05版本同步不了节点，币在里面拿不出来。用keystore 在手机的Bycoin 导入失败。。。。。。现在要下个1.09 死活拉不下来。。。。。。。。。。晕死。。。

**Comment by zcc0721** [comment]
你可以尝试到 https://bytom.io/wallet/ 下载

**Comment by sundayxcn** [comment]
新的问题出来了。。一直同步不了是什么问题？连接数一会有一会没有。最后都消失

**Comment by HAOYUatHZ** [comment]
mainnet?

**Comment by HAOYUatHZ** [comment]
testnet 节点比较少，连接可能不太稳定

**Comment by sundayxcn** [comment]
是mainnet 的 一直卡在187843.

118.24.32.51:46657 | 259090 | 880ms | 1.5s | 11 KB 断开
45.40.244.129:46657	259090	520ms	1.58s	11 KB	断开

这是其中两个节点。出现了。又消失。这样来回显示几次后。就什么都没有了。

**Comment by HAOYUatHZ** [comment]
您好，我明白您的问题了，您的问题在于钱包软件更新了，而没有清除数据重新同步。
因为这个更新和之前的不兼容，所以才需要清除数据重新同步。这个我们也有说明。

解决办法：
需要 删除   <数据目录>/data/core.db/
然后 运行钱包重新同步

**Comment by sundayxcn** [comment]
@HAOYUatHZ   只删core 钱包数据有问题。。全部删掉后可以了。。然后现在又有新的问题了。。
我发现PC钱包相当相当难用！！！
我现在一个很旧的账号 里面有2987个btm 。。。我现在要转到我手机创建的钱包。。。。使用简单交易尝试转账10个没有问题。。转账2980个 不是出现 utxo已经被用来构建交易，导致临时锁定，不可花费 就是什么账户上限21个。什么鬼。。然后账户下面找零账户一直在增加。。。这是什么鬼啊。。。。真的是。。。。要被搞疯掉了

**Comment by HAOYUatHZ** [comment]
这是因为 为了防止攻击虚拟机，设置了 gas 上限
导致 utxo 不能超过21个，但是如果你花超了就会临时锁定1天

简单来说
你需要小笔小笔的转
或者联系 @DeKaiju   将utxo合并然后进行大笔转账
