### ISSUE TITLE
忘记密码怎样用助记词恢复钱包？

### ISSUE THREAD

**Issue by ak84998** [Bytom/bytom#1757]
原钱包1.08版本忘记了转账密码。但有助记词，在另外一台电脑安装1.08钱包软件后用助记词恢复，但发现没有账户原来的信息（没有交易记录，没有账户记录，余额显示空白），怎么弄？

**Comment by zcc0721** [comment]
点击余额菜单右上角的“重新扫描”即可。

![image](https://user-images.githubusercontent.com/17916496/59670001-bfa44000-91ed-11e9-89dd-bf73c3e971e5.png)
