### ISSUE TITLE
超级小的bug或者说是笔误！望修改

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#177]
#### Environment

- OS: all

#### Problem Description
bytomd.exe init --chain_id 重复的时候会报错说 配置文件已经存在 然而 你们报警信息的单词打错了

[36mINFO[0m[2017-12-06T09:18:56+08:00] Already 【exits】 config file.
应该是exists! 少了个字母 少了个字母 这个 我不说 也许没人注意之前永远不会改！但是正式后会影响形象！

**Comment by gguoss** [comment]
nice, thanks.

**Comment by gguoss** [comment]
e88b446128557ef67bdea75418ab0f591c9eedba
