### ISSUE TITLE
为什么seed生成私钥的结果和bytom kit不一样呢

### ISSUE THREAD

**Issue by chenzhijun45** [Bytom/bytom#1773]

**Comment by chenzhijun45** [comment]
public static byte[] hmacSha512(byte[] data, byte[] key) throws NoSuchAlgorithmException, InvalidKeyException {
        SecretKeySpec signingKey = new SecretKeySpec(key, "HmacSHA512");
        Mac mac = Mac.getInstance("HmacSHA512");
        mac.init(signingKey);
        return mac.doFinal(data);
    }

通过以上方法(Java)，第一个参数是seed，第二个参数是new byte[]{'R', 'o', 'o', 't'}
生成的结果和这上面(https://blockmeta.com/tools/key)不一样
请问是哪里出了什么问题吗？

**Comment by zcc0721** [comment]
bytom kit 生成的 seed 是随机的，生成结果必然不一样。
