### ISSUE TITLE
初始化测试网络配置文件无效

### ISSUE THREAD

**Issue by semliu** [Bytom/bytom#178]
C:\Users\Administrator>cd btm

C:\Users\Administrator\btm>bytomd init --chain_id testnet
[36mINFO[0m[2017-12-06T13:59:14+08:00] Initialized bytom
       [36mgenesis[0m=".bytomd\\genesis.json"

C:\Users\Administrator\btm>

**Comment by zcc0721** [comment]
Please read the [wiki](https://github.com/Bytom/bytom/wiki/Common-Commands-of-Bytom-(bytom%E7%9A%84%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C))
It‘s ok.

**Comment by honhosing** [comment]
@semliu 
Dear developer semliu：

你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
