### ISSUE TITLE
按照教程执行到docker build -t bytom . 报错

### ISSUE THREAD

**Issue by FoxCao** [Bytom/bytom#1808]
报错信息如下：
Build an image from a Dockerfile
localhost:~ apple$ docker build -t bytom .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/apple/Dockerfile: no such file or directory
localhost:~ apple$ 

这是我首次拉取bytom项目到本地按照流程执行的时候到这里报错

**Comment by HAOYUatHZ** [comment]
请进入 bytom文件夹构建镜像
