### ISSUE TITLE
我应该如何学习bytom chain

### ISSUE THREAD

**Issue by FoxCao** [Bytom/bytom#1809]
熟悉GO语言，对区块链还不是很熟悉，正在学习bytom是如何使用go来实现，我应该如何入手，希望前辈指导一下

**Comment by MartinBTM** [comment]
我们有wiki和开发者文档

**Comment by MartinBTM** [comment]
可以加个好友聊：keduo7151，备注一下

**Comment by FoxCao** [comment]
谢谢，已经发送加好友请求，我是GitHub上的foxcao,请教如何学习比原币开发



发自我的&nbsp;iPad


------------------ 原始邮件 ------------------
发件人: MartinBTM <notifications@github.com&gt;
发送时间: 2019年11月19日 16:01
收件人: Bytom/bytom <bytom@noreply.github.com&gt;
抄送: FoxCao <371147085@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Bytom/bytom] 我应该如何学习bytom chain (#1809)




我们有wiki和开发者文档
