### ISSUE TITLE
节点运行后，为什么一直重复出现这个

### ISSUE THREAD

**Issue by semliu** [Bytom/bytom#181]
[36mINFO[0m[2017-12-04T15:29:34+08:00] blockKeeper processed block                   [36mhash[0m=7bef17bb9624bf1013385e7c471f21c7dfb84a556276a4a5dfa0b23
8a4070000 [36mheight[0m=383 [36misOrphan[0m=false
[36mINFO[0m[2017-12-04T15:29:35+08:00] Receive request                               [36mmsg[0m="BlockResponseMessage{Size: 502}" [36mpeerID[0m=923DDF
78558A66D1795DD5DC095D3148AE12159029E890FB8CB1EE7CE519162C
[36mINFO[0m[2017-12-04T15:29:35+08:00] Block saved on disk                           [36mhash[0m=4383221a2b22d75950607ede17a09fc087cf6cf6c634c63495837b8
c65010000 [36mheight[0m=384
[36mINFO[0m[2017-12-04T15:29:35+08:00] blockKeeper processed block                   [36mhash[0m=4383221a2b22d75950607ede17a09fc087cf6cf6c634c63495837b8
c65010000 [36mheight[0m=384 [36misOrphan[0m=false
[36mINFO[0m[2017-12-04T15:29:35+08:00] Receive request                               [36mmsg[0m="BlockResponseMessage{Size: 502}" [36mpeerID[0m=566D4D
661F79AF09CC7F5644EB0EB7C02380AE7A64553DDF9681FC6C44129C31
[36mINFO[0m[2017-12-04T15:29:35+08:00] Skip process due to block already been handled  [36mhash[0m=4383221a2b22d75950607ede17a09fc087cf6cf6c634c63495837
b8c65010000
[36mINFO[0m[2017-12-04T15:29:35+08:00] blockKeeper processed block                   [36mhash[0m=4383221a2b22d75950607ede17a09fc087cf6cf6c634c63495837b8
c65010000 [36mheight[0m=384 [36misOrphan[0m=false
[36mINFO[0m[2017-12-04T15:29:35+08:00] Receive request                               [36mmsg[0m="BlockResponseMessage{Size: 502}" [36mpeerID[0m=923DDF
78558A66D1795DD5DC095D3148AE12159029E890FB8CB1EE7CE519162C
[36mINFO[0m[2017-12-04T15:29:35+08:00] Block saved on disk                           [36mhash[0m=a46ecf22e46997485fbe283b0cd19af03903c4bd14cc938c86616c6
224070000 [36mheight[0m=385
[36mINFO[0m[2017-12-04T15:29:36+08:00] blockKeeper processed block                   [36mhash[0m=a46ecf22e46997485fbe283b0cd19af03903c4bd14cc938c86616c6
224070000 [36mheight[0m=385 [36misOrphan[0m=false
[36mINFO[0m[2017-12-04T15:29:36+08:00] Receive request                               [36mmsg[0m="BlockResponseMessage{Size: 502}" [36mpeerID[0m=566D4D
661F79AF09CC7F5644EB0EB7C02380AE7A64553DDF9681FC6C44129C31
[36mINFO[0m[2017-12-04T15:29:36+08:00] Skip process due to block already been handled  [36mhash[0m=a46ecf22e46997485fbe283b0cd19af03903c4bd14cc938c86616
c6224070000

**Comment by honhosing** [comment]
你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

比原链团队
Bytom Core
