### ISSUE TITLE
如何用java离线创建一个BTM的地址

### ISSUE THREAD

**Issue by shenyaqi9527** [Bytom/bytom#1822]
如何用java离线创建一个BTM的地址

**Comment by shenao78** [comment]
原理都是一样的
1.  根据BIP44派生路径对Root Pubkey进行派生
2. 使用Ripemd160对派生派生计算公钥的hash
3. 使用bech32生成地址

java密码学库可以用这个
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.56</version>
        </dependency>
