### ISSUE TITLE
使用solonet创建单节点网络无法交易

### ISSUE THREAD

**Issue by awangbrace** [Bytom/bytom#1823]
您好，我最近在学习bytom,尝试建立单节点网络，之后尝试进行交易。但是发现无法进行交易，提示未成熟。比较疑惑，这个交易是需要其他节点确认之后才可能吗？
./bytomd init --chain_id solonet
./bytomd node
通过http://127.0.0.1:9888/dashboard使能挖矿。
在交易中可以看到挖矿的交易，但是都是immature，尝试创建资产时，都是失败的。

**Comment by Paladz** [comment]
这个原因点是因为solonet需要挖矿才可以出块，但是初始难度过大的问题。这个的话我们近期会修改solonet的初始难度

**Comment by DeKaiju** [comment]
100个块之后coinbase交易成熟才能使用coinbase交易的UTXO
具体代码在$GOPATH/src/github.com/bytom/bytom/consensus/general.go 中的CoinbasePendingBlockNumber
如果想快点使用coinbase交易的UTXO，可以修改CoinbasePendingBlockNumber的值，然后重新编译bytomd
