### ISSUE TITLE
一直出现 Send failed

### ISSUE THREAD

**Issue by semliu** [Bytom/bytom#184]
#### Environment

- OS: win7 64

#### Problem Description

一直出现 Send failed

[36mINFO[0m[2017-12-07T13:24:04+08:00] Receive request
       [36mmsg[0m="StatusResponseMessage{Height: 9097, Hash: 13943b6bf4b53af4b
74c33f7b4e5a1bcac153b1d8376b1c1f6830ead5e010000}" [36mpeerID[0m=81248CB850E924
56F08C7C713CE70E502B797585CCE84E5B51E09281777C2A86
[31mERRO[0m[2017-12-07T13:24:13+08:00] Send failed
       [31mchID[0m=64 [31mconn[0m="MConn{47.96.42.1:46656}" [31mmsg[0m="{S
tatusResponseMessage{Height: 9097, Hash: 1ffb623fb886c6f7a7da947df88bd6160cac88e
9bc7de9a1602b928993020000}}"
[36mINFO[0m[2017-12-07T13:24:14+08:00] Receive request
       [36mmsg[0m="StatusResponseMessage{Height: 9097, Hash: 13943b6bf4b53af4b
74c33f7b4e5a1bcac153b1d8376b1c1f6830ead5e010000}" [36mpeerID[0m=81248CB850E924
56F08C7C713CE70E502B797585CCE84E5B51E09281777C2A86
[36mINFO[0m[2017-12-07T13:24:22+08:00] Block saved on disk
       [36mhash[0m=0a08bbe49228fdcfe5e22a8a591fee237f0848dcdc21655ff27e15fd140
00000 [36mheight[0m=9098
[36mINFO[0m[2017-12-07T13:24:22+08:00] Miner processed block
       [36mheight[0m=9098 [36misOrphan[0m=false [36mtx[0m=1
[31mERRO[0m[2017-12-07T13:24:23+08:00] Send failed
       [31mchID[0m=64 [31mconn[0m="MConn{47.96.42.1:46656}" [31mmsg[0m="{S
tatusResponseMessage{Height: 9097, Hash: 1ffb623fb886c6f7a7da947df88bd6160cac88e
9bc7de9a1602b928993020000}}"

**Comment by gguoss** [comment]
问题是种子节点的机器是外网的， 有时网络不好。
