### ISSUE TITLE
命令错误

### ISSUE THREAD

**Issue by errortm** [Bytom/bytom#189]
#### Environment

- OS: macos 10.13.2

#### Problem Description

教程中命令错误：create-accoun,实际不存在这个命令

**Comment by gguoss** [comment]
教程中没有打错create-accoun

**Comment by honhosing** [comment]
@errortm 
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address.

Bytom Core

**Comment by honhosing** [comment]
@errortm 
Dear developer errortm：

你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
