### ISSUE TITLE
What will happen to current Bytom if Bytom v2.0 released?

### ISSUE THREAD

**Issue by Obada8** [Bytom/bytom#1899]
Does the old BTM merge or switch with the new BTM 2.0 automatically on the exchange? Or on the contrary, do I have to do something? Should i sell all current my BTM to avoiding loss?

**Comment by jacksoom** [comment]
> Does the old BTM merge or switch with the new BTM 2.0 automatically on the exchange? Or on the contrary, do I have to do something? Should i sell all current my BTM to avoiding loss?

Maybe you should focus on the btm2.0 white paper
