### ISSUE TITLE
$./bytomcli net-info 信息不易读

### ISSUE THREAD

**Issue by zkaip** [Bytom/bytom#190]
建议 网络信息 显示可读性强一些, 目前都是挤在一坨, 很不好一眼看出来问题

**Comment by gguoss** [comment]
这块我们一直在更新中， 后期会出来用户友好的交互界面

**Comment by Blockmeta** [comment]
下一版会有图形界面的展示。

**Comment by honhosing** [comment]
@zkaip 麻烦提供一下BTM收款地址，我给你发放12月测试奖励~

**Comment by zkaip** [comment]
@honhosing 已发邮件
