### ISSUE TITLE
3 errors

### ISSUE THREAD

**Issue by yunduansing** [Bytom/bytom#191]
#### Environment

- OS: Win10

#### Problem Description
1.create-account response:
```
responses:{  [] 0 <nil>}
account id:
```
2.create-account-receiver response:
`responses:<nil>`
3.bytomcli net-info response:
`net info:<nil>`

note:I just use your official release by [Common Commands of Bytom](https://github.com/Bytom/bytom/wiki/Common-Commands-of-Bytom-(bytom%E7%9A%84%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C))

**Comment by gguoss** [comment]
Check out excute:  ./bytomd node --wallet.enable

**Comment by yunduansing** [comment]
发行资产，出现错误：
To build transaction:
-----------tpl:{<nil> [] false false}
----------tpl transaction:<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x90badd]

**Comment by yunduansing** [comment]
bytomd node --wallet.enable  后出现：
 data:<130994550772:/* unknown wire type 7 */ 1642:/* unknown wire type 7 */ 10:17681930801800169409 159728:7652 9:4897805654558278394 9:/* unexpected EOF */ >]}

could not add UPNP port mapping               [31merror[0m="Error 500 for AddPortMapping"

CPU miner stopped
