### ISSUE TITLE
Readme instructions for create-account requires additional arguments

### ISSUE THREAD

**Issue by jtran064** [Bytom/bytom#200]
#### Environment

- OS: Mac OSX 10.13.1

#### Problem Description

Following the README.md, `./bytomcli create-account alice` no longer works since 

``` Go
func createAccount(client *rpc.Client, args []string) {
	if len(args) != 2 {
		fatalln("error: [alias] [root pub]")
	}
```
requires 2 arguments. Same goes for `create-asset`.

**Comment by gguoss** [comment]
Sorry, README.md not updated.

**Comment by honhosing** [comment]
@jtran064 
Hi, I am Bytom team. Thank you for you participation in Bytom network testing and submitted issues
for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address.

Bytom Core

**Comment by honhosing** [comment]
@jtran064 
Dear developer jtran064：

你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。
Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core

**Comment by jtran064** [comment]
@honhosing 

Dear Peter,

I did not know Bytom has bounties! I have always been interested in Bytom's technology so I just did some research.  As long term fan of Bytom, I have held BTM after ICO on Binance so any more of BTM to my hold is greatly appreciated. Thank you!

Eth Address: 0x7D83f9acEa7E8FaEc004ABD8e5A6F61EF2b51b90

Sincerely,
Jimmy

**Comment by honhosing** [comment]
@jtran064 
Hi, Jimmy. The bounties have been given:
https://etherscan.io/tx/0x33c168c26bea42887b6ab9c759df5abc51b115518ccd3550b182565cdec811b6
Thank you for joining us. And we have a develop community, welcome you to join: https://discord.gg/zukpkkX
