### ISSUE TITLE
发行资产时出现runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV:

### ISSUE THREAD

**Issue by zer0zh1** [Bytom/bytom#201]
#### Environment

- OS: ???
Ubuntu 16.04 LTS 64位
#### Problem Description

按照readme里的教程发行资产，出现runtime error，试几次都是这样
./bytomcli sub-create-issue-tx 07PVCJ61G0A02 74e652ea08dbc102ebb6c9968a3313c98aaf57b448b7804dce37c001f3f91916 1000 e89a313b00a58b8d2a9b79a645055f14280cb86123cbab5bd2c471efc5d8796a52c642e74fd7d0c89d3d9247bf04611931120a9ebb298e987a4641b1a0c2c08b 4089d2ddb8e48d92d162354c1e3f90eb90b791ff5a82398bed86c49251324266e0442ec08678f765089d00035c7d40fd7fe1bbab9f1660b93b7700db16356940
To build transaction:
-----------tpl:{<nil> [] false false}
----------tpl transaction:<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8eb93e]

goroutine 1 [running]:
main.submitCreateIssueTransaction(0xc420010310, 0xc420010090, 0x5, 0x5)
	/home/zer0/workspace/go/src/github.com/bytom/cmd/bytomcli/main.go:555 +0x57e
main.main()
	/home/zer0/workspace/go/src/github.com/bytom/cmd/bytomcli/main.go:129 +0x271

![2017-12-16 16-14-55](https://user-images.githubusercontent.com/23079496/34068773-5feba4e0-e27c-11e7-8b12-1467ecbb9c0a.png)

**Comment by Blockmeta** [comment]
可能是用了不同版本的bytom

**Comment by honhosing** [comment]
@zer0zh1 
你好，我们是比原链团队，感谢你在12月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

比原链团队
Bytom Core

**Comment by zer0zh1** [comment]
soga, 等下用最新版本的代码试试，你好这是我的地址： 0x42b425CBFBDa1ce9a96e54b9Be3dd57b25B5a9B4
