### ISSUE TITLE
Failed to Compile bytom source code on windows platform

### ISSUE THREAD

**Issue by Leekailklk** [Bytom/bytom#202]
windows64 Environment

- OS: windows 64

Build source code 
github.com\bytom\cmd\bytomd\main.go，error as following:

D:/Go/bin/go.exe build -i [E:/Go/src/github.com/bytom/cmd/bytomd]
..\..\vendor\github.com\spf13\cobra\command_win.go:9:2: cannot find package "github.com/inconshreveable/mousetrap" in any of:
E:\Go\src\github.com\bytom\vendor\github.com\inconshreveable\mousetrap (vendor tree)
D:\Go\src\github.com\inconshreveable\mousetrap (from $GOROOT)
E:\Go\src\github.com\inconshreveable\mousetrap (from $GOPATH)
错误: 进程退出代码 1.

problem: The package is missing in the source code package.

sol:ution: 
1. Download the package files from "github.com/inconshreveable/mousetrap"
2.Create Directory inconshreveable\mousetrap under bytom\vendor\github.com
3.unzip the download files and move them to \bytom\vendor\github.com\inconshreveable\mousetrap
directory.
4. Re build and should be ok.

**Comment by gguoss** [comment]
https://github.com/Bytom/bytom/commit/98440d2ed2cf6916e7f69977c79c74ef4f4cc519

Support github.com/inconshreveable/mousetrap
