### ISSUE TITLE
源码只支持类Linux操作系统，不支持Win 7系统。编译报路劲错误。

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#206]
#### Environment

- OS: Windows 7 x64

#### Problem Description

E:\GoWorkSpace\src\github.com\bytom\cmd\bytomd>go build main.go
..\..\vendor\github.com\spf13\cobra\command_win.go:9:2: cannot find package "git
hub.com/inconshreveable/mousetrap" in any of:
        E:\GoWorkSpace\src\github.com\bytom\vendor\github.com\inconshreveable\mo
usetrap (vendor tree)
        E:\Develop\Go\src\github.com\inconshreveable\mousetrap (from $GOROOT)
        E:\GoWorkSpace\src\github.com\inconshreveable\mousetrap (from $GOPATH)

E:\GoWorkSpace\src\github.com\bytom\cmd\bytomd>go env GOROOT GOPATH
E:\Develop\Go
E:\GoWorkSpace

E:\GoWorkSpace\src\github.com\bytom\cmd\bytomd>

**Comment by gguoss** [comment]
go get github.com/inconshreveable/mousetrap

**Comment by gguoss** [comment]
我在linux 环境下就可以直接交叉编译出mac, windows平台的可执行文件

**Comment by Wolkin** [comment]
@gguoss 确实少包了，加入那个包之后，编译就没有问题了。。
