### ISSUE TITLE
使用glide管理

### ISSUE THREAD

**Issue by ShooterTT** [Bytom/bytom#214]
#### Problem Description

推荐使用slide来管理包依赖问题

允许的话，我想试着改一下

**Comment by gguoss** [comment]
以前我们是用glide 管理的， 后面团队成员给删掉了。 如果你可以做到兼容现在的方式的话， 你可以尝试一下。非常感谢！

**Comment by ShooterTT** [comment]
@gguoss 好的，为什么删除掉了，是因为更新依赖比较麻烦吗？

**Comment by gguoss** [comment]
是的， 很多是需要翻墙的
