### ISSUE TITLE
无法创建账户

### ISSUE THREAD

**Issue by 1robo** [Bytom/bytom#217]
#### Environment

- OS: Mac OS 

#### Problem Description

安装，初始化，启动均正常
./bytomd init --chain_id testnet
 ./bytomd node --wallet.enable

也能够查看当前信息
./bytomcli net-info

就是创建账户出错
./bytomcli create-account pony1238876555666
[error: [alias] [root pub]]

开始以为是账户名重复，后来发现无论输入什么名称都是这样。

**Comment by 1robo** [comment]
查了一下源文件

if len(args) != 2 {
		fatalln("error: [alias] [root pub]")
	}

create-account 要两个参数？？ 文档里不是只有一个，这也太坑了。

**Comment by gguoss** [comment]
Sorry, 是现在的Readme 和最新的代码不匹配， 需要先./bytomd create-key [name] [passwd], 然后才能./bytomd create-account [name] [上步的公钥]

**Comment by 1robo** [comment]
ok . 按新方法 可以创建新账户。
