### ISSUE TITLE
几天没更新，今天测试网络更新后发现一个ERR 不知是什么BUG

### ISSUE THREAD

**Issue by cryptodjyy** [Bytom/bytom#229]
#### Environment

- OS: Mac OSX

#### Problem Description

几天没连接比原测试网络，今天上来测试 更新区块后发现一个没见过的ERR 不知是什么BUG。

```
INFO[2046] Receive request                               msg="BlockRequestMessage{Hash: 0000000000000000000000000000000000000000000000000000000000000000}" peerID=072404E311B1DD8D956C0C1FAA1A9571738CFC12BA27AD5C6F09088DAB24EC58
ERRO[2046] Fail on BlockRequestMessage get block: There are no block with given hash 0000000000000000000000000000000000000000000000000000000000000000
```

![screen shot 2017-12-30 at 11 42 15 am](https://user-images.githubusercontent.com/34213402/34455882-9cd07f22-ed56-11e7-8ac3-7b0caaf34de8.png)

**Comment by gguoss** [comment]
你这问题的原因是， 你本地的同步的数据是原来的老数据。
重新部署了测试网， 和更新了版本0.3.0， 需要重新测。
