### ISSUE TITLE
sub-create-issue-tx 出错

### ISSUE THREAD

**Issue by motto0808** [Bytom/bytom#232]
#### Environment

- OS: windows 10

#### Problem Description

D:\bytom>bytomcli.exe sub-create-issue-tx 08EP127IG0A02 cd98dcea7458ffbcc5f4a18a8bdc1700444071e4e7c98de22f042aed6e3d089d 1000 7027c245cfeb0d2dbae6d982d4918aef962a8ffca792287f86e9fcd55bb6f76f1483c7be6fefa1ee9f1b1fc3738b4c98b69a05ff2a8830d36b5c0dfd1f907086 50c63c980bf2c10857372f2e77a8579b14f41c93b475242a1c8a2c3b26661e7da97dd9fde0d712634350e3ed1f83ea0d07f2f38a2fbeb242185bbad1d815cb0c
To build transaction:
-----------tpl:{<nil> [] false false}
----------tpl transaction:<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x90badd]

goroutine 1 [running]:
main.submitCreateIssueTransaction(0xc04206c2a0, 0xc04206c020, 0x5, 0x5)
        D:/workspace/src/github.com/bytom/cmd/bytomcli/main.go:555 +0x58d
main.main()
        D:/workspace/src/github.com/bytom/cmd/bytomcli/main.go:129 +0x12c

**Comment by liuchengxu** [comment]
`sub-create-issue-tx` is deprecated already, please try with the latest version.
