### ISSUE TITLE
[error: [alias] [root pub]] 不知道为什么没法建立新账号？

### ISSUE THREAD

**Issue by dalinhuang99** [Bytom/bytom#233]
#### Environment

- OS: MacOS High Sierra 10.13.1 (17B1003)

#### Problem Description
更新了区块链后无法创建用户？
```
./bytomcli create-account alice
[error: [alias] [root pub]]
```

删除了以前的文件夹，从新下载按照步骤
```
./bytomcli create-account alice
```
无法创建用户？

得到以下错误信息：
```
[error: [alias] [root pub]]
```

**Comment by liuchengxu** [comment]
Please pull the latest version and follow the instructions in README. The refactored `bytomcli` is more user friendly. Feel free to reopen if you still run into this issue.
