### ISSUE TITLE
资产余额不显示

### ISSUE THREAD

**Issue by gguoss** [Bytom/bytom#240]
#### Environment

- OS: Ubuntu

#### Problem Description

 基于同一个key建立的多个账户， 只能给第一个拥有该key 的账户正常转帐， 给第二到第n个拥有该key的账户转帐， 被转帐的账户余额显示不正常。

**Comment by icodezjb** [comment]
time="2018-01-03T18:00:01+08:00" level=error msg="walletUpdater GetBlockByHash" err="There are no block with given hash 0583460c5fc7129090c57ee6a8a74f692786303924681a1e70b6a4fe2a050000"

bytomd报如上错误，钱包更新程序应该中断过，且0583460c5fc7129090c57ee6a8a74f692786303924681a1e70b6a4fe2a050000 这个块发生过回滚，walletUpdater 找不到该块，异常退出。相应的transaction,UTXO都不进行索引，因此账户余额状态没有更新。
