### ISSUE TITLE
Could not parse JSON response

### ISSUE THREAD

**Issue by dominolu** [Bytom/bytom#244]
ubuntu 16
bytom 0.3.0
初次安装完成，启动后，能够进入dashboard
但进入accouts时，页面提示报错:Could not parse JSON response

**Comment by 1robo** [comment]
猜测机器是不是有防火墙什么的或者某个端口没打开。

我有两个节点，一个在本地，一切正常。
另一个在外网，也是同样的报错，但是找不具体原因。

**Comment by LoganLai** [comment]
无防火墙，搬瓦工机器，应该不是防火墙的问题。
机器
![image](https://user-images.githubusercontent.com/14155268/34666553-e67db7d4-f49f-11e7-9c77-15c9b1d8c6b9.png)
页面
![image](https://user-images.githubusercontent.com/14155268/34666565-fa1fe938-f49f-11e7-8ff9-accd8d1141a1.png)
后台
![image](https://user-images.githubusercontent.com/14155268/34666576-0bc03a26-f4a0-11e7-8d6b-2c06e3943482.png)

**Comment by wliyongfeng** [comment]
最新版本应该已经解决，请下载最新版本或build我们的最新代码再测试下。
