### ISSUE TITLE
发布的wiki教程新版3.0 有一个命令错误！

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#245]
#### Environment

- OS: ???

#### Problem Description
链接
https://github.com/Bytom/bytom/wiki/dashboard-tutorial

"$ ./bytomd node --chain_id testnet"  这里的node 应该是init 下面的截图是对的 可是上面写错了 会误导小白造成麻烦的

**Comment by liuchengxu** [comment]
Fixed, thanks.
