### ISSUE TITLE
build-transaction -t spend problem 

### ISSUE THREAD

**Issue by 1robo** [Bytom/bytom#246]
#### Environment

- OS:  CentOS release 6.9

#### Problem Description

Spend
Bob  pays another guy 333  gold and 333 btm

but same command 
$ ./bytomcli build-transaction -t spend bob gold 333 --alias -r 76XXXXXXXXX
is ok.
$ ./bytomcli build-transaction -t spend bob btm 333 --alias -r 76XXXXXXXXX
errors occurred in one or more actions

attach the screenshot
![pic](https://user-images.githubusercontent.com/34087593/34594029-74643a94-f209-11e7-96b8-12cc07a4ed7f.jpg)

**Comment by liuchengxu** [comment]
Please check out whether your BTM balance is enough for the second transaction building. Every `build-transaction` action will reserve 2,000,000(default) BTM as the transaction fee.

**Comment by 1robo** [comment]
thanks , but in this case . (see at  screenshot)
./bytomcli list-balances
bob have 999980,000,000 btm

**Comment by honhosing** [comment]
Hi, I am Bytom team. Thank you for you participation in Bytom network testing and submitted issues
 for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. 

Bytom Core

**Comment by 1robo** [comment]
0xC83b205BCda620cc1eD9305bAa9FdFfc9359c23A

Thank you, I am honored to do something for Bytom team .
I believe in Bytom will change the world .
