### ISSUE TITLE
按照网页的向导操作，不能转出btm

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#251]
#### Environment

- OS: ??? window 7

#### Problem Description

按照这个向导，在windows上面安装了win 7 版的 btm客户端，按照这个向导操作
https://github.com/Bytom/bytom/wiki/dashboard-tutorial
增加了account, asset, 然后有人转入很多btm, 安装网页的操作，转出88888888个btm 给 "account_alias": "zyowe",  "account_id": "08IDVK0O00A02"， 点击提交，一直是submitting 状态，用户也没有收到btm.

另外一个问题，我的asset的名字是gold, 但是balance里面的asset alice 是btm, 这不对。

**Comment by VictorWei000** [comment]
![account](https://user-images.githubusercontent.com/14964955/34604433-b5b00d64-f242-11e7-859f-8ca349a61c62.jpg)
![asset](https://user-images.githubusercontent.com/14964955/34604434-b5e59240-f242-11e7-87e1-e4ddcb98cc5c.jpg)
![balance](https://user-images.githubusercontent.com/14964955/34604435-b61b8972-f242-11e7-8cf3-bd1ac8a55008.jpg)
![keys](https://user-images.githubusercontent.com/14964955/34604436-b650826c-f242-11e7-9ebe-ac1e90fc212c.jpg)
![submitting](https://user-images.githubusercontent.com/14964955/34604437-b682d5c8-f242-11e7-9207-b9c45cf56004.jpg)

**Comment by honhosing** [comment]
Dear developer @VictorWei000 ：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core

**Comment by wliyongfeng** [comment]
@VictorWei000 请使用我们的最新版重新测试下。
