### ISSUE TITLE
Can not execute make bytomd

### ISSUE THREAD

**Issue by nomadcamp** [Bytom/bytom#252]
Im on a fresh ubuntu 14.04 64bit install. installed go and set GOPATH as $Home where the src folder is located.  When I enter `make bytomd`  i get this error:
`/bin/sh 1: go: not found
make: *** [bytomd] Error 127`

**Comment by liuchengxu** [comment]
What's your `HOME`, `GOPATH` and `pwd`?
```bash
$ echo $HOME
$ echo $GOPATH
$ pwd
```

**Comment by honhosing** [comment]
Dear developer @nomadcamp ：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
