### ISSUE TITLE
一切配置正常的情况下！猎豹浏览器，IE9 无法显示dashboard 不支持html5的事？

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#254]
#### Environment

- OS: ???

#### Problem Description
同时用 谷歌，火狐，IE9，猎豹浏览器 
谷歌，火狐 没有问题 
IE9 猎豹就不行
应该是对html5 支持不好的原因吧，最好去说明一下！否则不太懂的客户 以为是开发问题，不是自己浏览器老！

**Comment by wliyongfeng** [comment]
目前没有对IE做兼容，请使用最新版的chrome
