### ISSUE TITLE
Win 7 64位运行bytom-0.3.0.amd64版本，执行Launch时异常

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#259]
#### Environment

- OS: Windows 7 x64

#### Problem Description
使用bytom-0.3.0.amd64程序包，initialize the node正常，在执行bytomd node --wallet.enable --mining时抛出false和fail异常。
如下图

![test](https://user-images.githubusercontent.com/34227886/34659931-3152f1c4-f479-11e7-8f75-a1664addbd4e.png)

**Comment by semliu** [comment]
同步完成

**Comment by wliyongfeng** [comment]
We are refactoring and improving the p2p module, and please track the latest `dev` branch.
