### ISSUE TITLE
缺少对Windows 7 X86的支持，在32位系统上无法使用

### ISSUE THREAD

**Issue by wlma0301** [Bytom/bytom#261]
#### Environment

- OS: Windows 7 X86

#### Problem Description

E:\GoWorkSpace\bytom-0.3.0.amd64>bytomd init --chain_id testnet
该版本的 E:\GoWorkSpace\bytom-0.3.0.amd64\bytomd.exe 与您运行的 Windows 版本不兼
容。请查看计算机的系统信息，了解是否需要 x86 (32 位)或 x64 (64 位)版本的程序，然
后联系软件发布者。

win7系统编译不通过，https://github.com/Bytom/bytom/wiki/dashboard-tutorial 提供的编译后的包
只有amd64、mac、ubuntu
没有X86(32位)的版本，无法安装运行

需要对Windows 7 X86的提供支持

**Comment by Blockmeta** [comment]
后续会加入。 现在amd64就是64位的系统。

**Comment by honhosing** [comment]
Dear developer @wlma0301 ：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
