### ISSUE TITLE
转账无法成功，一直显示提交状态

### ISSUE THREAD

**Issue by wuwoweishui** [Bytom/bytom#262]
#### Environment

- OS: win7 64位系统

#### Problem Description
按照这个向导操作，在win 764位系统 版的 btm网页客户端，进行转账操作， 点击提交，一直是submitting 状态，用户也没有收到btm.

如有问题请联系我的微信号：wuwoweishui

![01](https://user-images.githubusercontent.com/3350482/34662535-60c1eb14-f48c-11e7-857e-7fcce598b647.JPG)
![02](https://user-images.githubusercontent.com/3350482/34662537-641f7f60-f48c-11e7-8783-61b69ffc140c.JPG)
![03](https://user-images.githubusercontent.com/3350482/34662539-66f0f1a6-f48c-11e7-8a6f-13889ee6f2c4.JPG)

**Comment by honhosing** [comment]
Dear developer @wuwoweishui ：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core

**Comment by wliyongfeng** [comment]
最新版本应该已经解决该问题，请下载最新代码或build最新代码再测试下。
