### ISSUE TITLE
Bytom Dashboard测试Bug和几点使用建议

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#264]
#### Environment

- OS: Windows 7 x64

#### Problem Description
Bytom Dashboard测试的Bug：
1、转账操作无任何响应，一直处于Submit...状态。
     建议：控制响应时间，无法提交成功、网络超时或者其他异常导致的几秒钟内无法获得响应，应提示用户后续操作。

Bytom Dashboard使用的几点建议：
1、新建资产界面，资产类型建议用确定选项模式（下拉框、弹出表格选项等），手工输入容易导致操作风险。
2、转账操作界面的转出操作，手续费用不明确，需要选择两次Spend from account。
3、建议转出金额、接收金额可以进行简易交易或控制，如转出金额需与接收金额相等校验，适当减轻非法交易进入比原链网络。
4、建议多次选择Spend from account进行控制，确认是否操作失误。多种资产转出、转入校验控制等。

**Comment by wliyongfeng** [comment]
> 1、转账操作无任何响应，一直处于Submit...状态
已修复

> Bytom Dashboard使用的几点建议：
感谢建议，我们会认真考虑。同时产品也在不断改进中，希望不断跟进。
