### ISSUE TITLE
bytomcli sign-submit-transaction 出错

### ISSUE THREAD

**Issue by rollsyang** [Bytom/bytom#268]
#### Environment

- OS: Win10
- BYTOMCLI:  v0.1.2-3712c2af windows/amd64
#### Problem Description

$bytomcli build-transaction -t issue rollsyang btc_ry 10000 --alias
return:
{"allow_additional_actions":false,"local":true,"raw_transaction":"07010002019d01019a01fb77ab11fafc5cf0446d552724aed272b71cfc7ac7d032d2b1de8890e482d0beffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80c0b1ca9412000131cd02d707a069766baa208c23403c53ab6d7940285a2b6a224b6804b06f82b83553cc303681b443445b685151ad696c00c0a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a000100012c0008f25d791811bf364a1209305aa7173782cf5dcd1a5b5a5c722bcbd3436e1f83eea834fe6e242a20d4904e004f64eaa1cae4cf14f775251c5eb786376d2cf218e488dcea79826b9ce56d0a000000012b766baa208ce1611d137ebe6c635f70c4feb09cda22e459b37d793df0cbe0d79970b4ca9c5151ad696c00c000020153ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80e6ecc09412012b766baa20b26d7a0091b96b79ab49629d307f6a7d86756d4c28e3640eefbc64154ed2e7d25151ad696c00c00000014f1209305aa7173782cf5dcd1a5b5a5c722bcbd3436e1f83eea834fe6e242a20d4904e012b766baa200404a87f813cfa488f63db70558295bffedcbb855942b788f109cb0deaec56a65151ad696c00c0000000","signing_instructions":[{"position":0,"witness_components":[{"keys":[{"derivation_path":["010100000000000000","0200000000000000"],"xpub":"300347c32ba17c10201c4f313734af8a98221caa3f0917c84b97b8a30bd53fc51350b0b4152e8459f1a59ccc653259751df03c77ac5e695395708b65b5b16753"}],"quorum":1,"signatures":null,"type":"signature"}]},{"position":1,"witness_components":[{"keys":[{"derivation_path":["000300000000000000"],"xpub":"300347c32ba17c10201c4f313734af8a98221caa3f0917c84b97b8a30bd53fc51350b0b4152e8459f1a59ccc653259751df03c77ac5e695395708b65b5b16753"}],"quorum":1,"signatures":null,"type":"signature"}]}]}

$$bytomcli sign-submit-transaction '{"allow_additional_actions":false,"local":true,"raw_transaction":"07010002019d01019a01fb77ab11fafc5cf0446d552724aed272b71cfc7ac7d032d2b1de8890e482d0beffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80c0b1ca9412000131cd02d707a069766baa208c23403c53ab6d7940285a2b6a224b6804b06f82b83553cc303681b443445b685151ad696c00c0a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a000100012c0008f25d791811bf364a1209305aa7173782cf5dcd1a5b5a5c722bcbd3436e1f83eea834fe6e242a20d4904e004f64eaa1cae4cf14f775251c5eb786376d2cf218e488dcea79826b9ce56d0a000000012b766baa208ce1611d137ebe6c635f70c4feb09cda22e459b37d793df0cbe0d79970b4ca9c5151ad696c00c000020153ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80e6ecc09412012b766baa20b26d7a0091b96b79ab49629d307f6a7d86756d4c28e3640eefbc64154ed2e7d25151ad696c00c00000014f1209305aa7173782cf5dcd1a5b5a5c722bcbd3436e1f83eea834fe6e242a20d4904e012b766baa200404a87f813cfa488f63db70558295bffedcbb855942b788f109cb0deaec56a65151ad696c00c0000000","signing_instructions":[{"position":0,"witness_components":[{"keys":[{"derivation_path":["010100000000000000","0200000000000000"],"xpub":"300347c32ba17c10201c4f313734af8a98221caa3f0917c84b97b8a30bd53fc51350b0b4152e8459f1a59ccc653259751df03c77ac5e695395708b65b5b16753"}],"quorum":1,"signatures":null,"type":"signature"}]},{"position":1,"witness_components":[{"keys":[{"derivation_path":["000300000000000000"],"xpub":"300347c32ba17c10201c4f313734af8a98221caa3f0917c84b97b8a30bd53fc51350b0b4152e8459f1a59ccc653259751df03c77ac5e695395708b65b5b16753"}],"quorum":1,"signatures":null,"type":"signature"}]}]}'

报错: ERROR 2018/01/09 23:26:00 invalid character '\\'' looking for beginning of value

另外在虚拟机ubuntu16.04 LTS版本，version go1.9.2 linux/amd64 编译出来的bytomcli
Account: rollsyang及Asset: btc_ry资产都已经创建成功，执行下面命令报错

rollsyang@rollsyang:~/gowork/src/github.com/bytom/cmd/bytomcli$ ./bytomcli build-transaction -t issue rollsyang btc_ry 10000 --alias
ERROR 2018/01/09 23:20:07 errors occurred in one or more actions

这种请问是什么原因呢

**Comment by icodezjb** [comment]
你好，欢迎下载测试最新版https://github.com/Bytom/bytom/releases

**Comment by honhosing** [comment]
Dear developer @rollsyang ：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core
