### ISSUE TITLE
errors occurred in build-transaction

### ISSUE THREAD

**Issue by starit** [Bytom/bytom#284]
#### Environment

- OS: macOS 10.13.1

#### Problem Description

when I followed the README.md and  type the following command:
```bash
./bytomcli build-transaction -t issue alice gold 10000 --alias
```
it shows 
```
ERROR 2018/01/15 12:20:12 errors occurred in one or more actions
```

As same as README.md

**Comment by wliyongfeng** [comment]
Please test it with the latest version.
