### ISSUE TITLE
关于3.0测试的若干建议

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#312]
#### Environment

- OS: ???

#### Problem Description

个人建议有待进一步友好方面
1.完美的配色和ui设计毋庸置疑，但是BTM还是有大量中国客户，建议增加多语言
2.尽量增加各种功能的说明文字，多一些说明
3.尽量各种名词采用较能被普通人理解的命名方式，例如contorl 这个词语也许再技术上更准确，但是对于用户，那简直是烧脑……，简单的用接收方或者更形象的最好，毕竟是面对普通用户，不是面对IT精英，同理还有control program 这个词语，玩钱包的估计更能理解address,虽然adrress不一定准确。

以下是一个重点问题
若是还没有开发，就当我没说，若是就想用这种方式面世，个人觉得真的会因为复杂而不妥。

这个问题就是转账问题
1.【不友好的转账设计】竟然一笔转账需要手动添加至少两次action，我刚接触的时候，第一感觉是可以同时在这个submit按钮事件下同时提交很多转账才这样设计，第一感觉真好，可是用了才发现，生生的吧转账方，接收方分成了两个表单，必须手动增加这两个表单，
填写无误后再submit才可以转账成功，这样跟日常人行为习惯完全相悖，非常容易丢失没有耐心的客户，我也是有一定经验和之前用过命令行终端，自己摸索才搞明白，包括教程，给人的感觉也是先submit转账方，再submit接收方，其实最简单的设计就是直接构建一个表单，
内容中包含转账方，和接收方（接收方再去分类是账户接收还是地址接收），若是可以一个submit提交好几笔转账，完全可以模仿 添加账户，做一个add another transcation 这样在动态增加下一个div和表单 一起submit. 说白了就是要分类明晰，要让普通人一看就知道往哪里填写内容怎么用，这样真的太烧脑，
网银开发上招商银行的网银普遍反映都特别好，不是功能有多么强大，而是各种按键的布置和表单符合人的潜意识。个人觉得这个转账ui设计真的是不妥，也许困扰的人不少。再推荐一个失败的例子，若是知道这个币pasc，可以去用一下，你就是个专业的，用明白也得半天，所以目前币的技术貌似挺有特点，就是无人关注。
2.【转账手续费设计问题】同上面一样，竟然让用户自己计算填写手续费？这就会有不友好的问题和下面我测试出另外一个问题更为严重，先说不友好的问题，正常手续费比较好的设计都是提前自动计算，转账金额一出来，就提前告知转账多少，手续费多少，实际收到多少，再退一步讲，就是不提示手续费多少，转了你也自动扣啊，
怎么会让用户自己去计算手续费，然后再在接收方填写减去手续费的金额……这有点太尴尬了吧，当然若是因为是测试才这样故意的 就当我没说，下面说一个重要的问题关于手续费
3.【手续费丢币问题】 由于让自己填收款金额，举例我从账号1 转出100000000，实际手续费20000000，就够了，这时候我需要填写接收方账号2，收款80000000，但是当我填写收款金额为30000000的时候，也就是说小于付款-手续费的时候，多余的币竟然不返还付款方，生生的没了……情景举例：若是客户转账100块钱，手续费20块，实际收到80块，而
用户手残，80写成了8，那么讲产生92块的手续费，用户能不骂娘吗……？

**Comment by wliyongfeng** [comment]
> 个人建议有待进一步友好方面

感谢提出的建议，目前已经添加了对普通用户友好的normal转账方式。同时团队精力有限，其它方面也在不断优化。

> 这个问题就是转账问题

#313 中已回复。
