### ISSUE TITLE
建议也许写的太长-说重点吧-手续费吞币问题！

### ISSUE THREAD

**Issue by btmtest** [Bytom/bytom#313]
#### Environment

- OS: ???

#### Problem Description

【手续费丢币问题】 由于让自己填收款金额，举例我从账号1 转出100000000，实际手续费20000000，就够了，这时候我需要填写接收方账号2，收款80000000，但是当我填写收款金额为30000000的时候，也就是说小于付款-手续费的时候，多余的币竟然不返还付款方，生生的没了……情景举例：若是客户转账100块钱，手续费20块，实际收到80块，而
用户手残，80写成了8，那么讲产生92块的手续费，用户能不骂娘吗……？

**Comment by wolfbrother** [comment]
太口语花了。能不能用文言文来表达，这样显得格调高许多

**Comment by wliyongfeng** [comment]
@btmtest 差额费用给了矿工，用户填写交易时要检查清楚。
