### ISSUE TITLE
Git pull最新代码，按Readme文档操作，出现ERROR: unknown flag: --wallet.enable

### ISSUE THREAD

**Issue by Devin001** [Bytom/bytom#336]
#### Environment

- OS: Mac OSx  10.11.6

#### ERROR: unknown flag: --wallet.enable

1, git pull 最新代码，根据官方文档启动Bytomd
![image](https://user-images.githubusercontent.com/11387477/35546961-5cbb1802-05b1-11e8-83b2-3767a10ac027.png)

出现 ERROR: unknown flag: --wallet.enable 错误。

2， ./bytomd node -h 如下
![image](https://user-images.githubusercontent.com/11387477/35546991-8797573e-05b1-11e8-999c-630579de6221.png)

只有 --wallet.disable ，难道是默认enable?

**Comment by Blockmeta** [comment]
不好意思， 官方文档没更新。 默认应该enable的。
