### ISSUE TITLE
win10系统

### ISSUE THREAD

**Issue by biggerJack** [Bytom/bytom#348]
#### Environment

- OS: ???

#### Problem Description

win10.64位不能开启使用程序

**Comment by biggerJack** [comment]
诺，程序不能使用测试

**Comment by icodezjb** [comment]
Common Commands of Bytom (bytom的常用操作) · Bytom/bytom Wiki
https://github.com/Bytom/bytom/wiki/Common-Commands-of-Bytom-(bytom%E7%9A%84%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C)
