### ISSUE TITLE
can't find block in given hight

### ISSUE THREAD

**Issue by winlin** [Bytom/bytom#350]
#### Environment

- OS: Mac 10.13.2

#### Problem Description

运行方式 ./bytomd node --mining
一直出现错误信息：ERRO[0112] Fail on BlockRequestMessage get block: can't find block in given hight

而且获取的height 18903、139 交替出现

INFO[0036] Receive request                               msg="StatusResponseMessage{Height: 18903, Hash: 843aee3873800faa35cccd95403fa71f3102725d01bde249439885224bd471ee}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0037] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0037] blockKeeper processed block                   hash=771b996dfaf1f0f4ecc906074fd98d95784c52eb058effe0c0e977d45588ab04 height=72 isOrphan=true
INFO[0037] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0037] blockKeeper processed block                   hash=a24076aa1966c679863802c2cb40b90cc817d186d7e377eb74aca3ae4bb263fb height=71 isOrphan=true
INFO[0037] Receive request                               msg="BlockRequestMessage{Height: 139}" peerID=796A4EB8251FE27534F16E02C3938E349B6C24099FC283B80E9057D088E9C9B9
ERRO[0037] Fail on BlockRequestMessage get block: can't find block in given hight
INFO[0038] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A

**Comment by Blockmeta** [comment]
@Paladz

**Comment by Paladz** [comment]
内核已改，无法复现
