### ISSUE TITLE
ERROR: unknown flag: --wallet.enable

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#351]
Mac OSX 10.13.3 (High Sierra)
GO Version go version go1.9.3 darwin/amd64

Following compile steps from github, it reports 
ERROR: unknown flag: --wallet.enable when running
./bytomd node --wallet.enable --mining

Cloning into '/Users/user1/go/src/github.com/bytom'...
remote: Counting objects: 16858, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 16858 (delta 40), reused 45 (delta 13), pack-reused 16731
Receiving objects: 100% (16858/16858), 39.64 MiB | 3.28 MiB/s, done.
Resolving deltas: 100% (7168/7168), done.
adsl-172-10-0-144:~ user1$ cd $GOPATH/src/github.com/bytom
-bash: cd: /src/github.com/bytom: No such file or directory
adsl-172-10-0-144:~ user1$ cd /Users/user1/go/src/github.com/bytom
adsl-172-10-0-144:bytom user1$ make bytomd
Building bytomd to cmd/bytomd/bytomd
adsl-172-10-0-144:bytom user1$ make bytommcli
make: *** No rule to make target `bytommcli'.  Stop.
adsl-172-10-0-144:bytom user1$ make bytomcli
Building bytomcli to cmd/bytomcli/bytomcli
adsl-172-10-0-144:bytom user1$ cd ./cmd/bytomd
adsl-172-10-0-144:bytomd user1$ ./bytomd init --chain_id testnet
INFO[0000] Initialized bytom                             genesis=.bytomd/genesis.json
adsl-172-10-0-144:bytomd user1$ ./bytomd node --wallet.enable --mining
**ERROR: unknown flag: --wallet.enable**
adsl-172-10-0-144:bytomd user1$

**Comment by Leekailklk** [comment]
The 0.4 version bytom was changed source code from --wallet.enable to--wallet.disable in the program.
You can try use " ./bytomd node --mining" or "./bytomd node" to start 。

**Comment by wliyongfeng** [comment]
currently wallet is enabled by default, while we provide [--wallet.disable](https://github.com/Bytom/bytom#launch) to disable it.
