### ISSUE TITLE
http://127.0.0.1:9888/dashboard/balances - Stuck with "Loading"

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#353]
Mac OS High Sierra
10.13.3

go version go1.9.3 darwin/amd64

From WEBPAGE:

NETWORK STATUS
listening: true
syncing: false
mining: false
peerCount: 2
currentBlock: 63
highestBlock: 18903

The Website balances page is stuck on Loading...

**Comment by wliyongfeng** [comment]
Fixed in latest `dev` branch. #508
