### ISSUE TITLE
是否可以增加功能--支持中文语言

### ISSUE THREAD

**Issue by Flyfeet** [Bytom/bytom#357]
#### Environment

- OS: win10-64

**Comment by Blockmeta** [comment]
正在开发中

**Comment by xianshengyu** [comment]
![image](https://user-images.githubusercontent.com/21304805/36093774-a8e950e8-1026-11e8-9e5d-8a22b3c5bb6f.png)

**Comment by wliyongfeng** [comment]
目前dashboard已支持中文。
