### ISSUE TITLE
关于密钥安全问题

### ISSUE THREAD

**Issue by Flyfeet** [Bytom/bytom#360]
#### Environment

- OS: win10-64

#### Problem Description

> **初步测试发现，密钥生成后导出过程没有加密，同时，密钥导入也不需要提供密码，若获取了密钥文件，直接导入就可以用，存在严重安全风险。建议密钥文件导入导出过程加入用户口令进行对称加密。**

**Comment by Blockmeta** [comment]
密钥已经加密。 由于某些功能还没完备， 所以代码中设置了默认密码。

**Comment by Flyfeet** [comment]
默认的密码是随机的吗？或者说针对不同的密钥，这个默认的密码是这么变化的呢？
