### ISSUE TITLE
Dashboard的Balances界面一直显示“LOADING”状态，“界”版本还是正常状态

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#368]
#### Environment

- OS:  Windows 7 x64

#### Problem Description
本次测试使用编译后的“诺”版本（bytom-0.4.0windows_amd64.tar.gz）进行测试的，进入Dashboard的Balances界面无法正常使用，一直显示装载状态，无法正常查看余额和转账状态等。
![20180207141137](https://user-images.githubusercontent.com/34227886/35901686-e09d4b10-0c12-11e8-8c5f-c0e67b5e80f5.png)

**Comment by zkaip** [comment]
Environment
OS: MacOS High Sierra Version 10.13.3

---------------
也是 neu 版本，也出现这种现象

**Comment by wliyongfeng** [comment]
Fixed in latest `dev` branch.
