### ISSUE TITLE
Accounts和Assets重复性校验区分大小写容易出现操作失误

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#369]
#### Environment

- OS: Windows 7 x64

#### Problem Description
Accounts和Assets重复性校验的建议：重复性校验个人建议不要区分大小写，在发布、定义账户和资产过程中，每个人的操作习惯不同，可能之前定义了大写，这次定义小写，如果账户和资产多的时候容易给使用者引起混淆。
![accounts](https://user-images.githubusercontent.com/34227886/35902351-d4f736ce-0c15-11e8-829d-0d8146284831.png)
![assets](https://user-images.githubusercontent.com/34227886/35902356-ddb8217e-0c15-11e8-9080-42e443529cec.png)

**Comment by Blockmeta** [comment]
good idea. 下一版会改变。

**Comment by wliyongfeng** [comment]
fixed #502 

对于asset，创建后alias会被转换为大写；对于account和key，创建后alias会被转换为小写。
