### ISSUE TITLE
Git Clone 最新代码，运行节点后，CPU一直居高不下

### ISSUE THREAD

**Issue by Devin001** [Bytom/bytom#381]
#### Environment

- OS: OS X 10.11.6

#### Problem Description

从Github上Clone最新的代码，启动Bytomd进程后，CPU立马就上去，占用率很高，一直不下来，截图。知道关闭进程才好。

![image](https://user-images.githubusercontent.com/11387477/36088392-05fe2372-1012-11e8-8245-923988964d57.png)

从终端里面的日志来看，一直显示这个Error

ERRO[2018-02-12T16:34:00+08:00] Fail on BlockRequestMessage get block: can't find block in given hight

感觉是同步区块有问题，但运行几个小时也无法同步完毕。启动./bytomd node. 一开始就报这个错误
./src/github.com/bytom/cmd/bytomd/.bytomd/keystore: No such file or directory

**Comment by wliyongfeng** [comment]
请下载最新版或编译最新代码（master或dev分支）重新试一下
