### ISSUE TITLE
 Looks like re-connection is not working. Error Connecting to peer - EOF

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#382]
#### Environment

MacOS High Sierra
10.13.3
go version go1.9.3 darwin/amd64

#### Problem Description

Leave Bytom running, 

Suspend the laptop

Get these errors when it comes back online

INFO[2018-02-13T08:58:15Z] Dialing peer                                  address="47.96.42.1:46656"
ERRO[2018-02-13T08:58:15Z] MConnection flush failed                      error="write tcp 192.168.1.5:53227->47.96.42.1:46656: use of closed network connection"
INFO[2018-02-13T08:58:17Z] Peer handshake                                peerNodeInfo="NodeInfo{pk: PubKeyEd25519{62C3B23C650298D53DCBA8DD15B5AF2C1F6F53D3188455C04F8A984F0183005E}, moniker: anonymous, network: bytom [remote , listen 10.80.155.150:46656], version: 0.4.0-62658d83 ([wire_version=0.7.1 p2p_version=0.5.0])}"
INFO[2018-02-13T08:58:17Z] Added peer                                    peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
INFO[2018-02-13T08:58:17Z] Dialed and added peer                         address="47.96.42.1:46656" error="<nil>"
INFO[2018-02-13T08:58:17Z] Reconnected to peer                           peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
INFO[2018-02-13T08:58:17Z] Dialing peer                                  address="45.79.213.28:46656"
ERRO[2018-02-13T08:58:17Z] Connection failed @ recvRoutine (reading byte)  conn="MConn{47.96.42.1:46656}" error=EOF
INFO[2018-02-13T08:58:17Z] Stopping peer due to error                    error=EOF peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
INFO[2018-02-13T08:58:17Z] Delete peer from blockKeeper                  ID=62C3B23C650298D53DCBA8DD15B5AF2C1F6F53D3188455C04F8A984F0183005E
INFO[2018-02-13T08:58:17Z] Reconnecting to peer                          peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
INFO[2018-02-13T08:58:17Z] Dialing peer                                  address="47.96.42.1:46656"
ERRO[2018-02-13T08:58:17Z] MConnection flush failed                      error="write tcp 192.168.1.5:53229->47.96.42.1:46656: use of closed network connection"
INFO[2018-02-13T08:58:18Z] Peer handshake                                peerNodeInfo="NodeInfo{pk: PubKeyEd25519{DE77434E3C69986F933370EFCEA1608F4363C955B44B1310C51BA8550F9AC615}, moniker: anonymous, network: bytom [remote , listen 45.79.213.28:46656], version: 0.4.0-62658d83 ([wire_version=0.7.1 p2p_version=0.5.0])}"
INFO[2018-02-13T08:58:18Z] Failed to add peer                            address="45.79.213.28:46656" error="Duplicate peer"
INFO[2018-02-13T08:58:18Z] Error reconnecting to peer. Trying again      error="Duplicate peer" retries=26
INFO[2018-02-13T08:58:20Z] Peer handshake                                peerNodeInfo="NodeInfo{pk: PubKeyEd25519{62C3B23C650298D53DCBA8DD15B5AF2C1F6F53D3188455C04F8A984F0183005E}, moniker: anonymous, network: bytom [remote , listen 10.80.155.150:46656], version: 0.4.0-62658d83 ([wire_version=0.7.1 p2p_version=0.5.0])}"
INFO[2018-02-13T08:58:20Z] Added peer                                    peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
INFO[2018-02-13T08:58:20Z] Dialed and added peer                         address="47.96.42.1:46656" error="<nil>"
INFO[2018-02-13T08:58:20Z] Reconnected to peer                           peer="Peer{MConn{47.96.42.1:46656} 62C3B23C6502 out}"
ERRO[2018-02-13T08:58:20Z] Connection failed @ recvRoutine (reading byte)  conn="MConn{47.96.42.1:46656}" error=EOF

**Comment by cwiles** [comment]
Still an issue with NEU 0.4.0

**Comment by shengling2008** [comment]
linux系统中EOF表示文件读到末尾。socket中没有EOF表示，但是读取数据返回0，表示server关闭连接。go语言中把这种情况认为是EOF。
