### ISSUE TITLE
执行bytomd出现异常

### ISSUE THREAD

**Issue by xiongls** [Bytom/bytom#395]
#### Environment

- OS: Win7-x64

#### Problem Description

bytomd node --mining

[36mINFO[0m[0000] Rpc listen                                    [36mapi addre
ss:[0m="0.0.0.0:9888"
[36mINFO[0m[0000] Local listener                                [36mip[0m=":
:" [36mport[0m=46656
[36mINFO[0m[0000] Getting UPNP external address
2018/03/03 18:53:41 http: panic serving 127.0.0.1:58706: runtime error: invalid
memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*conn).serve.func1(0xc04215d540)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69fa0, 0x1504d50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042119ad0, 0x14c46
60, 0xc0420f4000, 0xc042148200)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0
x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc042002a40, 0x14c4660, 0xc0420f
4000, 0xc042148200)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc04200d200, 0x14c4660, 0xc0420f4000, 0xc0421482
00)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x14c4660, 0xc0420f4000, 0xc042148
100)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +
0x31b
net/http.HandlerFunc.ServeHTTP(0xc042002a80, 0x14c4660, 0xc0420f4000, 0xc0421481
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x14c4660, 0xc0420f4000, 0xc04214810
0)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc042002aa0, 0x14c4660, 0xc0420f4000, 0xc0421481
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x150afe0
, 0x14c4660, 0xc0420f4000, 0xc042148100)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/securehead
er/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc042092b00, 0x14c4660, 0xc0420f4000, 0xc04214
8100)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc04215d540, 0x14c50a0, 0xc042252100)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
2018/03/03 18:53:41 http: panic serving 127.0.0.1:58704: runtime error: invalid
memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc04218c960)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69fa0, 0x1504d50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042119ad0, 0x14c46
60, 0xc0421882a0, 0xc0424e8100)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0
x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc042002a40, 0x14c4660, 0xc04218
82a0, 0xc0424e8100)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc04200d200, 0x14c4660, 0xc0421882a0, 0xc0424e81
00)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x14c4660, 0xc0421882a0, 0xc042148
300)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +
0x31b
net/http.HandlerFunc.ServeHTTP(0xc042002a80, 0x14c4660, 0xc0421882a0, 0xc0421483
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x14c4660, 0xc0421882a0, 0xc04214830
0)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc042002aa0, 0x14c4660, 0xc0421882a0, 0xc0421483
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x150afe0
, 0x14c4660, 0xc0421882a0, 0xc042148300)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/securehead
er/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc042092b00, 0x14c4660, 0xc0421882a0, 0xc04214
8300)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc04218c960, 0x14c50a0, 0xc0422523c0)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
2018/03/03 18:53:42 http: panic serving 127.0.0.1:58705: runtime error: invalid
memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc0424fa0a0)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69fa0, 0x1504d50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042119ad0, 0x14c46
60, 0xc0420f41c0, 0xc042148500)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0
x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc042002a40, 0x14c4660, 0xc0420f
41c0, 0xc042148500)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc04200d200, 0x14c4660, 0xc0420f41c0, 0xc0421485
00)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x14c4660, 0xc0420f41c0, 0xc042148
400)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +
0x31b
net/http.HandlerFunc.ServeHTTP(0xc042002a80, 0x14c4660, 0xc0420f41c0, 0xc0421484
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x14c4660, 0xc0420f41c0, 0xc04214840
0)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc042002aa0, 0x14c4660, 0xc0420f41c0, 0xc0421484
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x150afe0
, 0x14c4660, 0xc0420f41c0, 0xc042148400)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/securehead
er/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc042092b00, 0x14c4660, 0xc0420f41c0, 0xc04214
8400)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0424fa0a0, 0x14c50a0, 0xc042252480)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
2018/03/03 18:53:42 http: panic serving 127.0.0.1:58709: runtime error: invalid
memory address or nil pointer dereference
goroutine 48 [running]:
net/http.(*conn).serve.func1(0xc04218cbe0)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69fa0, 0x1504d50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042119ad0, 0x14c46
60, 0xc0420f4380, 0xc042148700)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0
x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc042002a40, 0x14c4660, 0xc0420f
4380, 0xc042148700)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc04200d200, 0x14c4660, 0xc0420f4380, 0xc0421487
00)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x14c4660, 0xc0420f4380, 0xc042148
600)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +
0x31b
net/http.HandlerFunc.ServeHTTP(0xc042002a80, 0x14c4660, 0xc0420f4380, 0xc0421486
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x14c4660, 0xc0420f4380, 0xc04214860
0)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc042002aa0, 0x14c4660, 0xc0420f4380, 0xc0421486
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x150afe0
, 0x14c4660, 0xc0420f4380, 0xc042148600)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/securehead
er/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc042092b00, 0x14c4660, 0xc0420f4380, 0xc04214
8600)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc04218cbe0, 0x14c50a0, 0xc042252780)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
2018/03/03 18:53:42 http: panic serving 127.0.0.1:58710: runtime error: invalid
memory address or nil pointer dereference
goroutine 24 [running]:
net/http.(*conn).serve.func1(0xc0424fa280)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69fa0, 0x1504d50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042119ad0, 0x14c46
60, 0xc042188540, 0xc0424e8300)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0
x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc042002a40, 0x14c4660, 0xc04218
8540, 0xc0424e8300)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc04200d200, 0x14c4660, 0xc042188540, 0xc0424e83
00)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x14c4660, 0xc042188540, 0xc0424e8
200)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +
0x31b
net/http.HandlerFunc.ServeHTTP(0xc042002a80, 0x14c4660, 0xc042188540, 0xc0424e82
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x14c4660, 0xc042188540, 0xc0424e820
0)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc042002aa0, 0x14c4660, 0xc042188540, 0xc0424e82
00)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x150afe0
, 0x14c4660, 0xc042188540, 0xc0424e8200)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/securehead
er/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc042092b00, 0x14c4660, 0xc042188540, 0xc0424e
8200)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc0424fa280, 0x14c50a0, 0xc04200ab40)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5

**Comment by wliyongfeng** [comment]
Please try again with the latest version or build the latest `master` branch.
