### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#399]
####  
OSX
Macbook Pro

adsl-172-10-0-144:~ user1$ sysctl kern.maxfiles
kern.maxfiles: 49152
adsl-172-10-0-144:~ user1$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 24576

#### Problem Description

2018/03/05 15:23:23 http: Accept error: accept tcp [::]:9888: accept: too many open files; retrying in 1s

I don't know what this is related to, is bytes closing the connections correctly?

**Comment by Paladz** [comment]
已有一个pr进行了修复，后续观察是否会重复出现
