### ISSUE TITLE
Unable to get property 'signing_instructions' of undefined or null reference

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#401]
#### Environment

- OS: Windows 10

#### Problem Description

Adding a Transaction -Control with Address

put in any address
select an asset which EXISTS
Enter an amount (which does not exceed the balance)
Click Submit Transaction - ERROR Displayed

The error is not clear that the address type is incorrect.

ERROR IN DOS:

[31mERRO[0m[62285] Loop tx's action                              [31maction index[0m=0 [31merror[0m="unknown address type"

<img width="831" alt="untitled" src="https://user-images.githubusercontent.com/2462930/37027173-7dd87768-2128-11e8-96d5-38b53f366d76.png">

**Comment by wliyongfeng** [comment]
I think it's fixed in the latest code. Please checkout the latest code, build and try it again.
