### ISSUE TITLE
test.sh bytom1 --- failed to dial peer

### ISSUE THREAD

**Issue by xiaolinzguo** [Bytom/bytom#41]
#### Environment

- OS: Windows 7

#### Problem Description

After the command "test.sh bytom1" command was input, one separate cmd window was popped up with the output below, but the highlighted error was reported.

I[10-01|07:01:13.740] Starting EventSwitch                         module=types impl=EventSwitch
--------------block:&{{0 0 {0 0 0 0} 0 {{0 0 0 0} {0 0 0 0}} 0 0} []}at=log.go:129 t=2017-10-01T07:01:13.741317400Z message="bytom's Height:14."
--------------block:&{{0 0 {0 0 0 0} 0 {{0 0 0 0} {0 0 0 0}} 0 0} []}I[10-01|07:01:13.884] Starting Node                                module=node_p2p impl=Node
I[10-01|07:01:13.884] Local listener                               module=p2p ip=127.0.0.1 port=3333
I[10-01|07:01:13.931] Starting DefaultListener                     module=p2p impl=Listener(@192.168.1.4:3333)
I[10-01|07:01:13.931] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[10-01|07:01:13.931] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[10-01|07:01:13.932] Starting RPC HTTP server on tcp socket 0.0.0.0:46658 module=rpc-server
I[10-01|07:01:13.932] Started node                                 module=main nodeInfo="NodeInfo{pk: PubKeyEd25519{BF4E0C509CC8887EC6986389A4E937C498762C4004D40F89C168C0D28CA76BAC}, moniker: anonymous, network: chain0 [remote , listen 192.168.1.4:3333], version: 0.1.0 ([wire_version=0.6.2 p2p_version=0.5.0 rpc_addr=tcp://0.0.0.0:46658])}"
I[10-01|07:01:14.530] Dialing peer                                 module=p2p address=127.0.0.1:3332
_**E[10-01|07:01:15.531] Failed to dial peer                          module=p2p address=127.0.0.1:3332 error="Error creating peer: dial tcp 127.0.0.1:3332: connectex: No connection could be made because the target machine actively refused it."
E[10-01|07:01:15.533] Error dialing seed                           module=p2p error="Error creating peer: dial tcp 127.0.0.1:3332: connectex: No connection could be made because the target machine actively refused it."**_
I[10-01|07:01:23.932] start to mining                              module=blockcain
finish commit block heigh 15, # of tx 1
finish commit block heigh 16, # of tx 1
finish commit block heigh 17, # of tx 1
finish commit block heigh 18, # of tx 1
finish commit block heigh 19, # of tx 1
finish commit block heigh 20, # of tx 1

**Comment by gguoss** [comment]
Thank you very much for your feedback. Do you have any more detailed steps?

**Comment by gguoss** [comment]
We haven't test it in Windows OS yet, but it is okay in Mac and Ubuntu. We will solve this problem few days latter. Thank you very much for feedback.

**Comment by zhouyasong** [comment]
hello,I have tested it on windows7 and windows10 OS,but  I didn't see that happening.
So this may be accidental events...
Then,I tested it on my ubuntu16.04 OS ,it happened...
And then,I got the bytom code in windows10 to the ubuntu16.04 and recompile it, and it works...
Next, I cloned the bytom code from github again,and it works again...
Then I guess whether the network or port is occupied,But the testing problem that passes through a variety of networks does not lie in the network, nor does the port.
So this may be accidental events because of different computers...

**Comment by gguoss** [comment]
Because address=127.0.0.1:3332's bytom node not run ok.  log level is too high (Error), should be (Info).
