### ISSUE TITLE
Block height

### ISSUE THREAD

**Issue by xiaolinzguo** [Bytom/bytom#42]
#### Environment

- OS: Windows 7

#### Problem Description

One question and One suggestion
1. How long will one new block be generated? In my PC, it is 1s, 2s, 7s, sometimes it is 29 seconds.
2. Is it better to say "finish commit block height 847, # of tx 1"? "block height" not "block heigh".

**Comment by gguoss** [comment]
1.The difficulty adjust algorithm is still being tested, The release speed of this version is really very uncertain. Furthermore, our artificial intelligence mining algorithm is private branch, now not open.
2. Thank you for your advice, we will accept it.

**Comment by xiaolinzguo** [comment]
Thanks for your response.
