### ISSUE TITLE
Could not perform UPNP discover

### ISSUE THREAD

**Issue by RockerFlower** [Bytom/bytom#46]
#### Environment

- OS: macOS High Sierra

#### Problem Description

When I run `./bytom node --home ./.bytom`, the output says: 

    Starting EventSwitch                         module=types impl=EventSwitch
    --------------block:&{{0 0 {0 0 0 0} 0 {{0 0 0 0} {0 0 0 0}} 0 0} []}at=log.go:129 t=2017-10-09T09:58:22.280866000Z message="bytom's Height:225."
    --------------block:&{{0 0 {0 0 0 0} 0 {{0 0 0 0} {0 0 0 0}} 0 0} []}
    I[10-09|09:58:22.293] Starting Node                                module=node_p2p impl=Node
    I[10-09|09:58:22.293] Local listener                               module=p2p ip=:: port=46656
    I[10-09|09:58:22.293] Getting UPNP external address                module=p2p 

    I[10-09|09:58:25.295] Could not perform UPNP discover              module=p2p error="write udp4 0.0.0.0:63207->239.255.255.250:1900: i/o timeout"

    I[10-09|09:58:25.296] Starting DefaultListener                     module=p2p impl=Listener(@10.8.200.50:46656)
    I[10-09|09:58:25.296] Starting P2P Switch                          module=p2p impl="P2P Switch"
    I[10-09|09:58:25.296] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
    I[10-09|09:58:25.296] Starting RPC HTTP server on tcp socket 0.0.0.0:46657 module=rpc-server 
    I[10-09|09:58:25.296] Started node                                 module=main nodeInfo="NodeInfo{pk: PubKeyEd25519{07DFAE00D7943BC718082A8C9CE19A3F9B56B43070EAAABE55AE23EEF622FDC3}, moniker: anonymous, network: chain0 [remote , listen 10.8.200.50:46656], version: 0.1.0 ([wire_version=0.6.2 p2p_version=0.5.0 rpc_addr=tcp://0.0.0.0:46657])}"
    I[10-09|09:58:35.302] start to mining                              module=blockchain 
    finish commit block heigh 226, # of tx 1 
    finish commit block heigh 227, # of tx 1 
    ...

and then create account:

> $ ./bytomcli create-account wong
> xprv:f074d5684d69469d0cbd7759c92fe74f2b95ffa39b7537a18ea7954c8e205d7e710228776d389c9d2bfb4519cbafd1727b121b6a18d2d3b66cd69bb871db5e34
> xpub:60fafb3376025ab344e8d732e25915d48ad8b3b1251ad611cd7fca33835dd335710228776d389c9d2bfb4519cbafd1727b121b6a18d2d3b66cd69bb871db5e34`
> **responses:{  [] 0 <nil>}**
> **account id:**

Is there anything wrong?

**Comment by gguoss** [comment]
Follow your steps, and the results are consistent with expectations. When you run bytomcli, you need to run Bytom at the same time. Because bytomcli calls the function of Bytom remotely.

![1](https://user-images.githubusercontent.com/9285062/31366015-77b029ee-ada1-11e7-86c7-4caf378dfa96.png)

**Comment by gguoss** [comment]
Could not perform UPNP discover.  We're tracking the problem.

**Comment by RockerFlower** [comment]
Thanks. I just started learning the block chain.

**Comment by gguoss** [comment]
Default p2p.skip is false. Because you start a single node, and our global test network is not configured with UPnP.
You can run as follows:
``` bash
./bytomd node --p2p.skip_upnp
```
