### ISSUE TITLE
建议转账的时候，amount 最好进行一下正则校验

### ISSUE THREAD

**Issue by zkaip** [Bytom/bytom#489]
#### Environment

- OS: MacOS High Sierra Version 10.13.3

#### Problem Description

现在填写数量，没有进行正则校验，随便怎样输入都可以，会导致一些问题，建议前端直接校验一下

**Comment by wliyongfeng** [comment]
感谢你的建议，目前前端也在不断优化。

**Comment by Blockmeta** [comment]
done
