### ISSUE TITLE
Key reload question

### ISSUE THREAD

**Issue by Leekailklk** [Bytom/bytom#493]
0.4 version Environment

- OS: win7 64

#### Problem Description

Delete some key files in keystore folder, Click the key botton on dashboard. The key was not updated. Click the refresh button on browser. The key was update. Copy back the key files into keystore folder. Click the key button, the keys get updated.

**Comment by wliyongfeng** [comment]
fixed https://github.com/Bytom/dashboard/commit/cf82a65be5bb6d45a0188dc6af2ea6920d2d3005
