### ISSUE TITLE
docker config is not functional

### ISSUE THREAD

**Issue by kbuggenhout** [Bytom/bytom#498]
#### Environment

- OS: CentOS 7.4 docker

#### Problem Description

dockerfile does not work:
 docker build -t bytom .
Sending build context to Docker daemon 9.359 GB
Step 1 : FROM golang:1.9-alpine as builder
Error parsing reference: "golang:1.9-alpine as builder" is not a valid repository/tag

clean docker images, create dockerfile, then run docker build -t bytom ./dockerfile

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
