### ISSUE TITLE
There are no block with given hash

### ISSUE THREAD

**Issue by starit** [Bytom/bytom#500]
#### Environment

- OS: macOS

#### Problem Description

When I try to run testnet node with command `./bytomd node --mining`, it shows:
```
Failed to create chain structure: There are no block with given hash 808678066fd06b12c33d0628e8ececfcc5f89143acec55aae5eb9c6337000000
```

**Comment by wliyongfeng** [comment]
Please do following steps to check whether the error reproduce:   
1.  delete the `.bytomd` folder under the `[$GOPATH]/src/github.com/bytom/cmd/bytomd` directory.
2. `./bytomd init --chain_id testnet`
3. `./bytomd node --mining`
