### ISSUE TITLE
高频发送交易报错 all gas credit has been spend: invalid block

### ISSUE THREAD

**Issue by yahtoo** [Bytom/bytom#524]
#### Environment

- OS: ???

#### Problem Description

交易发送脚本
#!/bin/sh
get_data() {
        cat << EOF
        $1
EOF
}
while true
do
#spend 60000000000 BTM from default to alice
aliceaddress=`./bytomcli create-account-receiver recovery_0 | sed -n '3p' | cut -d ":" -f 2 | cut -d "\"" -f 2`

echo "*** spend asset 10 BTM from default to alice"
viewcmd="./bytomcli build-transaction -t spend recovery_0 btm 10 --alias -r $aliceaddress"
#echo $viewcmd
spend=`eval $viewcmd`

spend_tmpl=`echo "$spend" | grep "raw_transaction" | tr -d '\n'`
txid=$(./bytomcli sign-submit-transaction -p 123456 "$(get_data "$spend_tmpl")")
echo $txid
sleep 0.01
done
错误：
time="2018-04-03T20:04:04+08:00" level=error msg="blockKeeper fail process block validity of transaction 1 of 8: checking result 0: checking output source: checking value source: all gas credit has been spend: invalid block" hash: ="{9321148780494535071 7776489163451272160 1454882198598169320 813716584951618909}"

**Comment by Paladz** [comment]
判断是gas手续太高了，调低后重试
