### ISSUE TITLE
a dashboard layout bug

### ISSUE THREAD

**Issue by HAOYUatHZ** [Bytom/bytom#526]
#### Environment
- OS:  ubuntu 17.10 64-bit
- Browser: chrome 65.0.3325.181 (64-bit)
- Resolution: 1920*1080

#### Problem Description
The pic paints thousands of words.

![screenshot from 2018-04-03 20-34-15_meitu_1](https://user-images.githubusercontent.com/37070449/38249949-fcd722c2-377f-11e8-82b0-cb13b3a3f7c8.png)

**Comment by wliyongfeng** [comment]
fixed https://github.com/Bytom/dashboard/pull/12/files
