### ISSUE TITLE
Synchronize the nodes problem

### ISSUE THREAD

**Issue by zhangbinbin625** [Bytom/bytom#566]
#### Environment

- OS:windows 7 64

#### Problem Description

bytom-0.4.2-windows_amd64.zip  

How to run this, or I want to download a full node wallet how to download

**Comment by zhangbinbin625** [comment]
Environment
OS:windows 7 64
Problem Description
bytom-0.4.2-windows_amd64.zip

How to run this, or I want to download a full node wallet how to download

**Comment by Paladz** [comment]
Plz download 0.4.6 from the github and retry
