### ISSUE TITLE
##Can not syncing when computer's time changed

### ISSUE THREAD

**Issue by Leekailklk** [Bytom/bytom#580]
#### Environment

- OS: win7 64 (bytom 0.4.3 version)

#### Problem Description

  * When your computer's time changed to some early time,The block syncing will fail.(For example,Now your computer's time show "21:59:00",change your computer's time from "21:59:00" to "09:59:00" .Then the bytom  block syncing will fail.)When this kind failure happened, Even you stop the bytom and restart the bytomd command to start node,The syncing will still fail.
  * 当改变电脑的系统时间到一个比当前时间较早的时间，同步会失败.(例如，现在的电脑时间是“21:59:00”，改变系统时间从“21:59:00”到“09:59:00”，比原链同步会失败）。当同步失败发生，即使停止同步重新启动节点，同步仍然会失败。
  

####In conclusion
If your computer's time is early than the exactly time(The reasons why the time is different are complex, Maybe traveling in different country,maybe your computer use double system having different time setting). The following failure will happened.

* If you are first time start bytom node,The block syncing will not start.
* If you already synchronized some blocks before,The syncing will not continue. Even you correcte your time, The syncing still can not continue.

####结论
如果你的电脑系统时间早于实际时间（时间不一致的原因可能很复杂，也许你在不同的国家旅行，也许你的电脑是双系统有不同的时间设置）下面的失败将发生。

* 如果你是第一次运行比原链节点，区块同步不会开始。
* 如果你之前已经同步了一些区块，现在同步将无法继续进行。即使你更正了你的时间，同步仍然无法进行。

**Comment by yahtoo** [comment]
当改变系统时间，挖出来的块会被视为恶意块，节点会被视为恶意节点被网络断开，挖矿前要同步系统时间，保证时间正确。

**Comment by Blockmeta** [comment]
You have to adjust your local time while syncing blockchain
