### ISSUE TITLE
bytomd-windows.exe init --chain_id testnet 执行两次，bytomd-windows.exe node --mining执行不成功

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#588]
#### Environment

- OS: windows

#### Problem Description

bytomd-windows.exe init --chain_id testnet 执行两次，bytomd-windows.exe node --mining执行不成功

1、执行初始化bytomd-windows.exe init 成功。
2、再执行一次初始化，bytomd-windows.exe init --chain_id testnet，提示已经执行。
3、执行node ， bytomd-windows.exe node --mining 不成功。

**Comment by shengling2008** [comment]
目前新版本测试没有这个问题，你测试的版本是多少呢？

**Comment by shengling2008** [comment]
@VictorWei000 当前的版本测试没有这样的问题

**Comment by ChrisLinn** [comment]
if u cant provide with more details  we have to close this issue

**Comment by VictorWei000** [comment]
已经换了图形界面，关闭此缺陷
