### ISSUE TITLE
执行命令后，弹出的页面是空白的

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#589]
#### Environment

- OS: windows

#### Problem Description

执行了命令后，控制台页面是空白的。

1. 执行了两句命令： bytomd-windows.exe init --chain_id testnet  
> bytomd-windows.exe node --mining
2. 自动打开了页面http://127.0.0.1:9888/dashboard/， 不过是空白的。

**Comment by MartinBTM** [comment]
是ie浏览器么？

**Comment by HAOYUatHZ** [comment]
whatz ur default browser

**Comment by MartinBTM** [comment]
It maybe the newer browser
we always use chorme
the old IEs are Proved can not show whole thing
 
------------------ Original ------------------

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
