### ISSUE TITLE
windows平台，不能load the keys

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#590]
#### Environment

- OS: windows

#### Problem Description

1、 执行了bytomd-windows.exe init --chain_id testnet  
> bytomd-windows.exe node --mining
2、显示不能load the keys. 见附件

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
