### ISSUE TITLE
【外部测试】OS X Build and Install 安装命令

### ISSUE THREAD

**Issue by liuxue5213** [Bytom/bytom#595]
#### Environment

- OS: Mac OS X

#### Problem Description

cd bytom-0.4.5-darwin_amd64 
./bytom-0.4.5-darwin_amd64 init --chain_id testnet  
./bytom-0.4.5-darwin_amd64 --mining  #提示没有这个命令

./bytom-0.4.5-darwin_amd64  node --mining  #查看其它平台安装命令 发现这里应该是少写了node

**Comment by MartinBTM** [comment]
已修改
