### ISSUE TITLE
[外部测试]  unknown action type "control_account" on action 2: bad action type

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#607]
#### Environment

- OS: OSX
- Code branch: `dev`

#### Problem Description

When run command:

```
./bytomcli build-transaction -t issue freewind BTM 10000 --alias
```

It prints:

```
ERROR 2018/04/12 15:12:08 unknown action type "control_account" on action 2: bad action type
```

Reason:

<https://github.com/Bytom/bytom/blob/f72ac848a2d25d5c8a91188dd8a3f1ef89f5793f/cmd/bytomcli/commands/transaction.go#L55-L60>

The actions have `control_account` type, but which is not handled in <https://github.com/Bytom/bytom/blob/6e130176e5ad7826ea92f805960f03ad877a4dc1/api/transact.go#L21-L41>

**Comment by Paladz** [comment]
应该已修复， 请重新检测。 这个issue有价值，请联系内测群管理员领取找bug奖励

**Comment by MartinBTM** [comment]
收到
