### ISSUE TITLE
【外部测试】0.4.6版mac环境下提示Peer is on a different network

### ISSUE THREAD

**Issue by souankou** [Bytom/bytom#611]
#### Environment

- OS: 10.13.3 (17D47)

#### Problem Description
![wechatimg535](https://user-images.githubusercontent.com/38316319/38670283-ec9bd9aa-3e7a-11e8-8473-e55b36137d8a.jpeg)

[

](url)

**Comment by shlj** [comment]
因为 `60.186.21.11`这个ip `./bytomd init --chain_id`使用了`mainnet`

**Comment by Paladz** [comment]
这个是别的节点启动错了
