### ISSUE TITLE
【外部测试】ERROR: unknown flag: --wallet.enable

### ISSUE THREAD

**Issue by zhangsj** [Bytom/bytom#612]
#### Environment

- OS: ubuntu 14.04 64bit

#### Problem Description

**下载gz包  解压
执行
ip-172-30-0-4:~/softwares$  ./bytomd init --chain_id testnet
ip-172-30-0-4:~/softwares$ ls
authentication.py            bytomcli        gateone.tar.gz               miner-linux_amd64
bytom-0.4.6-linux_amd64.md5  bytomd          go                           nginx
bytom-0.4.6-linux_amd64.tgz  GateOne-master  go1.10.1.linux-amd64.tar.gz  server.py
ip-172-30-0-4:~/softwares$ ./bytomd node --wallet.enable
ERROR: unknown flag: --wallet.enable

源码部署同样

**Comment by shlj** [comment]
默认是开启的 直接 `./bytomd node  --mining` @zhangsj

**Comment by zhangsj** [comment]
那 挖到的btm 在哪个账号呢？
