### ISSUE TITLE
【外部测试】建议init时手动设置default账户密码（Set password for default account manually when init）

### ISSUE THREAD

**Issue by Clarenous** [Bytom/bytom#615]
#### Environment

- OS: Ubuntu 16.04, Windows 10 64-bit

#### Problem Description

目前，初始化时，default账户的密码均被自动设置为123456，可能存在一定的安全隐患。

Currently, the password for default account is set to 123456 automatically, which may increase risk of being attack.

建议在初始化客户端时增加启动参数，要求用户自行设置密码，例如 `./bytomd init chain_id testnet default_passwd <user_typed password>`

May add init options like `./bytomd init chain_id testnet default_passwd <user_typed password>` , ask for user typed password.

**Comment by Paladz** [comment]
会添加一个改密码功能

**Comment by Blockmeta** [comment]
enhanced at version 1.0.2
