### ISSUE TITLE
【外部测试】Dashboard页面内新建交易时的用户体验问题

### ISSUE THREAD

**Issue by Clarenous** [Bytom/bytom#619]
#### Environment

- OS: Windows 10 64-bit, Chrome Browser

##### 复现步骤 #####

1. 打开Dashboard页面，进入交易界面，点击新建。

2. 输入交易信息，例如从default账户转账10 BTM 到某地址，Gas选择标准(0.2BTM)。

3. 先输入错误的密码并提交交易，得到错误提示。

4. 再次输入正确的密码，交易依然无法被发送，且得到错误提示如下。

> Error submitting form
> errors occurred in one or more actions-<action index 0: reserving utxos: reservation found outputs already reserved>

##### 问题产生的原因 #####

从微信测试群中@James 处了解到，“这个错误是因为钱包有个utxo预留机制防止双花，之前有一笔交易发出去，但是密码输入错误。等n分钟钱包会自动释放这个锁。”

##### 改善建议 #####

用户可能失误输错密码，并且对于这类错误信息难以辨别，带来不好的使用体验。

可以加入便于阅读的错误提示，例如"交易已因安全问题被锁定，请等待X分钟后重试"、"交易已发送，请勿重复提交"等。

**Comment by wliyongfeng** [comment]
Good. But, currently we have higher priority issues while we will improve the UE after that.

**Comment by Paladz** [comment]
已更新，请尝试最新的版本
