### ISSUE TITLE
新建account后无法查询到账户对应的address

### ISSUE THREAD

**Issue by dikeny** [Bytom/bytom#621]
#### Environment

- OS: window7,64位

#### Problem Description
新建account后查不到这个account的address，导致我无法接收他人的转账

新建account后就可以查询到这个account的address地址，并且可以接受他人的转账

1.在地址 http://127.0.0.1:9888/dashboard/keys 创建了一个秘钥
2.在 地址 http://127.0.0.1:9888/dashboard/accounts  中点击“创建”，进入创建账户页面
3.在创建账户页面填写Alias，并选择使用步骤1中创建的私钥，并提交，账户创建成功
4.在 http://127.0.0.1:9888/dashboard/accounts 点击查看步骤3中创建的账户详情，发现账户里边无address信息

**Comment by Lbqds** [comment]
创建新账户时不会自动创建地址，在账户详情页面点击右上角create address创建新的地址。
