### ISSUE TITLE
【外部测试】Web browser can not open dashboard correctly.

### ISSUE THREAD

**Issue by Leekailklk** [Bytom/bytom#623]
#### Environment

- OS: Win7 64(bytom0.4.6version)

#### Problem Description

* IE&360 web browser can not open the dashboard.
* 搜狗browser can not show the balances, It shows "LOADING" .
* 搜狗browser have no chinese中文show显示.
* Chrome browser works without any problem.

**Comment by wliyongfeng** [comment]
Currently we only support Chrome. Please ignore other browsers for recent test.
