### ISSUE TITLE
点对点网络连接总是超时

### ISSUE THREAD

**Issue by LeeNoOne** [Bytom/bytom#627]
#### Environment

win7 32位

- OS: ???

#### Problem Description

peer创建连接超时

![_20180413113437](https://user-images.githubusercontent.com/22511134/38715602-b61c2f4e-3f0e-11e8-80da-ae4487f3c7ba.png)

**Comment by HAOYUatHZ** [comment]
you need to clean up the `.bytom/` directory

and use newer release (>0.4.6)
