### ISSUE TITLE
连接网络报文件丢失错误

### ISSUE THREAD

**Issue by LeeNoOne** [Bytom/bytom#628]
#### Environment

联想笔记本电脑
- OS: ???
win7 32位
#### Problem Description
连接网络报文件丢失错误

![_20180413113634](https://user-images.githubusercontent.com/22511134/38715640-f13e11dc-3f0e-11e8-8631-ba1a13c3a11d.png)

**Comment by shengling2008** [comment]
这个是key的目录，新启动的节点开始是不存在，等节点启动后，会创建
