### ISSUE TITLE
创建一个空格作为账户名

### ISSUE THREAD

**Issue by shlj** [Bytom/bytom#633]
1.页面中创建一个` `(空格)作为账户名的account
2.进入此账户详情
3.创建arrdess失败
![image](https://user-images.githubusercontent.com/12427048/38729231-da48d0e4-3f44-11e8-868b-360926f60b19.png)
![image](https://user-images.githubusercontent.com/12427048/38729248-ebdb8c0c-3f44-11e8-87cd-49c6458a7713.png)

建议对相关创建input框做特殊符号的校验，比如只能使用(字母/数字/_/-)

**Comment by huwenchao** [comment]
看了下代码，alias 字段会做转小写和trim操作

```
normalizedAlias := strings.ToLower(strings.TrimSpace(alias))
```

但是API层面和控制台页面都没有任何提示，会让用户感到困惑。建议如上面所说，明确 alias 规范，并在后端加上对应检查，前端页面加上相应提示和校验。

**Comment by Paladz** [comment]
Dashboard fixed this issue, plz download the newest version and re-try
