### ISSUE TITLE
dashboard javascript error

### ISSUE THREAD

**Issue by jerry6290** [Bytom/bytom#639]
#### Environment

- OS: mac OSX 10.12.2
- 浏览器：62.0.3202.94（正式版本） 

#### Problem Description

![btm-js-error](https://user-images.githubusercontent.com/3364638/38739360-4bcc8414-3f67-11e8-8f19-ad6d4c0521ef.png)

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
