### ISSUE TITLE
【外部测试】利用build-transaction构建”issue asset交易“失败

### ISSUE THREAD

**Issue by Clarenous** [Bytom/bytom#641]
#### Environment

- OS: Ubuntu 16.04, Bytomcli v0.4.6-e087c28b linux/amd64
- OS: Windows 10 64-bit, Bytomcli v0.4.6-f7709ca7 windows/amd64

##### 问题摘要 #####

利用 `./bytomcli build-transaction` 构建issue asset类型的交易时，出现错误.

##### 复现步骤 #####

1. 按照[README.MD](https://github.com/Bytom/bytom/blob/dev/README.md)中的指引，创建镍金属资产Nickel , 输入的xpub是default账户的xpub

```
$ ./bytomcli create-asset nickel 6b340f52b8c13c2433e5a1b02ec95de7150281928fe8d1f880f1a7acbca2fabccc417de14c0db173c0aae7e16134027afd6c930a085b0b660518bea4a0557555
{
  "alias": "NICKEL",
  "definition": {},
  "id": "70c79c54d64d5e40dfa61b1cba697d0de6938029986671674b439d76777a2ebb",
  "issuance_program": "ae20f717c975ecb570ab0f7366334cfc1bc77c0af5cf17a57453ca1d9462c49818755151ad",
  "keys": [
    {
      "asset_derivation_path": [
        "000100000000000000"
      ],
      "asset_pubkey": "f717c975ecb570ab0f7366334cfc1bc77c0af5cf17a57453ca1d9462c49818750bd2fcff6c6975a2aa77e660c59ccfc560eca1f59edceedefab1ea7901d59e14",
      "root_xpub": "6b340f52b8c13c2433e5a1b02ec95de7150281928fe8d1f880f1a7acbca2fabccc417de14c0db173c0aae7e16134027afd6c930a085b0b660518bea4a0557555"
    }
  ],
  "quorum": 1,
  "tags": {}
}
```

2. 仿照[README.MD](https://github.com/Bytom/bytom/blob/dev/README.md)中的示例`./bytomcli build-transaction -t issue alice gold 10000 --alias`，输入命令，为alice(已在节点创建该账户)发10000个nickel，得到错误提示如下：

```
$ ./bytomcli build-transaction -t issue alice nickel 10000 --alias
ERROR 2018/04/14 01:11:36 errors occurred in one or more actions-<action index 0: reserving utxos: can't match enough valid utxos><action index 2: required field is missing>
````

改为向default账户issue，也得到相同的错误输出.

##### 原因猜测  #####

从错误输出的`reserving utxos: can't match enough valid utxos`来看，似乎是default账户Nickel余额不足导致了错误。

如果是这样，应该如何在创建资产时为账户初始化一定量的资产？目前还未找到相关的资料。

但是，在[issue 638](https://github.com/Bytom/bytom/issues/638)中已经有人能够“节点A创建资产，并发给节点B”。

希望能够提供更多与资产创建(create-asset)相关的资料。

**Comment by Lbqds** [comment]
build-transaction现在需要加一个地址参数
```
./bytomcli build-transaction -t issue Alice nikel 1000 -a <address> --alias
```
地址可通过`bytomcli list-addresses`或`bytomcli create-account-receiver`获取

稍后会更新README

**Comment by Clarenous** [comment]
增加地址参数后，可以构建交易了。不过在余额确认到账后，无法用txid查询到具体的交易，应该遇到了与[issue 638](https://github.com/Bytom/bytom/issues/638)相同的问题。

**Comment by Lbqds** [comment]
README已更新，请参考[sending transaction#issue](https://github.com/Bytom/bytom#issue)
