### ISSUE TITLE
bytomd运行中，CPU占用大，导出密钥超级慢

### ISSUE THREAD

**Issue by jidongg** [Bytom/bytom#642]
#### Environment

- OS: WINDOWS10

**Comment by HAOYUatHZ** [comment]
if u r mining, itz quite reasonable that the cpu usage is pretty high, and u may even wanna make full use of the cpu!

it will be hard to understand if you wanna mine a block as quickly as possible while you wanna keep the usage low.

however this shouldn't be a problem as the exporting is super faster and sorry I cannot reproduce ur problem, and i believe you won;t face this again as the upcoming release is based on faster codes.
