### ISSUE TITLE
win8 R2 云服务器启动项目  访问需要token  自己创建token失败 bytomcli-windows_amd64.exe create-access-token tokenname

### ISSUE THREAD

**Issue by xq463364973** [Bytom/bytom#649]
#### Environment

- OS: ???

**Comment by HAOYUatHZ** [comment]
what's the eorror message

**Comment by HAOYUatHZ** [comment]
whatz more,  the bytomd needs being running

**Comment by xq463364973** [comment]
Thank you for your reply.
Eorror message:Unable to connect to the bytomd.
I'm sure it's on the same server.
Execution order:
1.bytomcli-windows_amd64.exe create-access-token tokenname
2.bytomd-windows_amd64.exe init --chain_id testnet
3.bytomd-windows_amd64.exe node --mining
