### ISSUE TITLE
自己创建的密钥 无法导出  default的可以导出

### ISSUE THREAD

**Issue by xq463364973** [Bytom/bytom#650]
#### Environment

- OS: ???

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me

**Comment by shengling2008** [comment]
看最新的版本的，现在有备份钱包 和 恢复的功能

**Comment by xq463364973** [comment]
ok! thanks
