### ISSUE TITLE
win7 32系统0.4.6版本不能通过128块

### ISSUE THREAD

**Issue by xiaobaoxb** [Bytom/bytom#653]
#### Environment

- OS: ???

**Comment by HAOYUatHZ** [comment]
let me try to reproduce it first

**Comment by HAOYUatHZ** [comment]
probably bacause of the CPU usage

don't start mining fore the sync done

**Comment by HAOYUatHZ** [comment]
I've reproduced the error

and i believe there's something wrong on 32-bit os, no matter win/linux

**Comment by HAOYUatHZ** [comment]
solved #725
