### ISSUE TITLE
将两个.bytomd文件夹覆盖合并后会有两个同名电秘钥alias，多个合并可能更多

### ISSUE THREAD

**Issue by xiaobaoxb** [Bytom/bytom#655]
#### Environment

- OS: ???

#### Problem Description
将两个.bytomd文件夹合并后有两个同名电秘钥，在建立资产和账户选择秘钥时是两个同名秘钥

**Comment by Paladz** [comment]
老哥，不要做这种合并的操作，很危险。你这个相当于篡改数据库然后造成上层显示错误了
