### ISSUE TITLE
[外部测试]API&dashboard操作验证不统一

### ISSUE THREAD

**Issue by shlj** [Bytom/bytom#666]
dashboard密钥的重置密码功能  对应API /reset-key-password
dashboard做了新密码限制
![image](https://user-images.githubusercontent.com/12427048/38802034-faae623a-419d-11e8-9a75-286bbf367aa5.png)
对应API接口未做
![image](https://user-images.githubusercontent.com/12427048/38802070-16e449ce-419e-11e8-9634-515e1d8b36ba.png)

其他api
create-key

**Comment by Paladz** [comment]
新版本上dashboard新建key和改密码都加了限制了
