### ISSUE TITLE
区块同步到129时报异常块，并停止了区块同步

### ISSUE THREAD

**Issue by dominolu** [Bytom/bytom#667]
64位linux
数据重置后，开始同步区块，刚开始提示节点无法链接，过几分钟过开始同步区块
但当同步到129块时，提示，区块异常，系统同步状态变为false
![image](https://user-images.githubusercontent.com/5698142/38806268-4ead1068-41ab-11e8-8ed2-883d565a6a72.png)
![image](https://user-images.githubusercontent.com/5698142/38806277-5612384c-41ab-11e8-9342-0f22f37dc4ff.png)

**Comment by HAOYUatHZ** [comment]
32bit OS?

**Comment by shengling2008** [comment]
@dominolu 是怎么做数据重置的？

**Comment by HAOYUatHZ** [comment]
this bug has been fixed in PR #725
