### ISSUE TITLE
key index boundaries check

### ISSUE THREAD

**Issue by HAOYUatHZ** [Bytom/bytom#699]
> 钱包里，当创建用户时，如果KEYS选6，而此时钱包只有4个key，实际创建的新账户里的xpub数目，就是选择的key的数目。而与选择的6无关。

**Comment by huwenchao** [comment]
看了下 [API-Refernce](https://github.com/Bytom/bytom/wiki/API-Reference#create-account)，接口里并没有 keys 这个字段，后端接口里也是判断 xpub 的长度和 QUORUM，所以这个应该是需要修改前端的检查？
