### ISSUE TITLE
Unable to PASTE into Address field

### ISSUE THREAD

**Issue by cwiles** [Bytom/bytom#703]
#### Environment

-OSX

#### Problem Description

The PASTE is disabled on the address field.  It should be enabled in order to prevent user error
<img width="862" alt="untitled 2" src="https://user-images.githubusercontent.com/2462930/38933961-55f05cb4-4312-11e8-87c3-e0575fc0176c.png">

**Comment by wliyongfeng** [comment]
Fixed in latest version.

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me

**Comment by cwiles** [comment]
I don’t understand?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
