### ISSUE TITLE
代码多处valid拼错，api返回结果时造成困扰

### ISSUE THREAD

**Issue by leifjacky** [Bytom/bytom#704]
https://github.com/Bytom/bytom/blob/9d3dab4b0798d45dfc8b087cace16da812c8986e/api/accounts.go#L42

**Comment by Blockmeta** [comment]
fixed #708

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me
