### ISSUE TITLE
图形化界面中的内容不能复制粘贴

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#709]
#### Environment

- OS: windows

#### Problem Description

图形化界面中的内容不能复制粘贴，只能用快捷键，这样能不方便。

**Comment by FataliBud** [comment]
同样的问题，MacOs也是无法复制粘贴的，也不能使用快捷键。是不是处理Windows的Win键和Mac的Cmd键有问题？

**Comment by wliyongfeng** [comment]
Fixed in latest version.
