### ISSUE TITLE
图形化页面，已经创建了账户，不能交易btm

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#710]
#### Environment

- OS: windows

#### Problem Description

已经创建了btm账户，地址：  bm1qxmeygn05nlxswtr26q4nxs054fzukqs8mkj43z
转入不了btm

**Comment by shengling2008** [comment]
这两个值currentBlock、highestBlock是多少？如果要看到账户上的btm，要等同步到发送交易时链的高度

**Comment by ZhitingLin** [comment]
应该是Account Alias 有空格活着其他符号不能识别。最新版本已经修复了这个bug。
