### ISSUE TITLE
使用图形化界面的钱包，不挖矿，cpu占用率达到70%以上

### ISSUE THREAD

**Issue by VictorWei000** [Bytom/bytom#711]
#### Environment

- OS: windows

#### Problem Description

使用图形化界面，不开启挖矿，cpu占有率仍然达到了70%以上。

**Comment by HAOYUatHZ** [comment]
syncing?

**Comment by Blockmeta** [comment]
系统配置能否提供一下

**Comment by HAOYUatHZ** [comment]
syncing?
-----------
在同步时占用这么高还是同步完了还占用这么高？

**Comment by HAOYUatHZ** [comment]
现在 一边同步就是这么高
simd版 则只有 30～50%
