### ISSUE TITLE
转出BTM提示异常

### ISSUE THREAD

**Issue by souankou** [Bytom/bytom#717]
#### Environment

- OS: mac
![wechatimg2667](https://user-images.githubusercontent.com/38316319/38980670-08b5b8e8-43f0-11e8-8b76-3f9aad9c3443.jpeg)

#### Problem Description

Error submitting form
tx rejected: checking result 0: checking output source: checking value source: checking gas input: checking control program: data stack underflow [prog 76ab14230a758275cdacb926f9d07719b89bfb9a9bfe7188ae7cac = DUP HASH160 0x230a758275cdacb926f9d07719b89bfb9a9bfe71 EQUALVERIFY TXSIGHASH SWAP CHECKSIG; args f1b4b937470dde120c1600613852d1b9baa20e441bf1a1ade6bd70406a08bebb]

**Comment by FataliBud** [comment]
是不是不能转出啊

**Comment by LzyDou** [comment]
我也遇到了同样的问题

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
