### ISSUE TITLE
mac 10.13.3 (17D47)系统，挖矿进程自动kill

### ISSUE THREAD

**Issue by souankou** [Bytom/bytom#718]
![1524128267347](https://user-images.githubusercontent.com/38316319/38981807-d89ab71e-43f2-11e8-9862-cb07746306bb.jpg)
#### Environment

- OS: mac 10.13.3 (17D47)

**Comment by HAOYUatHZ** [comment]
fix in 0ffbae451e1eadd6b3d016fe015a0893f04f1435
