### ISSUE TITLE
Mac Gui钱包同步块显示不正确

### ISSUE THREAD

**Issue by joyven** [Bytom/bytom#731]
#### Environment

- OS: MacOS 10.13.3

#### Problem Description

![image](https://user-images.githubusercontent.com/5885519/39003899-7a5f47c8-442e-11e8-9a3f-9dd7db267f8f.png)
如题，MacOS 最新版本[v0.4.7](https://github.com/Bytom/bytom/releases/download/v0.4.7/Bytom.Wallet-Macosx.zip)可视化钱包，同步数据块显示总共块数有问题。比如同步第一块的时候显示:1/1,第二块显示：2/2，依次类推。难道理应该是这样的：已同步的区块/现在的最高区块。

**Comment by HAOYUatHZ** [comment]
guess u must be mining?

**Comment by FataliBud** [comment]
@HAOYUatHZ 被你猜对了，难道挖矿就显示不正常？我要停止挖矿去验证一下。

**Comment by ChrisLinn** [comment]
does it work

**Comment by HAOYUatHZ** [comment]
你出现这个问题的原因是  挖矿比同步快～是不是很爽
所以你挖到的就是最高的，但是后面正确发现节点之后你的块都会被回滚的

现在难度已经调整挖矿没那么简单了～所以也不会再遇到这样的问题～
