### ISSUE TITLE
"syncing":false,"current_block":0

### ISSUE THREAD

**Issue by bizlevel** [Bytom/bytom#734]
Why node is not in sync mode ? (block height is always "0" )
I run:
bytomd init --home /mnt/bytom --chain_id mainnet
bytomd node --home /mnt/bytom

And my next POST request always return 0 highest_block and no sync mode.
```
root@bytom:/mnt/bytom# curl -X POST http://localhost:9888/net-info
{"status":"success","data":{"listening":true,"syncing":false,"mining":false,"peer_count":0,"current_block":0,"highest_block":0,"network_id":"mainnet"}}
```
How to run sync full mode (not fast) ?
Thanks.

**Comment by HAOYUatHZ** [comment]
plz use testnet at the moment
