### ISSUE TITLE
编译过程中，把源代码存放位置写死是不是有点不人性化

### ISSUE THREAD

**Issue by FataliBud** [Bytom/bytom#735]
#### Problem Description

下载或者git拉取的代码必须在$GOPATH/src/github.com/bytom这个位置才能编译，是不是考虑使用相对路径呢，在任何地方编译都可以就好了。没必要一定在这个位置，因为有的时候，这个位置根本没权限。

**Comment by HAOYUatHZ** [comment]
很抱歉的告诉你，我们这么做并不是因为我们不人性化，而是go确实对这方面支持的不好。
我们不得不关闭这个issue
