### ISSUE TITLE
Can't create address

### ISSUE THREAD

**Issue by bizlevel** [Bytom/bytom#761]
In BYTOM GUI can't create address - no worked link.
In other account i can create, even 2 address. But no in this account.
I have 3 Acc, only in one i can add many addresses, in one only one address in last no one.

![capture](https://user-images.githubusercontent.com/12154217/39050666-dd776c5c-44ae-11e8-96c3-16ad657115b5.PNG)

**Comment by wliyongfeng** [comment]
Maybe due to the trailing spaces when filling alias. Try new account with no trailing spaces when filling the alias.

**Comment by bizlevel** [comment]
No, no spaces.
On new version this trouble not recreated.
