### ISSUE TITLE
simd miner killed 9

### ISSUE THREAD

**Issue by FataliBud** [Bytom/bytom#762]
![Uploading image.png…]()

SIMD版的v5.0的在mac中挖矿，差不多10分钟就中断了。日志报killed 9,再无其他信息。

**Comment by FataliBud** [comment]
time="2018-04-21T01:47:22+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-21T01:47:22+08:00" level=info msg="block saved on disk" hash=46a96041d46cae21ca86b68b6e16b2193d11205a244705f717aeaa7fe7948a2f height=1558
time="2018-04-21T01:47:22+08:00" level=info msg="Miner processed block" height=1558 isOrphan=false tx=1
time="2018-04-21T01:47:24+08:00" level=info msg="block saved on disk" hash=4599c086747f77a0228936701caad1d7ba8b2db1619d51041caf21344cf1f88a height=1559
time="2018-04-21T01:47:24+08:00" level=info msg="Miner processed block" height=1559 isOrphan=false tx=1
time="2018-04-21T01:47:25+08:00" level=info msg="block saved on disk" hash=a7e5e1315827f4b91ee20a19106cb6eaf5a2f6a6da68ab26f129c51b0b87e0d1 height=1560
time="2018-04-21T01:47:25+08:00" level=info msg="Miner processed block" height=1560 isOrphan=false tx=1
time="2018-04-21T01:47:26+08:00" level=info msg="block saved on disk" hash=c115765485ae765720483e7ab44b4c29a4042f94fe883b17c1db009ddf266c7b height=1561
time="2018-04-21T01:47:26+08:00" level=info msg="Miner processed block" height=1561 isOrphan=false tx=1
Killed: 9

**Comment by HAOYUatHZ** [comment]
sorry itz because i release the wrong file

sad story.....


it has actually been fixed  https://github.com/Bytom/bytom/issues/718

**Comment by FataliBud** [comment]
@HAOYUatHZ 能否把修补的发一下版本或者替换一下原版本呢？我下载的5.0的版本应该是最新的吧

**Comment by HAOYUatHZ** [comment]
明天会发新版本～
