### ISSUE TITLE
[外部测试] 对于socket连接建立之后，加密传输公钥的流程的疑问

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#763]
我这几天把Bytom中，当某个节点与peer建立连接之后，双方进行安全检查的流程细看了一遍，对于其中的一些地方有疑问：

建立起连接的双方节点为了以**加密方式**传输公钥和challenge signature，生成了一次性的公私钥对它们进行加密，这个步骤是否可以防范中间人攻击? 因为按我的理解，似乎还是防范不了，只是增加了中间人的难度而已。那么我们使用一次性公私钥的初衷是什么？

我看的主要的代码集中于`p2p/secret_connection.go`中的`MakeSecretConnection`方法：<https://github.com/Bytom/bytom/blob/40c8794c0fd0ce115d368aa688fc244b85de1e7e/p2p/secret_connection.go#L49-L101>

为了方便理解，对于这段代码做的事情，我整理成了一个图，把其中的步骤列了出来：

![bytom](https://user-images.githubusercontent.com/333781/39066764-cafa19f8-4508-11e8-8f44-5c352717f999.png)

从上面的代码和图示的流程可以看出，当两个节点建立连接以后，它们最终的目的是要把各自的公钥传输给对方，以便后面进行加密传输，防止内容被中间人窃取或修改。为了安全起见，并没有直接以明文方式把公钥和challenge signature传过去，而是对它进行了加密。为了加密，双方又先各自生成了另一对一次性的公私钥（代码中叫`Ephemeral pubKey`/`privKey`），其中的公钥以明文的方式首先传给对方，然后两边再各自利用对方的一次性公钥和自己的一次性私钥算出sharedSecret和nonce（两边结果相等），再利用`secretbox.Seal`将真正的公钥和challenge signature加密后传给对方，最后由对方使用`secretbox.Open`解密后拿出真正公钥，并对challenge signature进行签名的验证。如果整个过程都正确，那么就认为对方是可信的，后面可以继续通信。

按照我的理解，虽然我们对公钥和challenge signature进行加密传输，但是如果真有中间人的话，它还是可以做到窃取或修改：

1. 中间人首先可以拿到双方发给对方的一次性公钥（明文），把它们占为己有，并不传给对方
2. 中间人生成两对公/私钥，用其中的公钥假冒原有的一次性公钥，传给双方
3. 中间人拿到双方发过来的经过加密后的真正公钥和challenge signature后，可以利用之前生成的私钥和已占有的一次性公钥进行解密，可以看到真正公钥和challenge signature的明文
4. 中间人再次生成两对公私钥，用其中的公钥假冒真正公钥，用其中的私钥重新对challenge进行签名后，再经过之前生成及占用的一次性密钥加密后发给双方
5. 双方完成了验证，相信对方是可靠的（实际上是相信了中间人）
6. 之后双方再进行传输时，中间人可以对内容进行解密和修改

在这整个过程中，我觉得中间多出来的“使用一次性密钥进行加密”的步骤实际上并没有起到防范中间人的作用，仅仅是让中间人的难度增加。而比原的代码是开源的，相信中间人还是可以通过研究代码进行针对性的处理。

由于我对网络安全这块儿不是很熟悉，所以不知道我的理解是否有问题。还有，不知道你们是不是已经有了别的手段（比如证书等）来解决这个问题。

**Comment by HAOYUatHZ** [comment]
thx for ur interest on Bytom!
let we summary up and explain it to you, may take a couple of days. thx for ur patience

**Comment by huwenchao** [comment]
说几点看法：
1. 节点之间首次建连，在没有对方任何信息的情况下，是无法做到绝对安全的，因为没有信任的起点。所以 HTTPS 要用 CA 来保证信任。ssh 协议如果用密码登陆，第一次会给出服务器公钥指纹让用户自己确认，之后如果指纹对不上会提示并拒绝登陆；如果直接用公钥登陆，需要将客户端的公钥放到服务端的 authorized_key 里。
2. 如果中间人有能力监听和篡改所有数据，上面提到的攻击方法是可以实现的，这个安全问题需要引入另外的信任起点，否则无解。但是如果中间人只能监听而无法修改数据，那这个一次性公私钥对还是有作用的。一来可以避免公钥明文传输，二来加密连接数据用到的 shrSecret 是用自己的私钥和对方公钥生成的，如果不是用一次性的，两个节点之间的每次通信都会用一样的 shrSecret，虽然还有一个 nonce 来保证生成密文的随机性，但还是有被分析密文模式来破译的风险。
