### ISSUE TITLE
运行./bytom.exe node --mining ERROR

### ISSUE THREAD

**Issue by RAYNBINGHAN** [Bytom/bytom#775]
#### Environment

- OS: W10

error msg="Could not perform UPNP discover" error="write udp4 0.0.0.0:61927->239.255.255.250:1900: i/o timeout

**Comment by HAOYUatHZ** [comment]
请稍等或者删掉 addrbook重启

以后代码会优化结点addrbook  感谢支持

**Comment by RAYNBINGHAN** [comment]
好的  加油

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
