### ISSUE TITLE
Why doesn't synchronize block on mainnet

### ISSUE THREAD

**Issue by FataliBud** [Bytom/bytom#780]
### env
OS： MacOs 10.13.3 、 MacOS 10.13.2
bytomVersion: 
- [bytom-0.5.0-darwin_amd64.tgz](https://github.com/Bytom/bytom/releases/download/v0.5.0/bytom-0.5.0-darwin_amd64.tgz) v0.5.0  普通版
- [bytomd-simd-0.5.0-darwin_amd64.zip](https://github.com/Bytom/bytom/releases/download/v0.5.0/bytomd-simd-0.5.0-darwin_amd64.zip) v0.5.0   SIMD版

我尝试了上面两个版本：
- 普通版：切换到mainnet之后，一直没有同步，net-info显示syncing为false。
- simd版：mainnet和testnet都可以同步，但是一直出现[killed 9](https://github.com/Bytom/bytom/issues/762)的问题，运行几分钟就杀掉了进程，虽然我提出了这个bug，说是已经修复过了，我看了问题是在打包v0.5.0之前被人也提出过:[mac 10.13.3 (17D47)系统，挖矿进程自动kill](https://github.com/Bytom/bytom/issues/718)，且修复了，为什么却没有打包到v0.5.0

总之，在MacAir或者MacPro都出现问题，暂时无法使用。
能不能将问题解决一下，发个新版本。

原谅我目前还一直是比原神教的脑残粉好吧，昨天还入手1.7w个BTM，结果今天就跌了10%+，虽然如此，我依然希望比原神教壮大，还是希望能够各个软件使用起来更好。不要老是发布一个问题一大堆，wiki又很少的版本。

甚至，你们的wiki都不更新。。。发布了新版本，wiki上写的还是0.4.7的运行命令。还有一些细节末节的东西，每个版本新加的可执行文件也没有一个说明是干嘛的。。。

比如0.5.0中多了一个miner-darwin_amd64这个文件，看起来是矿工相关的，但是怎么用，或者说不用管它，一点说明都没有。

原谅我说了这么多，我每次都摸索到深夜，提了至少10几个bug或者优化相关的东西了吧。请对我的提问给予回复，不要两三天都不闻不问好吧。

问题[Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable](https://github.com/Bytom/bytom/issues/764)提出来你们看都没看，我把问题发生的场景描述的很清楚了吧。对于SIMD不是偶现，是一直存在，对于普通版，是偶现。原因是CTRL+C的时候，虽然看似退出了进程，但是还有进程一直没有退出来，导致下次启动的时候端口占用，报了一堆毫不相关的异常信息。

**Comment by HAOYUatHZ** [comment]
是的我的锅！
我已经fix了但是打包时打错了  0.5.0 里面的 .dylib  用的还是 0.4.7 的
抱歉抱歉哭

**Comment by HAOYUatHZ** [comment]
miner前面都有的 但是其实普通用户用不上一般是我们自己内部测试时使用的
暂时不用管
文档方面承认确实很不完善，人手很紧张

miner前面都有的 但是其实普通用户用不上一般是我们自己内部测试时使用的
暂时不用管
文档方面承认确实很不完善，人手很紧张，在努力更新了

**Comment by HAOYUatHZ** [comment]
还有 #764 真的是看了的
但是大概定位到了问题 还没有解决
之所以没有回复是因为   你给的信息确实很详尽我已经不知道问什么好了
但是又还没有解决所以也不知道回复什么好也不能close

**Comment by FataliBud** [comment]
@HAOYUatHZ 感谢回复，能看到你们的回复，说明你们在做一个认真的项目，所以，我们一直都会支持的，所以，这会儿我还得入手一波BTM，不怕再跌10%，因为我相信认真做项目的团队，一定会有暴发的一天。

**Comment by Blockmeta** [comment]
fixed at version 1.0.2
