### ISSUE TITLE
 I can not send the BTM when I created two accounts with the same alias

### ISSUE THREAD

**Issue by jeanstang** [Bytom/bytom#809]
#### Environment

- OS: Windows7 
- CPU: I5
- RAM: 16GB
- Bytomd version: 0.5.1-0df7c918

#### Problem Description

I created two accounts with the same alias on 2 PCs. and then I can not send the BTM. 
the error: invalid account alias jeans on action 0: fail to find account
![image](https://user-images.githubusercontent.com/30144233/39140276-a10943ee-4756-11e8-9ec4-56421f884e81.png)

but I can send BTM via ID but not with alias.

When I send BTMs from another same alias account (other laptop). it show this:
errors occurred in one or more actions-<action index 0: reserving utxos: some coinbase utxos are immature: reservation found insufficient funds>

Any Guys reply ? @ Thanks

**Comment by HAOYUatHZ** [comment]
这个是因为  utxo不够？

**Comment by jeanstang** [comment]
当时测试时laptop有几万未花费，laptop发pc账户只是发送66.66666666个，不应该是不够

**Comment by jeanstang** [comment]
你看错误提示，是无限的别名，fail to find account
