### ISSUE TITLE
BTMs disappeared after a sync problem. All transactions rollbacked

### ISSUE THREAD

**Issue by jeanstang** [Bytom/bytom#810]
#### Environment

- OS: Windows7 
- CPU: I5
- RAM: 16GB
- Bytomd version: 0.5.1-0df7c918

#### Problem Description

Last night(2018/04/23 23:00) , BTMs disappeared after a sync problem.
There was a slow sync last night,
And then, over 200000 BTM, all the BTM that I have been mined, they are disappeared.
My PC mining again. All transactions rollbacked.

Thanks

**Comment by Blockmeta** [comment]
closed . You are not in mainnet

**Comment by jeanstang** [comment]
小伙，你回复的时候是主网出来了，实际上我测试的时候主网还没出来，你看时间。
这是大问题

**Comment by jeanstang** [comment]
the time is (2018/04/23 23:00) ,
