### ISSUE TITLE
http://127.0.0.1:9888/dashboard/core 手动刷新时无法打开

### ISSUE THREAD

**Issue by zkaip** [Bytom/bytom#819]
#### Environment

- OS: Mac

#### Problem Description

1.0.0 版本，前端路由可以，但是后端路由估计漏了 /dashboard/core 地址，导致无法刷新

**Comment by shengling2008** [comment]
看下最新的版本，如果没有此问题，就close了

**Comment by ZhitingLin** [comment]
最新版本的已经没有这个bug了。
