### ISSUE TITLE
【外部测试】点击“新建账户”按钮，之后关闭钱包软件，程序崩溃

### ISSUE THREAD

**Issue by santifuhuo** [Bytom/bytom#820]
#### Environment

- OS: Windows7 64位 企业版

#### Problem Description

今天第一时间在github上下载了软件包”Bytom-Wallet-desktop-Windows64-1.0.0.zip“，解压之后按照“比原用户手册v1.0.pdf”进行操作，最后钱包桌面程序崩溃，初步看应该是内存使用有问题。具体复现步骤如下：
1、打开钱包桌面程序；
2、点击“加入 Bytom 主网”；
3、点击“加入网络”；
4、点击“账户”下来列表；
5、点击“新建账户”按钮；
6、点击右上角关闭程序红色X，导致程序崩溃；
以上操作步骤需要连续进行，必现程序崩溃现象。
程序崩溃截图已经上传，请解决。

![crash_screenshot](https://user-images.githubusercontent.com/38684365/39174119-5bd750c6-47d9-11e8-82f9-5dedc35ebf29.png)

**Comment by ZhitingLin** [comment]
你好，我已经安装win7 64 的系统。并没办法复现你所说的问题。这个error是在点击新建账户后？还是点击关闭 后？能否详细叙述下？

**Comment by santifuhuo** [comment]
是在点击关闭之后出现的。
要按照上面的步骤一步步来，必现

**Comment by santifuhuo** [comment]
我换了一台电脑试了下，发现如下必现步骤：
1、打开钱包；
2、点击“加入Bytom主网”；
3、点击“加入网络”，接着立即按”alt + F4“按钮，程序崩溃。
此时C:\Users\用户名\AppData\Roaming下面只有BytomWallet文件夹，无Bytom文件夹。如果不按”alt+F4“的话，程序运行正常，并且会创建Bytom文件夹。
  初步判断我的第一台电脑比较卡，所以在点击”加入网络“按钮后程序执行慢，没有快速跳转到下个流程，导致我此时点击关闭程序后出现程序崩溃的现象。现在换了台性能高的电脑，需要在点击“加入网络”按钮后快速点击“alt+F4”关闭程序，才能复现此问题。

![screenshot](https://user-images.githubusercontent.com/38684365/39191561-c6c383d4-4809-11e8-8c2c-625c49f5a6c9.png)

![screenshot2](https://user-images.githubusercontent.com/38684365/39191571-cd3a2204-4809-11e8-8ccc-7b7443031546.png)

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me

**Comment by ZhitingLin** [comment]
这是因为我们的desktop是用electron 编写的。原因导致是在于你在主进程发送信号到渲染进程 或者 渲染进程发送信号到主进程的时候切断了而导致的。这是正常的报错。
