### ISSUE TITLE
服务器新部署了一个节点，启动问题

### ISSUE THREAD

**Issue by Demontf** [Bytom/bytom#821]
#### Environment

- OS: ubuntu 16.4

#### Problem Description
在服务器新部署一个节点，使用
./bytomd-linux_amd64 node --mining 启动节点  在~/.bytom中并没有创建账户（没有keystore），但是浏览器中要求输入tokenname:xyz. 这里该如何操作，我在mac上初次启动是弹出的新建账户页面。

**Comment by FataliBud** [comment]
对于这种操作，我清冽建议你看看API，你下载的包里面还有一个bytomcli开头的文件，还脚本是创建用户账户，执行交易等的客户端文件。而这个bytomd-linux_amd64是一个守护进程，属于一个节点服务器。

**Comment by shuangjj** [comment]
## To create access token:
bytomcli create-access-token **tokenID**
After that you can login to the dashboard and create an new account.

**Comment by Demontf** [comment]
@shuangjj Thanks a lot for your solution. It very helpful.
