### ISSUE TITLE
windows-wallet crash

### ISSUE THREAD

**Issue by captaincs** [Bytom/bytom#823]
#### Environment

- OS: windows 7
AMD FX 6300 Six-Core Processor 3.5GHz
64位 系统

#### Problem Description
第一次启动钱包，程序直接闪退， 后重复启动不了。
在任务管理器里关闭进程， 再重新启动才好。

**Comment by ZhitingLin** [comment]
这个可能是你的cmd 的 bytomd已经跑了。然后你尝试打开桌面端？

**Comment by Blockmeta** [comment]
fixed at 1.0.2
