### ISSUE TITLE
bk peer num:0 sw peer num:0 循环 不可同步

### ISSUE THREAD

**Issue by semliu** [Bytom/bytom#826]
#### Environment

- OS: win7 64

#### Problem Description

time="2018-04-24T18:17:25+08:00" level=info msg="Failed to dial peer" address="4
5.79.213.28:46657" error="Error creating peer: EOF"
time="2018-04-24T18:17:25+08:00" level=error msg="Error dialing seed" error="Err
or creating peer: EOF"
time="2018-04-24T18:17:26+08:00" level=info msg="Ensure peers" numDialing=0 numO
utPeers=0 numToDial=10
time="2018-04-24T18:17:33+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

time="2018-04-24T18:17:43+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by bizlevel** [comment]
same problem.
I trying add seed IPs, but no luck:

```
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Started node" nodeInfo="NodeInfo{pk: PubKeyEd25519{3EF99259D915CC4DD80AD30D9AF9A1C3DA24C18D70BA4E97C
D33733ACAE4C917}, moniker: anonymous, network: mainnet [remote , listen 167.99.XX.XX:46656], version: 1.0.0-23e45399 ([wire_version=0.7.1 p2p_version=0.5.0])}"
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Added new address address:212.111.41.245:46656 total:1"
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Added new address address:198.74.61.131:46656 total:2"
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Saving AddrBook to file" size=2
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Saving AddrBook to file" size=2
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Dialing peer" address="198.74.61.131:46656"
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=info msg="Failed to dial peer" address="198.74.61.131:46656" error="Error creating peer: dial tcp 198.74.61.13
1:46656: getsockopt: connection refused"
Apr 24 10:50:06 bytom bytom[15658]: time="2018-04-24T10:50:06Z" level=error msg="Error dialing seed" error="Error creating peer: dial tcp 198.74.61.131:46656: getsockopt: connectio
n refused"
Apr 24 10:50:07 bytom bytom[15658]: time="2018-04-24T10:50:07Z" level=info msg="Ensure peers" numDialing=0 numOutPeers=0 numToDial=10

```

**Comment by yuzebin** [comment]
OS: Mac OSX , the same problem:

"Failed to dial peer"

**Comment by silenyc** [comment]
time="2018-04-24T19:10:07+08:00" level=info msg="Failed to add peer" address="45.118.132.164:46656" error="Peer is on a different major version. Got 0, expected 1"
time="2018-04-24T19:10:07+08:00" level=info msg="Dialing peer" address="47.96.42.1:46656"
time="2018-04-24T19:10:07+08:00" level=info msg="Peer handshake" peerNodeInfo="NodeInfo{pk: PubKeyEd25519{826AA9ACA891D7BFEAB7311556AC7AE46183929472FECA71AAA3F31E26B06881}, moniker: anonymous, network: testnet [remote , listen 10.80.155.150:46656], version: 0.5.1-0df7c918 ([wire_version=0.7.1 p2p_version=0.5.0])}"
time="2018-04-24T19:10:07+08:00" level=info msg="Failed to add peer" address="47.96.42.1:46656" error="Peer is on a different major version. Got 0, expected 1"
time="2018-04-24T19:10:17+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T19:10:27+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T19:10:37+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T19:10:47+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by xiaotiansky** [comment]
[2018-04-24T19:53:43.725] [INFO] bytomd - bytomd mining: time="2018-04-24T19:53:44+08:00" level=info msg="Ensure peers" numDialing=0 numOutPeers=0 numToDial=10

[2018-04-24T19:53:50.282] [INFO] bytomd - bytomd mining: time="2018-04-24T19:53:50+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:01.046] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:01+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:11.079] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:11+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:21.097] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:21+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:31.046] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:31+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:41.112] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:41+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:54:51.152] [INFO] bytomd - bytomd mining: time="2018-04-24T19:54:51+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:55:01.817] [INFO] bytomd - bytomd mining: time="2018-04-24T19:55:01+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:55:11.777] [INFO] bytomd - bytomd mining: time="2018-04-24T19:55:11+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:55:21.762] [INFO] bytomd - bytomd mining: time="2018-04-24T19:55:22+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

[2018-04-24T19:55:31.761] [INFO] bytomd - bytomd mining: time="2018-04-24T19:55:32+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by FataliBud** [comment]
time="2018-04-24T21:16:11+08:00" level=info msg="Will dial address" addr="125.120.74.34:46658"
time="2018-04-24T21:16:11+08:00" level=info msg="Will dial address" addr="123.249.0.160:46657"
time="2018-04-24T21:16:11+08:00" level=info msg="Will dial address" addr="45.79.213.28:46657"
time="2018-04-24T21:16:11+08:00" level=info msg="Will dial address" addr="47.96.67.144:46657"
time="2018-04-24T21:16:11+08:00" level=info msg="Will dial address" addr="39.104.176.10:46657"
time="2018-04-24T21:16:11+08:00" level=info msg="Dialing peer" address="125.120.74.34:46658"
time="2018-04-24T21:16:14+08:00" level=info msg="Failed to dial peer" address="125.120.74.34:46658" error="Error creating peer: dial tcp 125.120.74.34:46658: i/o timeout"
time="2018-04-24T21:16:14+08:00" level=info msg="Dialing peer" address="123.249.0.160:46657"
time="2018-04-24T21:16:14+08:00" level=info msg="Failed to dial peer" address="123.249.0.160:46657" error="Error creating peer: read tcp 192.168.0.102:60296->123.249.0.160:46657: read: connection reset by peer"
time="2018-04-24T21:16:14+08:00" level=info msg="Dialing peer" address="45.79.213.28:46657"
time="2018-04-24T21:16:14+08:00" level=info msg="Failed to dial peer" address="45.79.213.28:46657" error="Error creating peer: read tcp 192.168.0.102:60297->45.79.213.28:46657: read: connection reset by peer"
time="2018-04-24T21:16:14+08:00" level=info msg="Dialing peer" address="47.96.67.144:46657"
time="2018-04-24T21:16:14+08:00" level=info msg="Failed to dial peer" address="47.96.67.144:46657" error="Error creating peer: read tcp 192.168.0.102:60298->47.96.67.144:46657: read: connection reset by peer"
time="2018-04-24T21:16:14+08:00" level=info msg="Dialing peer" address="39.104.176.10:46657"
time="2018-04-24T21:16:15+08:00" level=info msg="Failed to dial peer" address="39.104.176.10:46657" error="Error creating peer: read tcp 192.168.0.102:60299->39.104.176.10:46657: read: connection reset by peer"
time="2018-04-24T21:16:19+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T21:16:29+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by bizlevel** [comment]
Same issuses! NO peers!

**Comment by HAOYUatHZ** [comment]
the seed nodes are all occupied

we've solved this problem but more tests are still needed.

we will release a new version asap

**Comment by HAOYUatHZ** [comment]
we've solved this problem and would release a newer version asap

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me
