### ISSUE TITLE
主网命令行操作，打开dashboard空白，且js报错

### ISSUE THREAD

**Issue by yunduansing** [Bytom/bytom#828]
#### Environment

- OS: win 10

#### Problem Description

1.Refused to execute script from 'http://127.0.0.1:9888/dashboard/dashboard.64fafdc8a3245ce65127.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
2.Failed to load resource: the server responded with a status of 500 (Internal Server Error) :9888/favicon.ico

**Comment by ZhitingLin** [comment]
are you using 32bit or 64bit? are there any errors from command line?
