### ISSUE TITLE
win64钱包无法连接种子peer

### ISSUE THREAD

**Issue by AnsenYu** [Bytom/bytom#831]
#### Environment

- OS: windows

#### Problem Description

win64钱包无法连接种子peer，upnp映射应该没问题。

C:\Users\Ansen\Downloads\bytom-1.0.0-windows_amd64>bytomd-windows_amd64.exe node --mining --p2p.dial_timeout 10
time="2018-04-24T22:42:43+08:00" level=info msg="Local listener" ip="::" port=46657
time="2018-04-24T22:42:43+08:00" level=info msg="Getting UPNP external address"
time="2018-04-24T22:42:46+08:00" level=error msg="Could not perform UPNP discover" error="write udp4 0.0.0.0:54288->239.255.255.250:1900: i/o timeout"
time="2018-04-24T22:42:46+08:00" level=info msg="CPU miner started"
time="2018-04-24T22:42:46+08:00" level=info msg="Rpc listen" api address:="0.0.0.0:9888"
time="2018-04-24T22:42:46+08:00" level=info msg="Launching System Browser with :http://127.0.0.1:9888"
time="2018-04-24T22:42:46+08:00" level=info msg="Added new address address:45.79.213.28:46657 total:6"
time="2018-04-24T22:42:46+08:00" level=info msg="Added new address address:198.74.61.131:46657 total:6"
time="2018-04-24T22:42:46+08:00" level=info msg="Saving AddrBook to file" size=6
time="2018-04-24T22:42:46+08:00" level=info msg="Saving AddrBook to file" size=6
time="2018-04-24T22:42:46+08:00" level=info msg="Dialing peer" address="212.111.41.245:46657"
time="2018-04-24T22:42:46+08:00" level=info msg="Started node" nodeInfo="NodeInfo{pk: PubKeyEd25519{1BC2B531D6CCF57C9026A2431A00CA330E2B24AC7D19C2BE7AC435D941D1
D24A}, moniker: anonymous, network: mainnet [remote , listen 192.168.31.181:46657], version: 1.0.0-23e45399 ([wire_version=0.7.1 p2p_version=0.5.0])}"
time="2018-04-24T22:42:47+08:00" level=info msg="Ensure peers" numDialing=1 numOutPeers=0 numToDial=9
time="2018-04-24T22:42:48+08:00" level=info msg="Failed to dial peer" address="212.111.41.245:46657" error="Error creating peer: read tcp 192.168.31.181:22600->
212.111.41.245:46657: wsarecv: An existing connection was forcibly closed by the remote host."
time="2018-04-24T22:42:48+08:00" level=error msg="Error dialing seed" error="Error creating peer: read tcp 192.168.31.181:22600->212.111.41.245:46657: wsarecv:
An existing connection was forcibly closed by the remote host."
time="2018-04-24T22:42:48+08:00" level=info msg="Dialing peer" address="47.100.105.165:46657"
time="2018-04-24T22:42:48+08:00" level=info msg="Failed to dial peer" address="47.100.105.165:46657" error="Error creating peer: EOF"
time="2018-04-24T22:42:48+08:00" level=error msg="Error dialing seed" error="Error creating peer: EOF"
time="2018-04-24T22:42:48+08:00" level=info msg="Dialing peer" address="47.100.214.154:46657"
time="2018-04-24T22:42:49+08:00" level=info msg="Failed to dial peer" address="47.100.214.154:46657" error="Error creating peer: EOF"
time="2018-04-24T22:42:49+08:00" level=error msg="Error dialing seed" error="Error creating peer: EOF"
time="2018-04-24T22:42:56+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T22:43:06+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T22:43:16+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T22:43:26+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by sfx12311** [comment]
在 C:\Users\xxxx\AppData\Roaming\Bytom下的config.toml文件里面的 seeds中加这两个地址：103.49.9.106:46657,123.249.0.160:46657，这样感觉同步成功率高很多

**Comment by AnsenYu** [comment]
@sfx12311 多谢，我试试

**Comment by HAOYUatHZ** [comment]
可以吗 可以的话我就 close啦

后面也会发新版本解决这个问题～ 。 我们已经有了解决方案  需要多测测

**Comment by Blockmeta** [comment]
fixed at 1.0.2
