### ISSUE TITLE
Mining on Linux - No peers/ No sync occuring (mainnet)

### ISSUE THREAD

**Issue by hybridtangent** [Bytom/bytom#832]
#### Environment

- OS: Ubuntu 16.04 LTS

#### Problem Description
Using command 
./bytomd-linux_amd64 node --mining --chain_id mainnet

System never connects to peers or sync the mainnet.

Please help.

====================LOGS============================

time="2018-04-24T11:15:18-05:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T11:15:23-05:00" level=info msg="block saved on disk" hash=276a9bb1b154516df1ea43c414fc160803a6ecfd46405b40d264f1a8a764efa8 height=3627
time="2018-04-24T11:15:23-05:00" level=info msg="Miner processed block" height=3627 isOrphan=false tx=1
time="2018-04-24T11:15:28-05:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T11:15:30-05:00" level=info msg="Ensure peers" numDialing=0 numOutPeers=0 numToDial=10
time="2018-04-24T11:15:38-05:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T11:15:38-05:00" level=info msg="Saving AddrBook to file" size=0
time="2018-04-24T11:15:48-05:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-24T11:15:58-05:00" level=info msg="bk peer num:0 sw peer num:0 []"

**Comment by shuangjj** [comment]
Try to setup port forward on your router to forward TCP messages to port 46658/46657 to your local machine.

**Comment by hybridtangent** [comment]
I'm able to sync on the testnet. I will try the port forwarding for the mainnet.

**Comment by nsummy** [comment]
This is happening to me on Windows.

**Comment by HAOYUatHZ** [comment]
we've solved this problem and would release a newer version asap

**Comment by shengling2008** [comment]
Use the latest version
