### ISSUE TITLE
Fetch error: TypeError: Network request failed

### ISSUE THREAD

**Issue by linqbug** [Bytom/bytom#834]
#### Environment

- OS: 【Winsows Server 2016 64bit】

#### Problem Description

【操作步骤】：

2018年4月24日 23点，因暂时无法获取种子，于是，根据技术测试2群组长“思想的芦苇”指导，修改 替换了 Bytom\config.toml中的种子清单。

2018年4月25日 6点，停止了账本同步，并显示 报错 如下。

【问题现象】 ①：

在主界面 - 余额的页面里，报错：Fetch error: TypeError: Network request failed

【问题现象】 ②：

同时，查看了 命令行执行的情况，发现如下输出：

time="2018-04-25T07:26:10+08:00" level=info msg="Failed to dial peer" address="xx.xxx.xx.xx:xxxxx" error="Error creating peer: dial tcp xx.xxx.xx.xx:xxxxx: i/o timeout"
time="2018-04-25T07:26:10+08:00" level=info msg="No addresses to dial. Sending pexRequest to random peer" peer="Peer{MConn{xx.xxx.xx.xx:xxxxx} 244DB28BD655 out}"
time="2018-04-25T07:26:10+08:00" level=info msg="Stopping peer gracefully"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x97026e]

goroutine 63 [running]:
github.com/bytom/p2p.(*Switch).stopAndRemovePeer(0x0, 0xc0423d8120, 0x0, 0x0)
        C:/Users/gavin/go/src/github.com/bytom/p2p/switch.go:489 +0x3e
github.com/bytom/p2p.(*Switch).StopPeerGracefully(0x0, 0xc0423d8120)
        C:/Users/gavin/go/src/github.com/bytom/p2p/switch.go:485 +0x84
github.com/bytom/p2p.(*PEXReactor).RequestPEX(0xc042170000, 0xc0423d8120)
        C:/Users/gavin/go/src/github.com/bytom/p2p/pex_reactor.go:168 +0xb3
github.com/bytom/p2p.(*PEXReactor).ensurePeers(0xc042170000)
        C:/Users/gavin/go/src/github.com/bytom/p2p/pex_reactor.go:318 +0xa30
github.com/bytom/p2p.(*PEXReactor).ensurePeersRoutine(0xc042170000)
        C:/Users/gavin/go/src/github.com/bytom/p2p/pex_reactor.go:222 +0x9b
created by github.com/bytom/p2p.(*PEXReactor).OnStart
        C:/Users/gavin/go/src/github.com/bytom/p2p/pex_reactor.go:76 +0x5a

C:\>   (退回至命令行)

**Comment by HAOYUatHZ** [comment]
1.0.0 是否还存在这个问题呢？相信已经被 solved？   没有问题的话我就关掉这个issue啦
