### ISSUE TITLE
【外部测试】新建交易时如果地址格式不对，UI上提示信息过多，最后覆盖了大部分UI

### ISSUE THREAD

**Issue by santifuhuo** [Bytom/bytom#840]
#### Environment

- OS: WINDOWS7 64位

#### Problem Description
我觉得应该只展示最后一个错误提示信息。
![screenshot](https://user-images.githubusercontent.com/38684365/39235490-88ef2fb6-4865-11e8-811a-11499c1a391e.PNG)

**Comment by Blockmeta** [comment]
@ZhitingLin  optimize the dashboard

**Comment by Blockmeta** [comment]
fixed
