### ISSUE TITLE
Error Issuing Asset

### ISSUE THREAD

**Issue by sujitpal2000** [Bytom/bytom#844]
#### Environment

- OS: ??? Linux Ubuntu

#### Problem Description
./bytomcli build-transaction -t issue alice X 100000 -a bm1ql8c3uuzd96se0p7la458j7nmcw5cftt5v4sxwr --alias
ERROR 2018/04/25 17:10:54 errors occurred in one or more actions-<action index 0: reserving utxos: can't match enough valid utxos>

**Comment by HAOYUatHZ** [comment]
这个 是因为 utxo不够

**Comment by sujitpal2000** [comment]
Where can I get /find utxos and see those details

**Comment by shengling2008** [comment]
There must be btm in the account. Nodes need to be mined or sent by someone to btm.
