### ISSUE TITLE
垃圾升级

### ISSUE THREAD

**Issue by ehigh2014** [Bytom/bytom#847]
#### Environment

- OS: windows，linux

#### Problem Description

非常垃圾的主网升级：
1/windows版本根本没法同步，就更谈不上挖矿了
2/linux版本，处理好端口相关之后，可以链接到主网，但是还没有同步完，就出现了程序死机的情况，也不用说挖矿了
3/只顾着卖矿机，根本就没有GPU版本软件，简直非常的良心，提供代码让用户去写，也真亏BTM团队想的出来

总的来说，此次升级，非常失败，非常垃圾！！！

**Comment by HAOYUatHZ** [comment]
首先纠正一下哈  

我们没有卖矿机，卖矿机的是比特大陆，我们是做链的不是做矿机矿池的，本来就没有去研究如何挖矿...

所谓的 提供代码让用户去写是什么意思呀，指的是gpu挖矿代码的吗，请问在哪里～我也很想要一份～

**Comment by HAOYUatHZ** [comment]
还有想问一下   linux版  死机是什么情况呢～
log能不能发一下～

**Comment by HAOYUatHZ** [comment]
没法同步 现在是因为种子节点连的太多了都被连满了，我们现在有了初步的解决方案，多测试几遍后面就实施～

**Comment by Blockmeta** [comment]
no constructive comment.
