### ISSUE TITLE
No result from mining

### ISSUE THREAD

**Issue by shadi1989** [Bytom/bytom#849]
#### Environment

- OS: Windows 10

#### Problem Description

Running the "mining" option but no balance is added.
Got 16 logical cores which are using max 30% CPU (why not a self configurable value like 80 of 90%?)
It is syncing blocks every now and then but when i click balance i see "There are no balances".

Running on mainnet (left option after first start)

**Comment by Jray11** [comment]
I believe I am having the same issue as shadi1989!  I've had mining running for a while but the  current block just sits at the same # as the highest block.  Every time highest block goes up by 1 it syncs for a moment.  Am I doing something wrong?

**Comment by HAOYUatHZ** [comment]
coz this code only use 4 goroutine

 more cpus does'nt mean a higher speed

**Comment by Jray11** [comment]
That is fine, but our biggest issue is that when we mine we don't get anything.  I mined using my i5 yesterday for several hours and didn't even get .000001 BTM.  What we want to know is, if we mine how will we get our BTM?

**Comment by capitaliste** [comment]
I am also no getting any BTMs connected to the Mainnet for 24 hours.  Tried to use Wallet app and the command line app on two different computers.

**Comment by Jray11** [comment]
Yes.  They don't differentiate between solo and pool or asic mining.  The issue we face now is that we are mining with consumer CPU's (or GPU's) alone.  To find a block with such little processing power while racing against bitmain with dozens-hundreds of asics running would be a MIRACLE.  Long story short, you'd have to get very lucky (lottery lucky) to get anything solo mining until you are able to join a mining pool (viaBTC or Ant will both have pools soon)

**Comment by hybridtangent** [comment]
Well at least your app doesn't crash...
time="2018-04-26T14:33:01-05:00" level=info msg="Stopping peer gracefully"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xa80827]

goroutine 86 [running]:
github.com/bytom/p2p.(*Switch).stopAndRemovePeer(0x0, 0xc4201441b0, 0x0, 0x0)
	/Users/8btc_1/go/src/github.com/bytom/p2p/switch.go:489 +0x37
github.com/bytom/p2p.(*Switch).StopPeerGracefully(0x0, 0xc4201441b0)
	/Users/8btc_1/go/src/github.com/bytom/p2p/switch.go:485 +0x95
github.com/bytom/p2p.(*PEXReactor).RequestPEX(0xc420192230, 0xc4201441b0)
	/Users/8btc_1/go/src/github.com/bytom/p2p/pex_reactor.go:168 +0xac
github.com/bytom/p2p.(*PEXReactor).ensurePeers(0xc420192230)
	/Users/8btc_1/go/src/github.com/bytom/p2p/pex_reactor.go:318 +0xa70
github.com/bytom/p2p.(*PEXReactor).ensurePeersRoutine(0xc420192230)
	/Users/8btc_1/go/src/github.com/bytom/p2p/pex_reactor.go:222 +0x94
created by github.com/bytom/p2p.(*PEXReactor).OnStart
	/Users/8btc_1/go/src/github.com/bytom/p2p/pex_reactor.go:76 +0x59

**Comment by shadi1989** [comment]
@HAOYUatHZ What about the solo-mining?

**Comment by HAOYUatHZ** [comment]
@shadi1989 i am afraid solo-mining is not what u expect.  it's unlikely to mine a block successfully atm.

as for hash-rate, even if u r doing it with ur best, it won;t go up to 10h/s. joining a pool will be a nicer choice
