### ISSUE TITLE
[主网异常]主网一直跑了一天突然断开

### ISSUE THREAD

**Issue by Wolkin** [Bytom/bytom#850]
#### Environment

- OS: Win 7  64位

#### Problem Description
具体参见下图
![default](https://user-images.githubusercontent.com/34227886/39337301-ca20dd42-49ee-11e8-9fa5-62d52e796ee5.PNG)
![1](https://user-images.githubusercontent.com/34227886/39337302-ca65f56c-49ee-11e8-8155-a125e54422ea.PNG)

**Comment by HAOYUatHZ** [comment]
@yahtoo @Paladz 
1.0.0  不是解决了空指针了么

**Comment by winnerwoo** [comment]
Environment

OS: Win10 64位
Problem Description: I had the same problem. And running the "mining" option but no balance is added.It is syncing blocks every now and two days, but when i click balance i see "There are no balances".

**Comment by HAOYUatHZ** [comment]
nil  pointer 。这个在  production 分支中修复了，后面会发新版本

**Comment by ehigh2014** [comment]
i meet the problem, too

**Comment by HAOYUatHZ** [comment]
fixed in v1.0.1

**Comment by shengling2008** [comment]
在v1.0.1中这个问题已经解决
