### ISSUE TITLE
[外部测试] netsync/fetcher.go中的Fetcher. queues没有正确使用

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#860]
声明了`queues`:

<https://github.com/Bytom/bytom/blob/master/netsync/fetcher.go#L36>

```
queues map[string]int            // Per peer block counts to prevent memory exhaustion
```

它只在这里使用过：

<https://github.com/Bytom/bytom/blob/master/netsync/fetcher.go#L186-L189>

```
f.queues[insert.peerID]--
if f.queues[insert.peerID] == 0 {
	delete(f.queues, insert.peerID)
}
```

可以看到，这里的代码只是读取和删除queues的内容，没有别的地方向它写入，所以这些代码没起到什么作用

**Comment by yahtoo** [comment]
对，这里暂时没用。

**Comment by freewind** [comment]
暂时没用的代码最好不要写上，等真正写的时候再添加

**Comment by yahtoo** [comment]
可以提交pr修改。

**Comment by freewind** [comment]
PR created
