### ISSUE TITLE
【外部测试】simd-v1.0.0-windows_amd64版本Web页面：“设置-核心状态” 刷新后空白

### ISSUE THREAD

**Issue by happy519** [Bytom/bytom#861]
#### Environment

- OS: windows
-version: simd-v1.0.0 amd64 版本

#### Problem Description

simd-v1.0.0-windows_amd64版本Web页面：设置-核心状态 刷新后空白，而“设置-访问控制”和“设置-备份与恢复”均没有此问题

1. 用chrome打开Bytom Dashboard;
2. 点击设置-核心状态，页面正确显示：
![image](https://user-images.githubusercontent.com/19317648/39390162-65b2ff22-4ac3-11e8-97ed-83447da98824.png)
3. 点击刷新按钮，页面空白：
![image](https://user-images.githubusercontent.com/19317648/39390173-888ff31a-4ac3-11e8-895f-548382b1f73d.png)
4. “设置-访问控制”和“设置-备份与恢复”均没有此问题。
5. 地址栏输入http://127.0.0.1:9888/dashboard/core，页面依旧空白。
6. 地址栏输入http://127.0.0.1:9888/dashboard/backup，http://127.0.0.1:9888/dashboard/backup也能正确显示。

微信号：happy519machao

**Comment by shengling2008** [comment]
@happy519 最新版本这个是正常的，请用最新的版本，如果没有问题，就close了。
