### ISSUE TITLE
 1.0.1版：节点数0，最高高度460，当前高度460，三个数值，长时间不变化

### ISSUE THREAD

**Issue by linqbug** [Bytom/bytom#874]
#### Environment

- OS: 【Winsows 10 professional版 64bit】

#### Problem Description

**【操作步骤】**：

**①** 2018年4月28日 19点，下载了最新版 bytom-1.0.1-windows_amd64.zip，

**②** 在解压后，准备cmd，执行 bytomd-windows_amd64.exe 之前，先清理了C:\Users\Administrator\AppData\Roaming\Bytom目录 和 Bytom Wallet目录。

**③** 打开cmd命令行，正式开始：

首先输入：“bytomd-windows_amd64.exe init --chain_id mainnet”，正确执行。
继续输入：“bytomd-windows_amd64.exe node --mining”，正确执行。弹出了 Web端·钱包·注册 页面。

**④** 在注册之后，**进入“核心状态”选项，查看，发现**：

节点监听: | true
网络同步: | false
挖矿状态: | true
节点数:     |     0
当前高度: | 460
最高高度: | 460
网络ID:     | mainnet

并且，经过 20 分钟，依旧是显示 0、460、460 三个数字，不动。**【出现了：第 一 处 的 问题/现象】**

在此期间，查看 cmd 命令行 的输出，几乎都 显示 类似 如下 信息：

time="2018-04-28T19:26:46+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:26:56+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:06+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:06+08:00" level=info msg="Saving AddrBook to file" size=165
time="2018-04-28T19:27:09+08:00" level=info msg="Ensure peers" numDialing=0 numOutPeers=0 numToDial=5
time="2018-04-28T19:27:09+08:00" level=info msg="Will dial address" addr="47.100.214.154:46657"
time="2018-04-28T19:27:09+08:00" level=info msg="Will dial address" addr="139.198.177.191:46657"
time="2018-04-28T19:27:09+08:00" level=info msg="Will dial address" addr="182.246.106.40:46656"
time="2018-04-28T19:27:09+08:00" level=info msg="Dialing peer" address="47.100.214.154:46657"
time="2018-04-28T19:27:09+08:00" level=info msg="Peer handshake" peerNodeInfo="NodeInfo{pk: PubKeyEd25519{5D35B20D9622CE65EADE4098EC062C4AB91DDCA020EBE1544327F8184A8154C6}, moniker: anonymous, network: mainnet [remote , listen 172.19.113.202:46657], version: 1.0.1-77c7b4e2 ([wire_version=0.7.1 p2p_version=0.5.0])}"
time="2018-04-28T19:27:09+08:00" level=info msg="Receive request" msg=StatusRequestMessage peerID=5D35B20D9622CE65EADE4098EC062C4AB91DDCA020EBE1544327F8184A8154C6
time="2018-04-28T19:27:10+08:00" level=info msg="Receive request" msg="StatusResponseMessage{Height: 4549, Best hash: a0ceb0f69e1bea569c79f9c073b542cb727531d69edc56a25589865bc77da637, Genesis hash: a75483474799ea1aa6bb910a1a5025b4372bf20bef20f246a2c2dc5e12e8a053}" peerID=5D35B20D9622CE65EADE4098EC062C4AB91DDCA020EBE1544327F8184A8154C6
time="2018-04-28T19:27:10+08:00" level=info msg="Add new peer to blockKeeper" ID=5D35B20D9622CE65EADE4098EC062C4AB91DDCA020EBE1544327F8184A8154C6
time="2018-04-28T19:27:10+08:00" level=info msg="Added peer" peer="Peer{MConn{47.100.214.154:46657} 5D35B20D9622 out}"
time="2018-04-28T19:27:10+08:00" level=info msg="Dialed and added peer" address="47.100.214.154:46657"
time="2018-04-28T19:27:10+08:00" level=info msg="Dialing peer" address="139.198.177.191:46657"
time="2018-04-28T19:27:10+08:00" level=info msg="New peer connected."
time="2018-04-28T19:27:10+08:00" level=error msg="Connection failed @ recvRoutine (reading byte)" conn="MConn{47.100.214.154:46657}" error=EOF
time="2018-04-28T19:27:10+08:00" level=info msg="Stopping peer due to error" error=EOF peer="Peer{MConn{47.100.214.154:46657} 5D35B20D9622 out}"
time="2018-04-28T19:27:10+08:00" level=info msg="Delete peer from peerset" ID=5D35B20D9622CE65EADE4098EC062C4AB91DDCA020EBE1544327F8184A8154C6
time="2018-04-28T19:27:10+08:00" level=info msg="Del peer from switch."
time="2018-04-28T19:27:10+08:00" level=info msg="Peer connection is closed."
time="2018-04-28T19:27:13+08:00" level=info msg="Failed to dial peer" address="139.198.177.191:46657" error="Error creating peer: dial tcp 139.198.177.191:46657: i/o timeout"
time="2018-04-28T19:27:13+08:00" level=info msg="Dialing peer" address="182.246.106.40:46656"
time="2018-04-28T19:27:14+08:00" level=info msg="Failed to dial peer" address="182.246.106.40:46656" error="Error creating peer: dial tcp 182.246.106.40:46656: connectex: No connection could be made because the target machine actively refused it."
time="2018-04-28T19:27:16+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:26+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:36+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:46+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:27:56+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:28:06+08:00" level=info msg="bk peer num:0 sw peer num:0 []"
time="2018-04-28T19:28:16+08:00" level=info msg="bk peer num:0 sw peer num:0 []"

**⑤** 此时，

找到，并打开：**曾经备份过的1.0.0版时**（由微信群里“思想的苇草”提供的）**“config.toml”替换文件**，
再同时打开了：**1.0.1版，20分钟前 使用 init 命令时**（自动生成的全新）的 **config.toml新文件**，

对比两个文档，发现 如下 **不同之处**：**【出现了：第 二 处 的 问题/现象】**

**【1.0.1版，通过 init 命令 新增出 的 “config.toml”文件中 的 seeds 清单】**

seeds = 

"45.79.213.28:46657,

198.74.61.131:46657,

212.111.41.245:46657,

47.100.214.154:46657,

47.100.109.199:46657,
47.100.105.165:46657"

**【1.0.0版，“思想的苇草”提供的“config.toml”替换文件中 的 seeds清单】**

seeds = 

"139.198.177.243:46657,
139.198.177.164:46657,
139.198.177.190:46657,

47.100.214.154:46657,

139.198.177.231:46657"

**【注：以上的⑤步 操作步骤中，合计：描述了  两处 的 问题/现象】**

**Comment by shengling2008** [comment]
问题1、是怎么清除的？清除后高度应该是0.
问题2、提供的config.toml的seeds的也是种子节点，这个不是问题

**Comment by linqbug** [comment]
回复1、直接删除了C:\Users\Administrator\AppData\Roaming\Bytom目录 和 Bytom Wallet，两个目录。
清除两个目录之后，就在cmd中，执行了 bytomd-windows_amd64.exe，当导入了曾经备份的钱包账号文件之后，高度确实不是0，而是460（此时，节点数为0）。给我感觉：是因为导入和曾经备份的钱包账号文件，所得到的460数值。

回复2、已经明白：这是1.0.1初始化给出的最新的一批种子节点清单。

**Comment by Blockmeta** [comment]
fixed at 1.0.2
