### ISSUE TITLE
sync is hanging forever

### ISSUE THREAD

**Issue by nyclei** [Bytom/bytom#875]
#### Environment
- OS: MacOS

#### Problem Description
I just upgraded from ver 1.0.0 to 1.0.1, and I see the synchronization is no long happening. I cannot confirm if it's because of the upgrade or other cause.

Have no idea of peer discovering strategy, the "Peer Count" is always 0. 
I have 2 Bytom Wallet running on 2 MacBooks side by side, one with synced block number of 1894/1894, another one is 0/0, they don't see each other and no sync is performed.

**Comment by Blockmeta** [comment]
fixed at 1.0.2
