### ISSUE TITLE
Cannot connect wallet miner to pool

### ISSUE THREAD

**Issue by Robbbbbbbbb** [Bytom/bytom#876]
#### Environment

- OS: Win10

#### Problem Description

In the Bytom wallet, there is no ability to connect to a public pool to CPU mine. I understand that the B3s are on the network, however, this is the perfect example of why a joining a pool is a necessity. There are no clear parameters on what to specify when running _bitmond_ either.

#### Suggested Resolution

Provide an option in the Bytom Wallet or CLI to connect to the pool. Looks like the code already exists here: https://github.com/Bytom/B3-Mimic/

**Comment by shengling2008** [comment]
The bytomd wallet is a node, and currently nodes do not support directed connections to the pool. Mine pool is only for miners.
