### ISSUE TITLE
Testnet: Peer is on a different major version. Got 0, expected 1

### ISSUE THREAD

**Issue by NorthFoxz** [Bytom/bytom#877]
#### Environment

- OS: Ubuntu 16.04

#### Problem Description

tried to run testnet on ubuntu 16.04,
however, I can't sync with any peers at all.
keep getting:

level=error msg="Error dialing seed" error="Peer is on a different major version. Got 0, expected 1"

**Comment by shengling2008** [comment]
Someone may not upgrade the version, the version number controls the connection of the lower version
