### ISSUE TITLE
bytomscan.io

### ISSUE THREAD

**Issue by NorthFoxz** [Bytom/bytom#881]
I've made a prototype of bytomscan by this repository,
if you are interested,
help me improve it, thanks!
https://bytomscan.io/

**Comment by Blockmeta** [comment]
nice job.

**Comment by sfx12311** [comment]
cool

**Comment by hybridtangent** [comment]
Great job! Sad to see some address are getting all the blocks! :(

**Comment by unhkd** [comment]
Can you add hashrate and diff to site
