### ISSUE TITLE
[外部测试] 关于vendor目录以及外部依赖

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#882]
看到比原项目使用了`vendor`目录来放置所有的外部依赖，保证了外部依赖的完整性与稳定性。

不过我发现它还有一些缺憾，因为我们无法知道这些依赖的版本是什么，而且还可能带来以下不便：

1. vendor目录下的文件属于第三方，我们不应该修改，但是如果有人不小心修改并提交了，很难发现
2. 因为无法得知依赖的版本，所以不清楚我们使用的版本与当前最新版差多少（比如是很旧的还是很新的）
3. 如果某个第三方依赖在某个版本发现了严重的bug，我们很难检查自己是否使用了该版本
4. 在网上查看了某个依赖项目的资料，但是不确定跟本地vendor中的版本是否一致，试验代码以及出错后定位问题都比较麻烦，因为存在更多的不确定性

总之主要的问题就是我们的依赖的版本没有明示，在未来维护的时候会造成很多问题，建议及早解决。

其中的一个解决方案是使用 <https://github.com/kardianos/govendor>，它主要是在`vendor`目录下增加了一个`vendor.json`文件，有地方可以让我们标示出每个依赖的版本（或者revision），同时提供了一些工具让我们检查是否有文件被修改，以及更多功能。

当然，使用它（或者使用其它的工具），我们都免不了需要有人来手动确定，我们当前使用的依赖到底是什么。这个工作越早做越好，建议考虑。

**Comment by heha37** [comment]
建议用[dep](https://github.com/golang/dep)

**Comment by heha37** [comment]
https://github.com/Bytom/bytom/pull/885

**Comment by Blockmeta** [comment]
good idea

**Comment by HAOYUatHZ** [comment]
https://github.com/Bytom/bytom/pull/885#issuecomment-385898632
