### ISSUE TITLE
[外部测试] Switch.OnStart中似乎有一段代码没用

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#902]
在Switch的OnStart方法中：

https://github.com/Bytom/bytom/blob/2c742b9a98b8032dce64d8da94d1b0dddcee1362/p2p/switch.go#L186-L204

其中下面几行代码，应该没起作用：

https://github.com/Bytom/bytom/blob/2c742b9a98b8032dce64d8da94d1b0dddcee1362/p2p/switch.go#L195-L198

因为在这个时刻`sw.peers`总是空的。

按照我对代码的分析，`Switch.AddNode`方法，只有在三种情况下被调用：

1. `PEXReactor.OnStart` -> `PEXReactor.ensurePeersroutine` -> `PEXReactor.ensurePeers` -> `Switch.DialPeerWithAddress` -> `Switch.AddPeer`

2. `SyncManager.Start` -> `SyncManager.netStart` -> `SyncManager.DialSeeds` -> `Switch.DialSeeds` -> `Switch.dialSeed` -> `Switch.DialPeerWithAddress` -> `Switch.AddPeer`

3. `Switch.OnStart` -> `Switch.listenerRoutine` -> `Switch.addPeerWithConnectionAndConfig` -> `Switch.AddPeer`

还有一个没用上的`Switch.Connect2Switches`就不说了

在前三种情况时，它们的调用都发生在前面提到的那几行代码之后，所以那几行代码应该没什么用。请确认

**Comment by yahtoo** [comment]
对的，你的分析是对的，可以提交pr进行修改。

**Comment by freewind** [comment]
已经提交PR
