### ISSUE TITLE
[外部测试] dashboard和web api的地址写在配置文件config.toml中，但是同时写死在代码中

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#908]
```ini
fast_sync = true
db_backend = "leveldb"
api_addr = "0.0.0.0:9888"
chain_id = "solonet"
[p2p]
laddr = "tcp://0.0.0.0:46658"
seeds = ""
```

注意其中的`api_addr`，就是dashboard以及web-api的地址。我们在这里更改之后，比如改为：

```
api_addr = "0.0.0.0:19888"
```

则比原会在`19888`端口上监听。但是比原在启动的时候，在浏览器中打开的，还是`http://localhost:9888`端口，因为它写死在了代码中：

为什么呢？因为这个地址目前写死在了代码中。

在代码中，这个地址出现在了三个地方，一个是用来表示dashboard的访问地址，位于`node/node.go`中：

https://github.com/Bytom/bytom/blob/d80eb92c55a27359726f297955747113679a1471/node/node.go#L33-L37

https://github.com/Bytom/bytom/blob/d80eb92c55a27359726f297955747113679a1471/node/node.go#L153-L159

https://github.com/Bytom/bytom/blob/59ed6d88b86b504be66d78093bafca3ea9da5a49/util/util.go#L26-L28

关于这个，我有几点疑问：

1. 为什么这个配置项既然出现在了配置文件中，却不使用它呢？岂不是给人以误导。
2. 在代码中，为什么反复出现多次，而不是定义在一个地方？
3. 因为写死的地址的代码将会在`bytomcli`和另一个命令行工具中使用，所以如果config.toml修改了该地址，将导致这些命令行工具出错

**Comment by HAOYUatHZ** [comment]
`bytom/node/node.go` has been fixed.

`coreURL` in `bytom/util/util.go` is used for `bytomcli` / `miner`, and can be configured with env var.
