### ISSUE TITLE
[外部测试] 与读取webapi相关的代码出现大量重复

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#909]
关于字符串`http://localhost:9888`，以及方法：

```go
func MustRPCClient() *rpc.Client {
	env.Parse()
	return &rpc.Client{BaseURL: *coreURL}
}
```

```go
func ClientCall(path string, req ...interface{}) (interface{}, int) {

	var response = &api.Response{}
	var request interface{}

	if req != nil {
		request = req[0]
	}

	client := MustRPCClient()
	client.Call(context.Background(), path, request, response)
	switch response.Status {
	case api.FAIL:
		return nil, ErrRemote
	case "":
		jww.ERROR.Println("Unable to connect to the bytomd")
		return nil, ErrConnect
	}

	return response.Data, Success
}
```

这些代码，在代码库中出现在两个地方。一个是`util/util.go`下，一个是`tools/sendbulktx/core/util.go`下。

https://github.com/Bytom/bytom/blob/59ed6d88b86b504be66d78093bafca3ea9da5a49/util/util.go#L26-L28

https://github.com/Bytom/bytom/blob/f5105a7865a4d398d6b8b987870b0c6b292c0501/tools/sendbulktx/core/util.go#L26-L28

通过它们再继续寻找，就能找到我所说的那一大堆代码了。

它们完全可以只定义一次，出现这么多的重复代码不应该。

**Comment by Blockmeta** [comment]
tools 内部是独立项目， 这部分以后会分开。
