### ISSUE TITLE
block中的output数据没有address字段

### ISSUE THREAD

**Issue by jacky007wang** [Bytom/bytom#919]
比如height 7881，如下所示，是bug还是有特殊意义？

{
    "data": {
        "bits": 2089670227104040700, 
        "hash": "1aa45628037d239b10432a86105d25661e231a8f3d5dea060dc9c28605aa08c4", 
        "size": 360, 
        "nonce": 343816477352283, 
        "height": 7881, 
        "version": 1, 
        "timestamp": 1525512227, 
        "difficulty": "1699199839283432977119549059437970687986080011033002024659469159366656", 
        "transactions": [
            {
                "id": "8843c2a8975631ab8a33f1e1452e550d54f39f6e6e69d263cd268a2dea2bc82b", 
                "size": 57, 
                "inputs": [
                    {
                        "type": "coinbase", 
                        "amount": 0, 
                        "asset_id": "0000000000000000000000000000000000000000000000000000000000000000", 
                        "arbitrary": "e1bb89", 
                        "asset_definition": { }
                    }
                ], 
                "outputs": [
                    {
                        "id": "0a412b2ef32c827a6771d3b274a67acd0551abf4365d76ce951840e252626c34", 
                        "type": "control", 
                        "amount": 41250000000, 
                        "asset_id": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", 
                        "position": 0, 
                        "control_program": "51", 
                        "asset_definition": { }
                    }
                ], 
                "version": 1, 
                "time_range": 0, 
                "status_fail": false
            }
        ], 
        "previous_block_hash": "eb52fbe88260fa085c4aac5991879dea5c57c22655250e1b0e6e4a5beddf30f5", 
        "transaction_merkle_root": "78d734019af6b8976a6f7260856ac9bcc74b1bcfec1c01be09903427a93433ee", 
        "transaction_status_hash": "c9c377e5192668bc0a367e4a4764f11e7c725ecced1d7b6a492974fab1b6d5bc"
    }, 
    "status": "success"
}

**Comment by shengling2008** [comment]
你这个是用怎么版本？输出结果如下：
{
  "bits": 2161727821137910500,
  "difficulty": "7640617385137161009307348744505657205600476961500639119722770042191872",
  "hash": "2469779ccd208f4b53e5ec1dbc21708501f485ed2c21b3d7dffb63534cef510a",
  "height": 77,
  "nonce": 17314088206,
  "previous_block_hash": "5b535382170e1c2c11642fe4b041130cf7bb7a8c4e02f0860275034ace90207b",
  "size": 392,
  "timestamp": 1524554953,
  "transaction_merkle_root": "c16c4dbc61004b0dfed83b709a0242d7faec7cf667bb80edb793dcffce283e76",
  "transaction_status_hash": "c9c377e5192668bc0a367e4a4764f11e7c725ecced1d7b6a492974fab1b6d5bc",
  "transactions": [
    {
      "id": "516ce5e399c7aa2ad34a35c56f03e8ac403f1a501cf077855e86e1af33f89345",
      "inputs": [
        {
          "amount": 0,
          "arbitrary": "4d",
          "asset_definition": {},
          "asset_id": "0000000000000000000000000000000000000000000000000000000000000000",
          "type": "coinbase"
        }
      ],
      "outputs": [
        {
          "address": "bm1qmyn5yn6w3sjzgc948rcycfnkh9uy96d8a8h25q",
          "amount": 41250000000,
          "asset_definition": {},
          "asset_id": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
          "control_program": "0014d927424f4e8c242460b538f04c2676b97842e9a7",
          "id": "0b364e0475dd65a5b45ffce92e2843833d6cc1790c67e3e2bc2fb06e81321fe5",
          "position": 0,
          "type": "control"
        }
      ],
      "size": 76,
      "status_fail": false,
      "time_range": 0,
      "version": 1
    }
  ],
  "version": 1
}

**Comment by Blockmeta** [comment]
not bug.   address is a special format of the control program.
