### ISSUE TITLE
请问与account相关的`quorum`是什么意思？

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#925]
https://github.com/Bytom/bytom/blob/2c742b9a98b8032dce64d8da94d1b0dddcee1362/account/accounts.go#L146

```
func (m *Manager) Create(ctx context.Context, xpubs []chainkd.XPub, 
          quorum int, alias string) (*Account, error) { 
```
看了相关的代码，还是猜不出来`quorum`这个参数是什么意思，有什么用

**Comment by Blockmeta** [comment]
顾名思义。所需的签名数量。

**Comment by freewind** [comment]
能多解释一下吗？不知道这个东西什么时候会用到，为什么需要它
