### ISSUE TITLE
想知道singers.IDGenerate()为什么需要一个这么复杂的算法？

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#926]
https://github.com/Bytom/bytom/blob/9c14fe5e1ef600420ae96fe7107df8b85ebe2ded/blockchain/signers/idgenerate.go#L22-L41

你好。我在看到这个`singers.IDGenerate()`的时候，发现它生成ID的算法还是比较复杂的，请问这个算法的名字是什么？

另外，它除了要提供一个“不重复”的id之外，还有别的什么要求吗？为什么不能直接使用一个uuid呢？

**Comment by Paladz** [comment]
这个点的提出是对的，过于复杂了，后期会简化的，没这个必要
