### ISSUE TITLE
可否根据用户·历次使用中，发现的优质seed，动态更新config.toml文件中的“优质”种子清单

### ISSUE THREAD

**Issue by linqbug** [Bytom/bytom#929]
#### 平台环境

- OS: 【ALL OS】

#### 问题描述

- Bytom钱包客户端，有一个config.toml配置文件，其中，有个seeds种子节点清单。可否**根据用户·历次使用过程中，（原cmd脚本里）发现到的一些“新的、优质的”种子，而进行：动态地 更新（追加或删减）**。**【提出问题的位置】**

举例：

在北京市常住的全节点用户A，今天上午10点，使用了Bytom钱包客户端，后台在检索中，发现有一个优质的种子节点（可能这个节点，是最近三天来，新增的稳定的全节点——也**可能是附近·矿池的24小时运作的稳定IP、或是 附近·一名矿工的稳定IP**），那么，如果 代码 能够根据“**IP属性（A/B/C类网）的逻辑，进行**优选IP**的评级判断**”（最好是能判断出优质的“公网静态IP”），从而，动态地，将这个IP存储、追加到seeds种子节点清单中，那么，会缩短用户客户端，后台检索**可连接seeds**的时长。

好处是：

北京常住的用户A，明天和以后的日子里，可能每次打开Bytom钱包，都会很快连接到config.toml文件中 最新（优化后）的seeds清单的新节点，从而，快速进入下一步——**同步 块高度**的第二阶段……

此时，会产生一个效果：为 **用户A** **私人订制的**本地seeds清单，虽然，与在深圳的**用户B**的seeds清单，是截然不同的。但是，却适合用户A自己 所在的使用场景（IP网段），于是，提高了 地处国内各地 挖矿（非挖矿）用户（A、B、C、D……）们 的节点 连接速度。

从而，实现seeds的用户的自主检索（代码自主判断，类似于机器智能）、自主更新的私人订制。

所以，**不用再担心**：10年、20年后，仍旧需要**开发者参与**，**采用代码升级x.y.z版本**的方式，才能更新到config.toml配置文件的最新、稳定的seeds公网静态IP清单了。

**Comment by Paladz** [comment]
config.toml这个文件是固定的配置文件，节点没有权限去修改。但是如果你喜欢某个特定的节点的话，可以将ip加入到config中

**Comment by MartinDong** [comment]
昨天下面的站点都不返回最新高度了，请问有别的节点可以使用么？
45.79.213.28:46657,198.74.61.131:46657,212.111.41.245:46657,47.100.214.154:46657,47.100.109.199:46657,47.100.105.165:46657
