### ISSUE TITLE
kill signal 给bytomd, bytomd没响应

### ISSUE THREAD

**Issue by gguoss** [Bytom/bytom#94]
#### Environment

- OS: ubuntu17.04 (连测试网络)

#### Problem Description
kill signal 给bytomd, bytomd没响应

启动本地节点连到测试网络， 过一会， 发现没法kill掉本地bytomd。

**Comment by Paladz** [comment]
不容易复线，后期处理

**Comment by zkaip** [comment]
os: Mac OS X
bytom mac 2.0 release

`$./bytomd node --wallet.enable`
也出现这个问题, 最后只能 `kill -9` 杀掉
.
