### ISSUE TITLE
【外部测试】账户新建地址，地址列表是随机排序，而不是先建的在前面，后建的依次排序，也不是按照字母顺序排列

### ISSUE THREAD

**Issue by happy519** [Bytom/bytom#942]
#### Environment

- OS: windows
version: 1.0.1

#### Problem Description
账户新建地址，地址列表是随机排序（杂乱无章），而不是先建的在前面，后建的依次排序，也不是按照字母顺序排列。地址新建的多了，非常难找。半天找不到刚刚新建的地址。

账户新建地址时，地址列表按照序号依次排列，先建的地址在前面，再建的地址依次排列。容易找新建的地址。

1. 在账户详情页面，点击“新建地址”按钮
![1](https://user-images.githubusercontent.com/19317648/39875684-db2060da-54a3-11e8-94c2-11be6f9dbcbd.png)
2. 重复1步骤多建几个。这里我们建4个地址
![2](https://user-images.githubusercontent.com/19317648/39875421-2f79e558-54a3-11e8-924c-6130e3e420f0.png)
3. 现在新建第五个地址，会发现第五个地址不是排在第四个地址“bm1qs0ap2pjvfdg57sg3phzl8de0alkpamj8m9k5rp”后面，而是随机插入地址列表中，也容易判断，地址列表不是按字母顺序排列的。
![3](https://user-images.githubusercontent.com/19317648/39875762-162cbbce-54a4-11e8-9162-c6a5754eb7dd.png)

微信号：happy519machao

**Comment by Paladz** [comment]
新版本中已经添加排序，请下载
