### ISSUE TITLE
【外部测试】页面显示错误，打开设置-》“核心状态”，右边页面显示“核心”二字，而非“核心状态”

### ISSUE THREAD

**Issue by happy519** [Bytom/bytom#943]
#### Environment

- OS: windows/MacOS/Linux
version:1.0.1

#### Problem Description
页面显示错误，打开设置-》“核心状态”，右边页面显示“核心”二字，缺少“状态”二字。

和“访问控制”、“备份与回复”保持一致，显示完整的名字。

1. 点击“设置”-》“核心状态”，右边页面显示“核心”，少了“状态”二字，而“访问控制”、“备份与回复”均与菜单显示一致：
![4](https://user-images.githubusercontent.com/19317648/39877807-7397c632-54a9-11e8-967a-e1d45723f20c.png)
![5](https://user-images.githubusercontent.com/19317648/39877729-45ae791e-54a9-11e8-8154-e69b515ded90.png)
![6](https://user-images.githubusercontent.com/19317648/39877735-48751d10-54a9-11e8-9189-cca5397001c8.png)

微信号：happy519machao

**Comment by ZhitingLin** [comment]
will updated in the next version
