### ISSUE TITLE
web端钱包备份恢复到桌面端钱包后 无法出现新账户交易和余额

### ISSUE THREAD

**Issue by MartinBTM** [Bytom/bytom#957]
#### Environment

- OS: win64

#### Problem Description

1、将web端的钱包账户和密钥进行备份，生成TXT文件
2、将TXT文件导入到桌面端钱包
3、新的账号可以出现在桌面端钱包，但是交易和余额不显示

**Comment by Paladz** [comment]
应该是备份之后有了新的交易，然后钱输出到了找零地址上了。这种情况下多新建几个地址然后按一下重新扫描按钮就好了。
