### ISSUE TITLE
testnet Peer is on a different network. Got wisdom, expected testnet

### ISSUE THREAD

**Issue by zhi-cike** [Bytom/bytom#965]
#### Environment

- OS: mac

#### Problem Description
level=error msg="Error dialing seed" error="Peer is on a different network. Got wisdom, expected testnet"
level=info msg="Failed to add peer" address="172.104.224.219:46656" error="Peer is on a different network. Got wisdom, expected testnet"

version：1.0.2
./bytomd-darwin_amd64 init --chain_id testnet
./bytomd-darwin_amd64 node

**Comment by DinoStray** [comment]
I got the same error, does the testnet working now?

**Comment by Paladz** [comment]
./bytomd-darwin_amd64 init --chain_id testnet

means you init a node to connect to "testnet", so when you receive a connection from "wisdom" net node, your node reject it and give a error message
