### ISSUE TITLE
789个BTM不能提出账户，因为：invalid account alisa zhaojunwb on action 0:fail to find account

### ISSUE THREAD

**Issue by zhaojunwb** [Bytom/bytom#982]
#### Environment
789个BTM不能提出账户
- OS: windows 7 SP1 64位

账户别名：zhaojunwb
账户ID：0DLRA4QM00A02
地址：bm1qf4zjs5jzaqd5hjnc3dn6sg9vchjj8tnu9lqza5

**Comment by tomjauh** [comment]
-13.93177092个BTM  
-7.64301263 个BTM
没进账户
OS: windows 7 SP1 **64位**
账户别名：tomjauh
账户ID：0DLRA4QM00A02
地址：bm1q208kw4uepjklv9sszg5nvks2ehln9fypn4zylu
＝＝＝＝＝＝antpool＝＝＝＝＝＝＝＝＝＝＝＝
时间 | 收款地址 | Transaction链接 | 金额 | 状态
-- | -- | -- | -- | --
2018-05-23 02:13:28 | bm1q208kw4uepjklv9sszg5nvks2ehln9fypn4zylu | 00b4fba3ecab0c29275e75b6a4749737c0c... | -13.93177092 | 已支付
2018-05-22 02:10:56 | bm1q208kw4uepjklv9sszg5nvks2ehln9fypn4zylu | 9d7810aa44c6429b947e6ebe60ceed118f5... | -7.64301263 | 已支付

**Comment by tomjauh** [comment]
帐户 已经显示 数量  thanks
但是要转至  gate.io   
出现下列讯息  无法提出交易

Error submitting form
tx rejected: checking result 0: checking output source: checking value source: checking gas input: checking control program: data stack underflow [prog 76ab1453cf6757990cadf616101229365a0acdff32a48188ae7cac = DUP HASH160 0x53cf6757990cadf616101229365a0acdff32a481 EQUALVERIFY TXSIGHASH SWAP CHECKSIG; args 1d5151d558d145648c06e5049e98b5c5b654b97c276e109f8b50e34d8b752084]
如附图

![3](https://user-images.githubusercontent.com/39557892/40459893-79d1054e-5f36-11e8-92ac-c74f781a1edb.jpg)
![4](https://user-images.githubusercontent.com/39557892/40459903-8703d02a-5f36-11e8-9cea-3e6b8e80de23.jpg)

**Comment by shengling2008** [comment]
@tomjauh  确定一下，是不是你密码错误？

**Comment by tomjauh** [comment]
Dear :
 thanks for reply ASAP.
i try transaction again.
still got zero.

check my process, it's OK?  something missing?

regards!

tomjauh





密码是输入  密钥  还是 登入  密码？？？？？





这是 gate.io 的住址  ok？





2018-05-28 9:13 GMT+08:00 wz <notifications@github.com>:

**Comment by tomjauh** [comment]
收到了  thanks

2018-05-28 9:31 GMT+08:00 Jauh Tom <tomjauh.tomjauh@gmail.com>:

**Comment by shengling2008** [comment]
是登录的密码，不是秘钥

**Comment by shengling2008** [comment]
@tomjauh 这个问题接没？
