### ISSUE TITLE
桌面钱包无法显示余额？

### ISSUE THREAD

**Issue by wuweiluohua** [Bytom/bytom#986]
已创建账户bm1qx6gvxh34feumxl7me7jn46fzg33ph4qf9lhx5w
已发生交易e3b84a423ad85fe47aee597bdc8b3a356ede9ec2c6b87e98d4ecd15c3b3179dc 
所属区块22878
桌面钱包已同步至23135
但是桌面钱包1.0.2（win10 64位）没有余额记录，没有交易记录

**Comment by zxcvnnm** [comment]
https://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com/chromehttps://support.google.com//..com/chromegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegooglegoogle

**Comment by Blockmeta** [comment]
bm1qx6gvxh34feumxl7me7jn46fzg33ph4qf9lhx5w 只是地址不是账户。 你是不是没有恢复账户信息，或者丢失了。

**Comment by zxcvnnm** [comment]
GhhttsjgegnaaGhhttsjgegnaaGhhttsjgegnaaGhhttsjgegnaaGhhttsjgegnaaGhhttsjgegnaa

**Comment by wuweiluohua** [comment]
我知道那个是我创建的账户的地址，我创建账户后没有有换过电脑，也没有其他奇怪的操作，钱包现在能看到这个地址对应的账户，区块也一直同步到最高的，只是看不到余额和交易记录

**Comment by Paladz** [comment]
最新版本的客户端有rescan的功能，可以试试
