### ISSUE TITLE
Bytom Address from desktop to exchange problem

### ISSUE THREAD

**Issue by mastermining** [Bytom/bytom#989]
#### Environment

- OS: windows 10 64bit

**Comment by onegiantcock** [comment]
which exchange?  what is the destination address?   What are the error message(s)

**Comment by mastermining** [comment]
on Kucoin, try sending Bytom on to desktop exchange, it says invalid address.

**Comment by Paladz** [comment]
These exchanges support Bytom mainnet
https://coinmarketcap.com/currencies/bytom/#markets
