### ISSUE TITLE
OS X Transaction error:   tx rejected

### ISSUE THREAD

**Issue by patmccormick** [Bytom/bytom#990]
#### Environment

Mac OS X High Sierra 10.13.2

NOTE:  I downloaded & installed the version on Bytom.io.  I',m hoping this is the same version, but there's no additional info on Bytom.

#### Problem Description

Cannot send BTM from desktop wallet to another wallet by address

I set up a normal transaction from my local account.  I have tried with and without a password:

![screen shot 2018-05-23 at 9 44 28 am](https://user-images.githubusercontent.com/5289909/40431869-efa00172-5e6d-11e8-8837-a37ffba41025.png)

**Comment by Paladz** [comment]
should be wrong password

**Comment by Tapi2508** [comment]
Oki

**Comment by sdem2002** [comment]
which password? my client hasn't any password

**Comment by Paladz** [comment]
The password that encrypt your private key
